<?php
namespace Modules\Shop\Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EPT20_20ETC_Transpalet_2_Detailed extends Seeder {
    public function run(): void {
        $p = DB::table('shop_products')->where('sku', 'EPT20-20ETC')->first();
        if (!$p) {$this->command->error('❌ Master bulunamadı: EPT20-20ETC'); return; }

        DB::table('shop_products')->where('product_id', $p->product_id)->update([
            'long_description' => json_encode(['tr' => "<section><h2>İXTİF EPT20-20ETC: Soğuk Zincirde Güvenilir Son Adım</h2><p>Soğuk odadan rampaya, rampadan mağaza rafına kadar her dakika kıymetlidir. -25℃ seviyelerine düşen ortamlar; akü performansını azaltır, elektronik bileşenleri zorlar ve operatörlerin manevra kabiliyetini sınar. İXTİF EPT20-20ETC bu zorluğa cevap verir: tam sızdırmaz gövde, IP67 korumalı tahrik sistemi ve kaymaya karşı üstün tutunma sağlayan kauçuk tahrik tekeriyle soğuk depo içi kısa mesafe ve son kilometre taşımalarında süreklilik sağlar. Süpermarket arka depolarından dağıtım merkezlerine, merkezi mutfaklardan catering operasyonlarına kadar sıcak-soğuk geçişlerinde temposunu hiç düşürmeden ürün akışını hızlandırır.</p></section>\n<section><h3>Teknik</h3><p>2000 kg nominal kapasite ve 600 mm yük merkezi mesafesi ile EPT20-20ETC, 1673 mm toplam uzunluk ve 560/685 mm gövde genişliği seçenekleriyle dar koridorlarda rahat ilerler. 1505 mm dönüş yarıçapı, tıkanan kapı eşikleri ve dar rampa alanlarında bile yön değişimini kolaylaştırır. 48V/40Ah Li‑Ion batarya 0.9 kW tahrik ve 0.8 kW kaldırma motorlarını besler; elektromanyetik servis fren ile güvenli duruş sağlar. 4/4.5 km/s hız, 0.027/0.038 m/s kaldırma ve 0.059/0.039 m/s indirme hızı; 8/20% eğim kabiliyetiyle birlikte soğuk oda kapılarındaki rampa geçişlerini hızlandırır. IP67 korumalı motor/elektronik, kauçuk/poliüretan teker kombinasyonu ve tam sızdırmaz şasi; yoğun yoğuşma ve nemin yol açtığı arızaların önüne geçer. Standart 1150 mm çatal uzunluğu, 50/150 mm kesit ölçüleri ve 560/685 mm çatal aralığıyla gıda ve içecek kasaları, süt ürünleri ve taze meyve-sebze paletlerinin güvenle aktarımını mümkün kılar.</p></section>\n<section><h3>Sonuç</h3><p>İşletmenize, soğukta hız ve süreklilik kazandıracak kompakt bir çözüm arıyorsanız EPT20-20ETC doğru seçimdir. Teknik destek, demo veya fiyatlandırma için bizi arayın: 0216 755 3 555.</p></section>"], JSON_UNESCAPED_UNICODE),
            'primary_specs' => json_encode([["icon" => "weight-hanging", "label" => "Kapasite", "value" => "2000 kg"], ["icon" => "battery-full", "label" => "Batarya", "value" => "48V 40Ah Li-Ion"], ["icon" => "gauge", "label" => "Hız", "value" => "4 / 4.5 km/s"], ["icon" => "arrows-turn-right", "label" => "Dönüş", "value" => "1505 mm"]], JSON_UNESCAPED_UNICODE),
            'highlighted_features' => json_encode([["icon" => "shield-alt", "title" => "IP67 Korumalı Tahrik", "description" => "Motor ve elektronik korozyona ve neme karşı güvence altında."], ["icon" => "battery-full", "title" => "Li‑Ion Enerji", "description" => "48V 40Ah batarya ile hızlı hazırlık ve kesintisiz vardiya."], ["icon" => "arrows-alt", "title" => "Kompakt Manevra", "description" => "1505 mm dönüş yarıçapı ile dar koridor çevikliği."], ["icon" => "snowflake", "title" => "Soğuk Dayanımı", "description" => "-25℃ koşullarda güvenilir çalışma, tam sızdırmaz tasarım."], ["icon" => "circle-notch", "title" => "Yüksek Tutunma", "description" => "Kauçuk tahrik tekeri ile kaygan zeminde kontrollü sürüş."], ["icon" => "cog", "title" => "Basit Bakım", "description" => "Mekanik direksiyon ve modüler yapı ile hızlı servis."]], JSON_UNESCAPED_UNICODE),
            'use_cases' => json_encode([["icon" => "store", "text" => "Süpermarket arka depolarında soğuk oda giriş-çıkış transferi"], ["icon" => "warehouse", "text" => "Dağıtım merkezlerinde soğuk ve ambient bölgeler arası çapraz sevkiyat"], ["icon" => "snowflake", "text" => "Donuk ve soğutulmuş ürün koridorlarında kısa mesafe taşıma"], ["icon" => "cart-shopping", "text" => "Gıda içecek toplama alanlarında rampa yükleme-boşaltma"], ["icon" => "pills", "text" => "İlaç ve medikal depolarda sıcaklık kontrollü ürün taşınması"], ["icon" => "flask", "text" => "Kimyasal ve katkı depolarında sızdırmaz gövdeyle güvenli operasyon"], ["icon" => "industry", "text" => "Merkezi mutfak ve catering tedarik akışında hızlı iç lojistik"], ["icon" => "box-open", "text" => "E-ticaret soğuk zincir siparişlerinde palet-parça aktarma"]], JSON_UNESCAPED_UNICODE),
            'competitive_advantages' => json_encode([["icon" => "bolt", "text" => "IP67 korumalı tahrik ve elektronik ile arıza riskinin azalması"], ["icon" => "battery-full", "text" => "Li‑Ion enerji ile hızlı şarj ve tutarlı performans"], ["icon" => "arrows-alt", "text" => "1505 mm dönüş yarıçapı ile dar alan çevikliği"], ["icon" => "shield-alt", "text" => "Tam sızdırmaz yapı ve korozyona dayanıklı komponentler"], ["icon" => "warehouse", "text" => "Kompakt gövde sayesinde yoğun koridorlarda akıcı akış"]], JSON_UNESCAPED_UNICODE),
            'target_industries' => json_encode([["icon" => "box-open", "text" => "E-ticaret ve Fulfillment"], ["icon" => "warehouse", "text" => "3PL ve Lojistik Hizmetleri"], ["icon" => "store", "text" => "Perakende Zincirler"], ["icon" => "cart-shopping", "text" => "FMCG Dağıtım"], ["icon" => "snowflake", "text" => "Gıda ve Soğuk Zincir"], ["icon" => "wine-bottle", "text" => "İçecek Lojistiği"], ["icon" => "pills", "text" => "İlaç ve Medikal"], ["icon" => "flask", "text" => "Kimyasal Depolama"], ["icon" => "spray-can", "text" => "Kozmetik ve Kişisel Bakım"], ["icon" => "microchip", "text" => "Elektronik ve Teknoloji"], ["icon" => "tv", "text" => "Beyaz Eşya Dağıtım"], ["icon" => "car", "text" => "Otomotiv Yedek Parça"], ["icon" => "tshirt", "text" => "Tekstil ve Hazır Giyim"], ["icon" => "shoe-prints", "text" => "Ayakkabı ve Aksesuar"], ["icon" => "couch", "text" => "Mobilya ve Ev Dekorasyon"], ["icon" => "hammer", "text" => "Yapı Market ve DIY"], ["icon" => "print", "text" => "Matbaa ve Ambalaj"], ["icon" => "book", "text" => "Yayıncılık ve Kırtasiye"], ["icon" => "seedling", "text" => "Tarım ve Bahçe Ürünleri"], ["icon" => "paw", "text" => "Evcil Hayvan Ürünleri"]], JSON_UNESCAPED_UNICODE),
            'warranty_info' => json_encode(['coverage' => 'Makine satın alım tarihinden itibaren 12 ay fabrika garantisine sahiptir. Li‑Ion batarya modülleri 24 ay garanti kapsamındadır. Garanti normal kullanımda üretim hatalarını kapsar.', 'duration_months' => 12, 'battery_warranty_months' => 24], JSON_UNESCAPED_UNICODE),
            'accessories' => json_encode([["icon" => "plug", "name" => "Standart Şarj Cihazı", "description" => "48V Li‑Ion için uyumlu, günlük kullanım", "is_standard" => true, "price" => null], ["icon" => "cog", "name" => "Hızlı Şarj Ünitesi", "description" => "Vardiya aralarında hızlı dolum", "is_standard" => false, "price" => "Talep üzerine"], ["icon" => "circle-notch", "name" => "Kauçuk Tahrik Teker Seti", "description" => "Yüksek tutunma, kaygan zeminler", "is_standard" => true, "price" => null], ["icon" => "battery-full", "name" => "Genişletilmiş Batarya", "description" => "48V 60Ah Li‑Ion paket", "is_standard" => false, "price" => "Talep üzerine"]], JSON_UNESCAPED_UNICODE),
            'certifications' => json_encode([["icon" => "certificate", "name" => "CE", "year" => "2024", "authority" => "EU"]], JSON_UNESCAPED_UNICODE),
            'faq_data' => json_encode([["question" => "Soğuk odada -25℃ koşullarda kesintisiz çalışmayı nasıl sağlar?", "answer" => "IP67 korumalı tahrik/elektronik ve tam sızdırmaz gövde yoğuşma ve neme karşı güvence sağlar. Li‑Ion batarya düşük sıcaklıklarda dahi tutarlı gerilim sunar."], ["question" => "Süpermarket depolarındaki dar alanlarda manevrası yeterli mi?", "answer" => "1505 mm dönüş yarıçapı ve 1673 mm toplam uzunluk dar koridorlarda yön değişimini kolaylaştırır. 560/685 mm gövde genişliği farklı palet hatlarına uyum verir."], ["question" => "Rampalarda çekiş kaybı yaşamamak için hangi özellikler var?", "answer" => "Kauçuk tahrik tekeri kaygan yüzeylerde yüksek tutunma sağlar. Elektromanyetik fren kontrollü duruş sunarken 8/20% eğim kabiliyeti rampa geçişlerini destekler."], ["question" => "Batarya değişimi veya bakımı için özel ekipman gerekir mi?", "answer" => "Modüler Li‑Ion yapı bakım ihtiyacını azaltır ve harici hızlı şarj ile kısa molalarda dolum yapılabilir. Günlük kontroller kullanıcı tarafından kolayca yapılır."], ["question" => "Yoğuşma ve korozyona karşı koruma nasıl sağlanıyor?", "answer" => "Tam sızdırmaz tasarım, contalı muhafazalar ve korozyona dayanıklı malzemelerle elektronik ve mekanik parçalar nemli ortamlarda korunur."], ["question" => "Standart çatal ölçüsü ve palet uyumluluğu nedir?", "answer" => "50/150/1150 mm çatal ölçüleri ve 560/685 mm çatal aralığı ile EUR ve ISO paletlerde güvenli giriş/çıkış sağlanır. Düşük 80/105 mm yükseklik kapı eşiklerini kolaylaştırır."], ["question" => "Operatör güvenliği için fren ve kontrol sistemi neler sunar?", "answer" => "Elektromanyetik servis fren hızlı tepki verir. Mekanik direksiyon basit ve öngörülebilirdir; IP67 korumalı kontrol sistemi güvenilir çalışma sağlar."], ["question" => "Günlük bakımda hangi noktalar kontrol edilmelidir?", "answer" => "Tekerlek aşınması, çatal kilidi, fren testi, şarj portu durumu ve contaların bütünlüğü günlük kontrol listesindedir. Gerekirse yağlama ve temizlik uygulanır."], ["question" => "Hangi sektörlerde verim avantajı daha belirgin olur?", "answer" => "Gıda, içecek, ilaç ve 3PL gibi sıcak-soğuk geçişlerin yoğun olduğu operasyonlarda yükleme/boşaltma çevrim sürelerini düşürerek verimi artırır."], ["question" => "Mevcut depolama altyapısına entegrasyon nasıl yapılır?", "answer" => "Koridor genişliği ve palet akışı doğrulanır; 560/685 mm genişlik seçenekleri ve 1150 mm çatal boyu hatlara uyarlanır. Eğitimle operatör devreye alınır."], ["question" => "Yedek parça ve saha servis desteği nasıl sağlanır?", "answer" => "Yetkili servis ağı üzerinden periyodik bakım planları ve hızlı parça tedariki sunulur. Uzaktan destek ile arıza ön teşhisi yapılabilir."], ["question" => "Garanti kapsamı ve iletişim bilgisi nedir?", "answer" => "Makine 12 ay, Li‑Ion batarya 24 ay garanti kapsamındadır. İXTİF satış ve teknik destek için 0216 755 3 555 numarasından iletişime geçebilirsiniz."]], JSON_UNESCAPED_UNICODE),
            'updated_at' => now(),
        ]);

        $this->command->info('✅ Detailed güncellendi: EPT20-20ETC');
    }
}
