<?php
namespace Modules\Shop\Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RPL201_Transpalet_2_Detailed extends Seeder {
    public function run(): void {
        $p = DB::table('shop_products')->where('sku', 'RPL201')->first();
        if (!$p) { return; }
        DB::table('shop_products')->where('product_id', $p->product_id)->update([
            'long_description' => json_encode(['tr' => "<section><h2>Uzun Mesafe Verimliliği İçin Tasarlandı</h2>\n<p>RPL201, yoğun vardiyaların temposuna uyum sağlayan, katlanır platform ve yan korumalarla operatörün konforunu ön plana alan 2.0 ton sınıfı platformlu transpalettir. Güçlü AC sürüş sistemi, bakım gerektirmeyen Li‑Ion enerji paketi ve ergonomik güç destekli direksiyon sayesinde uzun mesafe iç lojistik akışlarında duruşları azaltır, depo verimliliğini artırır. Harici şarj soketi ile batarya kapağına erişmeden hızlı bağlantı yapılır; bu da fırsat şarjı disiplinini kolaylaştırır ve günlük operasyon ritmine sorunsuz entegre olur.</p></section>\n<section><h3>Teknik</h3>\n<p>24V/205Ah Li‑Ion akü, 1.6 kW sürüş ve 2.2 kW kaldırma motoru ile 7.5/8 km/s (yüklü/boş) hız sunar. 2000 kg kapasite, 600 mm yük merkezi, 1531 mm dingil açıklığı ve 1806 mm dönüş yarıçapı dar koridorlarda etkin manevra kabiliyeti sağlar. 55×170×1150 mm çatal ölçüsü ve 540/685 mm çatallar arası mesafe yaygın palet standartlarına tam uyumludur. Stabilite için batarya bölmesine entegre karşı ağırlık ve yeniden konumlandırılmış castor tekerleri kullanılır; virajlarda otomatik hız azaltma yazılımı yük ve şasi denge davranışını korur. Poliüretan teker kombinasyonu zemin dostu, düşük gürültülü çalışma sunar. Elektromanyetik servis freni ve elektronik direksiyon sistemi operatör güvenliğini artırır.</p></section>\n<section><h3>Sonuç</h3>\n<p>Uzun mesafe, yoğun tempo ve düşük bakım maliyeti ihtiyacı olan depolar için RPL201 akılcı bir seçimdir. Teknik detay ve teklif için 0216 755 3 555.</p></section>"], JSON_UNESCAPED_UNICODE),
            'primary_specs' => json_encode([["icon" => "weight-hanging", "label" => "Kapasite", "value" => "2000 kg"], ["icon" => "battery-full", "label" => "Batarya", "value" => "24V 205Ah Li-Ion (harici şarj soketi)"], ["icon" => "gauge", "label" => "Hız", "value" => "7.5/8 km/s (yüklü/boş)"], ["icon" => "arrows-turn-right", "label" => "Dönüş Yarıçapı", "value" => "1806 mm"]], JSON_UNESCAPED_UNICODE),
            'highlighted_features' => json_encode([["icon" => "battery-full", "title" => "Li-Ion teknoloji", "description" => "Fırsat şarjı ve sıfır bakım ile yüksek vardiya sürekliliği"], ["icon" => "bolt", "title" => "Yüksek stabilite", "description" => "Ağırlık merkezi iyileştirmesi ve castor düzeni ile güvenli sürüş"], ["icon" => "arrows-alt", "title" => "Dönüşte hız azaltma", "description" => "Virajlarda otomatik hız düşümü ile yük güvenliği artar"], ["icon" => "hand", "title" => "Güç destekli direksiyon", "description" => "Elektronik güç desteğiyle operatör yorgunluğu azalır"], ["icon" => "plug", "title" => "Harici şarj prizi", "description" => "Batarya kapağını açmadan hızlı ve güvenli bağlantı"], ["icon" => "shield-alt", "title" => "Gövde koruma", "description" => "Geniş çerçeve ve yan kollar arka kapağı darbelerden korur"]], JSON_UNESCAPED_UNICODE),
            'use_cases' => json_encode([["icon" => "warehouse", "text" => "Büyük depolarda uzun mesafe palet transferi ve hat besleme"], ["icon" => "box-open", "text" => "Lojistik merkezlerinde yoğun çapraz sevkiyat operasyonları"], ["icon" => "store", "text" => "Perakende DC’lerde raf arası akış ve kamyon boşaltma"], ["icon" => "industry", "text" => "Ağır hizmet gerektiren üretim alanlarında WIP taşımaları"], ["icon" => "car", "text" => "Otomotiv yan sanayide JIT/JIS malzeme akışı"], ["icon" => "flask", "text" => "Kimya depolarında güvenli, sabit hızla iç lojistik"], ["icon" => "snowflake", "text" => "Soğuk depo hazırlık alanlarında hızlı besleme"], ["icon" => "pills", "text" => "İlaç dağıtım depolarında hassas yük yönetimi"]], JSON_UNESCAPED_UNICODE),
            'competitive_advantages' => json_encode([["icon" => "bolt", "text" => "Katlanır platform ve yan kollarla ağır hizmete uygun şasi dayanımı"], ["icon" => "battery-full", "text" => "Bakım gerektirmeyen Li-Ion ve harici şarj ile minimum duruş"], ["icon" => "arrows-alt", "text" => "Otomatik dönüş hız kontrolü ve yüksek manevra kabiliyeti"], ["icon" => "shield-alt", "text" => "Geniş çerçeve ve korumalar ile çarpışma riskine karşı güven"]], JSON_UNESCAPED_UNICODE),
            'target_industries' => json_encode([["icon" => "box-open", "text" => "E-ticaret ve Fulfillment"], ["icon" => "warehouse", "text" => "3PL ve Sözleşmeli Lojistik"], ["icon" => "store", "text" => "Perakende Dağıtım Merkezleri"], ["icon" => "cart-shopping", "text" => "Hızlı Tüketim (FMCG)"], ["icon" => "snowflake", "text" => "Gıda & Soğuk Zincir"], ["icon" => "wine-bottle", "text" => "İçecek Lojistiği"], ["icon" => "pills", "text" => "İlaç ve Medikal"], ["icon" => "flask", "text" => "Kimya & Petrokimya"], ["icon" => "spray-can", "text" => "Kozmetik & Kişisel Bakım"], ["icon" => "microchip", "text" => "Elektronik & Yarı İletken"], ["icon" => "tv", "text" => "Beyaz Eşya & Tüketici Elektroniği"], ["icon" => "car", "text" => "Otomotiv & Tedarikçileri"], ["icon" => "couch", "text" => "Mobilya & Ev Tekstili"], ["icon" => "tshirt", "text" => "Tekstil & Hazır Giyim"], ["icon" => "industry", "text" => "Genel Sanayi & Metal"], ["icon" => "hammer", "text" => "Yapı Malzemeleri"], ["icon" => "seedling", "text" => "Tarım & Gıda İşleme"], ["icon" => "book", "text" => "Kırtasiye & Matbaa Depoları"], ["icon" => "print", "text" => "Ambalaj & Baskı"], ["icon" => "briefcase", "text" => "B2B Toptan Depoları"]], JSON_UNESCAPED_UNICODE),
            'warranty_info' => json_encode(['coverage' => 'Makine 12 ay, Li-Ion batarya 24 ay garanti.', 'duration_months' => 12, 'battery_warranty_months' => 24], JSON_UNESCAPED_UNICODE),
            'accessories' => json_encode([["icon" => "plug", "name" => "24V-100A Harici Şarj Cihazı", "description" => "Hızlı harici şarj için endüstriyel bağlantı", "is_standard" => true, "price" => null], ["icon" => "cog", "name" => "PU Tahrik Teker Seti", "description" => "Düşük gürültü ve zemine uyum", "is_standard" => true, "price" => null], ["icon" => "grip-lines-vertical", "name" => "Çatal Uzunluğu 1220 mm", "description" => "Standart 1150 mm yerine uzun çatal", "is_standard" => false, "price" => "Talep üzerine"], ["icon" => "wrench", "name" => "Ağırlık Sistemi Entegrasyonu", "description" => "Çatallarda tartım opsiyonu", "is_standard" => false, "price" => "Talep üzerine"]], JSON_UNESCAPED_UNICODE),
            'certifications' => json_encode([["icon" => "certificate", "name" => "CE", "year" => "2024", "authority" => "EU"]], JSON_UNESCAPED_UNICODE),
            'faq_data' => json_encode([["question" => "Bu model uzun mesafe vardiyalarda operatör konforunu nasıl artırır?", "answer" => "Katlanır süspansiyonlu platform ve yan kollar, titreşimi azaltır ve operatörün güvenle yüksek hızda sürmesini sağlar. Elektronik destekli direksiyon yorgunluğu düşürür."], ["question" => "Dönüşlerde hız azaltma sistemi ne avantaj sağlar?", "answer" => "Virajlara girişte otomatik olarak hız kısılır; yük stabilitesi ve operatör güvenliği artar, devrilme ve palet kayması riski azalır."], ["question" => "Harici şarj soketi bakım süreçlerini nasıl etkiler?", "answer" => "Batarya kapağını açmadan güvenli bağlantı sunar, bakım sürelerini kısaltır ve hatalı bağlantı riskini azaltır. Vardiya aralarında fırsat şarjına uygundur."], ["question" => "Li-Ion akü ile tipik çalışma süreleri ve şarj döngüsü nasıldır?", "answer" => "24V 205Ah paket, fırsat şarjı ile gün içine yayılmış aralarda yüksek erişilebilirlik sağlar. Planlı bir vardiyada duruş süreleri belirgin şekilde azalır."], ["question" => "Dar koridorlarda manevra kabiliyeti hangi ölçülerle tanımlanır?", "answer" => "1806 mm dönüş yarıçapı ve 804 mm yüzeye kadar uzunluk; 734 mm genişlikle birlikte dar koridorlarda güvenli dönüş sağlar."], ["question" => "Stabilite için hangi mekanik iyileştirmeler yapıldı?", "answer" => "Batarya bölmesinin altına eklenen karşı ağırlık ve yeniden konumlanan denge tekerleri ani duruş ve dönüşlerde aracı dengede tutar."], ["question" => "Hız ve kaldırma performansı değerleri nelerdir?", "answer" => "Yürüyüş hızı 7.5/8 km/s (yüklü/boş), kaldırma hızı 0.050/0.054 m/s, indirme hızı 0.067/0.054 m/s olup verimli akış sağlar."], ["question" => "Bakım kalemleri ve periyotları nasıldır?", "answer" => "Li-Ion akü bakım gerektirmez. Günlük görsel kontroller ve tekerlek aşınma kontrolü önerilir; elektromanyetik fren sistemi periyodik test edilmelidir."], ["question" => "Standart çatal ölçüleri ve varyant seçenekleri nelerdir?", "answer" => "Standart 55×170×1150 mm; 1220 mm dahil farklı uzunluklar ve 540/685 mm çatal aralığı seçenekleri mevcuttur."], ["question" => "Yedek parça ve servis süreçleri nasıl yönetilir?", "answer" => "Türkiye genelinde yetkili servis ağı ve yedek parça lojistiğiyle hızlı müdahale sağlanır; bakım planları operasyonel kesintiyi azaltır."], ["question" => "Garanti süresi ve kapsamı nedir?", "answer" => "Makine 12 ay, Li-Ion batarya modülleri 24 ay üretim hatalarına karşı garanti altındadır."], ["question" => "Satın alma ve yerinde demo için nasıl ilerleyebilirim?", "answer" => "Ürün, demo ve fiyatlandırma için İXTİF ile iletişime geçin: 0216 755 3 555."]], JSON_UNESCAPED_UNICODE),
            'updated_at' => now(),
        ]);
    }
}
