<?php
namespace Modules\Shop\Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RSL161_Istif_2_Detailed extends Seeder {
    public function run(): void {
        $p = DB::table('shop_products')->where('sku', 'RSL161')->first();
        if (!$p) {$this->command->error('❌ Master bulunamadı: RSL161'); return; }

        DB::table('shop_products')->where('product_id', $p->product_id)->update([
            'long_description' => json_encode(['tr' => '<section><h2>RSL161: Ağır Hizmet Li-Ion İstif Makinesi</h2><p>Depolarda mesafe uzadıkça operatör konforu ve enerji sürekliliği kritik hâle gelir. Katlanır platformu dar koridor çevikliğiyle birleştiren RSL161, gün boyu istifleme ve taşıma işlerinde yüksek hız, düşük yorgunluk ve tutarlı güvenlik sağlar. Süratli kaldırma/indirme oranları ve 11 km/s azami seyir hızı, throughput hedeflerini gerçek operasyon koşullarında ulaşılabilir kılar. </p></section><section><h3>Teknik Güç ve Verimlilik</h3><p>205Ah Li-Ion batarya, fırsat şarjına uygun kimyası sayesinde plan dışı duruşları azaltır; harici şarj soketi batarya bölmesini açmadan bağlantı imkânı verir. AC sürüş motoru 3 kW gücüyle 9/11 km/saate varan seyir sağlar; 4.5 kW kaldırma motoru ise 0.26 m/s seviyesinde hassas ve hızlı kaldırma/indirme kabiliyeti sunar. Elektronik güç destekli direksiyon, dönüşlerde otomatik hız düşürme ile stabiliteyi artırır. 850 mm toplam genişlik ve kompakt şasi yapısı, 1000×1200 çapraz paletlerde dar alan manevrasını kolaylaştırır. Yeni renkli gösterge, akü ve sistem parametrelerinin anlık takibini sağlar; oransal hidrolik kontrol, yükü rafa zarar vermeden milimetrik konumlandırır. </p></section><section><h3>Operasyonel Kazançlar</h3><p>Uzun mesafe iç taşıma ile sık istifin bir arada yürütüldüğü tesislerde RSL161, operatörün ayakta veya platform üstünde güvenli biçimde ilerlemesini sağlar. Titreşim sönümlü platform sürüş konforunu yükseltir; ergonomik timon başı farklı el boyutlarına uygundur. Planlı bakım aralıkları uzundur ve Li-Ion batarya bakım gerektirmez; bu sayede toplam sahip olma maliyeti düşer. VDI 2198’e göre 54.4 t/saat işlem hacmi ve 37 t/kWh enerji verimliliği, yoğun vardiyalarda hedeflenen throughput’u destekler. Depo güvenliği açısından elektromanyetik fren ve yokuş kalkış kontrolü, riskli alanlarda ek koruma katmanı oluşturur. </p></section><section><h3>Sonuç</h3><p>İster üretim beslemesi ister sevkiyat öncesi konsolidasyon olsun, RSL161 iş akışını hızlandırır, operatör yorgunluğunu azaltır ve enerji masrafını kontrol altında tutar. Demo ve teknik danışmanlık için 0216 755 3 555. </p></section>'], JSON_UNESCAPED_UNICODE),
            'primary_specs' => json_encode([['icon' => 'weight-hanging', 'label' => 'Kapasite', 'value' => '1600 kg'], ['icon' => 'battery-full', 'label' => 'Batarya', 'value' => '24V / 205Ah Li-Ion'], ['icon' => 'gauge', 'label' => 'Hız', 'value' => '9 / 11 km/s (yüklü/boş)'], ['icon' => 'arrows-turn-right', 'label' => 'Dönüş Yarıçapı', 'value' => '1560 mm']], JSON_UNESCAPED_UNICODE),
            'highlighted_features' => json_encode([['icon' => 'battery-full', 'title' => 'Li-Ion Enerji Avantajı', 'description' => '205Ah paket ile hızlı şarj, ara vermeden vardiya sürekliliği.'], ['icon' => 'bolt', 'title' => 'Yüksek Performans', 'description' => '11 km/s sürüş ve 0.26 m/s kaldırma hızıyla çevik operasyon.'], ['icon' => 'arrows-alt', 'title' => 'Kompakt Şasi', 'description' => '850 mm genişlik, dar raf aralarında kolay sürüş.'], ['icon' => 'shield-alt', 'title' => 'Güvenli Dönüş', 'description' => 'Elektronik direksiyon ve dönüşte otomatik hız azaltma.'], ['icon' => 'hand', 'title' => 'Ergonomik Kontrol', 'description' => 'Rahat tutuşlu timon ve oransal hidrolik kontrol.'], ['icon' => 'tv', 'title' => 'Renkli Gösterge', 'description' => 'Akü ve sistem parametrelerini anlık izleyin.']], JSON_UNESCAPED_UNICODE),
            'use_cases' => json_encode([['icon' => 'warehouse', 'text' => 'Yoğun vardiyalı depolarda raf arası istif ve besleme'], ['icon' => 'box-open', 'text' => 'Fulfillment alanlarında palet toplama ve sevk hazırlığı'], ['icon' => 'store', 'text' => 'Perakende DC’lerde ürün transferi ve cross-docking'], ['icon' => 'snowflake', 'text' => 'Soğuk oda giriş-çıkışlarında kontrollü taşıma'], ['icon' => 'pills', 'text' => 'İlaç lojistiğinde hassas ürünlerin güvenli istifi'], ['icon' => 'car', 'text' => 'Otomotiv yedek parça hat besleme ve kitting'], ['icon' => 'industry', 'text' => 'Üretim hücrelerinde WIP palet hareketi'], ['icon' => 'flask', 'text' => 'Kimya depolarında dökülme riskine karşı hassas kaldırma']], JSON_UNESCAPED_UNICODE),
            'competitive_advantages' => json_encode([['icon' => 'bolt', 'text' => 'Yüksek seyir ve kaldırma hızlarıyla vardiya başına daha fazla palet.'], ['icon' => 'battery-full', 'text' => 'Li-Ion ile fırsat şarjı ve sıfır bakım; daha yüksek kullanılabilirlik.'], ['icon' => 'arrows-alt', 'text' => 'Kompakt şasi ve hassas direksiyonla dar alan çevikliği.'], ['icon' => 'shield-alt', 'text' => 'Dönüşte hız azaltma, elektromanyetik fren ve güvenli duruş.'], ['icon' => 'star', 'text' => 'Renkli ekran ile anlık izleme ve hata teşhisi hızlanır.']], JSON_UNESCAPED_UNICODE),
            'target_industries' => json_encode([['icon' => 'box-open', 'text' => 'E-ticaret ve fulfillment'], ['icon' => 'warehouse', 'text' => '3PL ve sözleşmeli lojistik'], ['icon' => 'store', 'text' => 'Perakende dağıtım merkezleri'], ['icon' => 'cart-shopping', 'text' => 'Hızlı tüketim ürünleri (FMCG)'], ['icon' => 'snowflake', 'text' => 'Gıda-soğuk zincir depoları'], ['icon' => 'wine-bottle', 'text' => 'İçecek dağıtım lojistiği'], ['icon' => 'pills', 'text' => 'İlaç ve medikal depolar'], ['icon' => 'flask', 'text' => 'Kimyasal hammaddeler ve karışım alanları'], ['icon' => 'spray-can', 'text' => 'Kozmetik ve kişisel bakım'], ['icon' => 'microchip', 'text' => 'Elektronik ve yüksek değerli ürünler'], ['icon' => 'tv', 'text' => 'Beyaz eşya ve dayanıklı tüketim'], ['icon' => 'car', 'text' => 'Otomotiv yedek parça ve CKD hatları'], ['icon' => 'tshirt', 'text' => 'Tekstil ve hazır giyim'], ['icon' => 'shoe-prints', 'text' => 'Ayakkabı ve moda aksesuarları'], ['icon' => 'couch', 'text' => 'Mobilya ve ev dekor'], ['icon' => 'hammer', 'text' => 'Yapı market ve hırdavat'], ['icon' => 'print', 'text' => 'Matbaa ve ambalaj'], ['icon' => 'book', 'text' => 'Yayıncılık ve kırtasiye'], ['icon' => 'seedling', 'text' => 'Tarım ve bahçe ürünleri'], ['icon' => 'paw', 'text' => 'Pet ürünleri ve yem depoları'], ['icon' => 'industry', 'text' => 'Ağır sanayi ve üretim hücreleri'], ['icon' => 'building', 'text' => 'Kamu depo ve belediye ambarları']], JSON_UNESCAPED_UNICODE),
            'warranty_info' => json_encode(['coverage' => 'Makineye satın alım tarihinden itibaren 12 ay fabrika garantisi sağlanır. Li-Ion batarya modülleri ise satın alım tarihinden itibaren 24 ay boyunca üretim hatalarına karşı garanti kapsamındadır.', 'duration_months' => 12, 'battery_warranty_months' => 24], JSON_UNESCAPED_UNICODE),
            'accessories' => json_encode([['icon' => 'plug', 'name' => 'Harici hızlı şarj cihazı 100A', 'description' => '24V 205Ah Li-Ion pakete uygun, vardiyalar arasında fırsat şarjı sağlar.', 'is_standard' => false, 'is_optional' => true, 'price' => 'Talep üzerine'], ['icon' => 'cog', 'name' => 'Tandem yük tekerleri (PU)', 'description' => 'Zemin bozukluklarında daha düşük noktasal yük ve rahat geçiş.', 'is_standard' => false, 'is_optional' => true, 'price' => 'Talep üzerine'], ['icon' => 'grip-lines-vertical', 'name' => 'Çatal giriş kılavuzları', 'description' => 'Palet giriş çıkışını hızlandıran metal kılavuz seti.', 'is_standard' => false, 'is_optional' => true, 'price' => 'Talep üzerine'], ['icon' => 'plug', 'name' => 'Standart şarj soketi ve kablo', 'description' => 'Harici şarj soketiyle güvenli bağlantı, bakım gerektirmez.', 'is_standard' => true, 'is_optional' => false, 'price' => null]], JSON_UNESCAPED_UNICODE),
            'certifications' => json_encode([['icon' => 'certificate', 'name' => 'CE', 'year' => '2024', 'authority' => 'EU'], ['icon' => 'award', 'name' => 'EN 16796', 'year' => '2024', 'authority' => 'CEN']], JSON_UNESCAPED_UNICODE),
            'faq_data' => json_encode([['question' => 'Zorlu vardiyalarda batarya ne kadar sürede yeniden şarj olur?', 'answer' => '205Ah Li-Ion paket harici 100A şarj cihazı ile yaklaşık 2 saatten kısa sürede tam doluma ulaşabilir; vardiya arasında fırsat şarjı desteklenir.'], ['question' => 'Dar raf aralarında manevra kabiliyeti sağlayan ölçüler nelerdir?', 'answer' => 'Toplam genişlik 850 mm, dönüş yarıçapı modeline göre 1560–1900 mm’dir; 1000×1200 çapraz paletlerde dar koridor dönüşleri rahatlıkla yapılır.'], ['question' => 'Dönüşte hız düşürme sistemi nasıl çalışır ve güvenliğe katkısı nedir?', 'answer' => 'Elektronik direksiyon açı sensörü timon açısını izler; belirli eşikleri aşınca sürüş kontrolü hızı kademeli düşürerek devrilme riskini azaltır.'], ['question' => 'Operatör platformu uzun mesafede konforu nasıl artırır?', 'answer' => 'Katlanır platform, darbe emici süspansiyonla titreşimi sönümler; uzun hatlarda yorgunluğu azaltırken katlandığında alan kazanımı sağlar.'], ['question' => 'Standart çatal ölçüleri nelerdir ve palet uyumluluğu nasıldır?', 'answer' => 'Standart çatal uzunluğu 1150 mm’dir; en ve kalınlık modele göre 65×170 mm veya 60×185 mm olup EUR/ISO paletlerle yüksek uyumluluk sunar.'], ['question' => 'Rampalı alanlarda kalkış ve duruş güvenliği nasıl sağlanır?', 'answer' => 'Elektromanyetik fren, geri kaçmayı engelleyen sürüş kontrolü ve oransal hidrolik dizginleme ile kontrollü kalkış-duruş yapılır.'], ['question' => 'Bakım planı ve periyodik kontrollerde öne çıkan noktalar nelerdir?', 'answer' => 'Fırçasız AC tahrik bakım ihtiyacını azaltır; görsel kontroller, fren testi ve tekerlek aşınma kontrolü planlı aralıklarla yapılır.'], ['question' => 'Enerji verimliliği değerleri operasyon maliyetine nasıl yansır?', 'answer' => 'EN 16796 ölçümüne göre 1.01 kWh/saat tüketim ve 37 t/kWh verimlilik, kWh başına taşınan tonajı yükselterek elektrik maliyetini düşürür.'], ['question' => 'Soğuk depo geçişlerinde performans düşüşü yaşanır mı?', 'answer' => 'PU teker ve Li-Ion kimya kısa süreli sıcaklık değişimlerinde kararlı çalışır; sürekli soğuk için uygun lastik ve yağ önerilir.'], ['question' => 'Hız parametreleri ve hız limiti ayarları kullanıcı tarafından düzenlenebilir mi?', 'answer' => 'Servis menüsünde yetkiye bağlı profil ayarı bulunur; hız, ivmelenme ve yavaşlama parametreleri güvenlik sınırları içinde optimize edilir.'], ['question' => 'Yedek parça ve servis erişimi nasıl sağlanır?', 'answer' => 'Yetkili servis ağı stoklu sarf parçaları ve uzaktan destek prosedürleriyle kesinti süresini kısaltır.'], ['question' => 'Garanti koşulları nedir ve kimden destek alırım?', 'answer' => 'Makine için 12 ay, Li-Ion batarya için 24 ay garanti sunulur. Satış, servis ve hızlı parça desteği için İXTİF 0216 755 3 555 hattına ulaşabilirsiniz.']], JSON_UNESCAPED_UNICODE),
            'updated_at' => now()
        ]);
        $this->command->info("✅ Detailed güncellendi: RSL161");
    }
}
