<?php

declare(strict_types=1);

namespace Modules\Shop\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ShopCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks temporarily
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Truncate table
        DB::table('shop_categories')->truncate();

        // Enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $now = Carbon::now();

        // Ana kategoriler ve tüm alt kategoriler
        $categories = [
            // 1. AMR
            [
                'category_id' => 186,
                'parent_id' => null,
                'title' => json_encode(['tr' => 'AMR', 'en' => 'AMR']),
                'slug' => json_encode(['tr' => 'amr', 'en' => 'amr']),
                'description' => json_encode(['tr' => 'AMR kategorisi', 'en' => 'AMR category']),
                'level' => 1,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 2. FORKLİFTLER
            [
                'category_id' => 163,
                'parent_id' => null,
                'title' => json_encode(['tr' => 'FORKLİFTLER', 'en' => 'FORKLIFTS']),
                'slug' => json_encode(['tr' => 'forkliftler', 'en' => 'forklifts']),
                'description' => json_encode(['tr' => 'Elektrikli ve dizel forklift çeşitleri', 'en' => 'Electric and diesel forklift varieties']),
                'level' => 1,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 154,
                'parent_id' => 163,
                'title' => json_encode(['tr' => 'ELEKTRİKLİ FORKLİFTLER', 'en' => 'ELECTRIC FORKLIFTS']),
                'slug' => json_encode(['tr' => 'elektrikli-forkliftler', 'en' => 'electric-forklifts']),
                'description' => json_encode(['tr' => 'Akülü forklift modelleri', 'en' => 'Battery-powered forklift models']),
                'level' => 2,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 178,
                'parent_id' => 154,
                'title' => json_encode(['tr' => 'LİTYUM AKÜLÜ FORKLİFTLER', 'en' => 'LITHIUM BATTERY FORKLIFTS']),
                'slug' => json_encode(['tr' => 'lityum-akulu-forkliftler', 'en' => 'lithium-battery-forklifts']),
                'description' => json_encode(['tr' => 'Lityum iyon akülü forklift modelleri', 'en' => 'Lithium-ion battery forklift models']),
                'level' => 3,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 180,
                'parent_id' => 178,
                'title' => json_encode(['tr' => '3 TEKERLİ LİTYUM AKÜLÜ FORKLİFTLER', 'en' => '3-WHEEL LITHIUM BATTERY FORKLIFTS']),
                'slug' => json_encode(['tr' => '3-tekerlekli-lityum-akulu-forkliftler', 'en' => '3-wheel-lithium-battery-forklifts']),
                'description' => json_encode(['tr' => 'Üç tekerlekli lityum akülü forklift modelleri', 'en' => 'Three-wheel lithium battery forklift models']),
                'level' => 4,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 181,
                'parent_id' => 178,
                'title' => json_encode(['tr' => '4 TEKERLİ LİTYUM AKÜLÜ FORKLİFTLER', 'en' => '4-WHEEL LITHIUM BATTERY FORKLIFTS']),
                'slug' => json_encode(['tr' => '4-tekerlekli-lityum-akulu-forkliftler', 'en' => '4-wheel-lithium-battery-forklifts']),
                'description' => json_encode(['tr' => 'Dört tekerlekli lityum akülü forklift modelleri', 'en' => 'Four-wheel lithium battery forklift models']),
                'level' => 4,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 182,
                'parent_id' => 178,
                'title' => json_encode(['tr' => 'YÜKSEK TONAJLI LİTYUM AKÜLÜ FORKLİFTLER', 'en' => 'HIGH TONNAGE LITHIUM BATTERY FORKLIFTS']),
                'slug' => json_encode(['tr' => 'yuksek-tonajli-lityum-akulu-forkliftler', 'en' => 'high-tonnage-lithium-battery-forklifts']),
                'description' => json_encode(['tr' => 'Yüksek taşıma kapasiteli lityum akülü forklift modelleri', 'en' => 'High capacity lithium battery forklift models']),
                'level' => 4,
                'sort_order' => 3,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 179,
                'parent_id' => 154,
                'title' => json_encode(['tr' => 'TRAKSİYONER AKÜLÜ FORKLİFTLER', 'en' => 'TRACTION BATTERY FORKLIFTS']),
                'slug' => json_encode(['tr' => 'traksiyoner-akulu-forkliftler', 'en' => 'traction-battery-forklifts']),
                'description' => json_encode(['tr' => 'Traksiyon akülü forklift modelleri', 'en' => 'Traction battery forklift models']),
                'level' => 3,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 41,
                'parent_id' => 163,
                'title' => json_encode(['tr' => 'DİZEL FORKLİFTLER', 'en' => 'DIESEL FORKLIFTS']),
                'slug' => json_encode(['tr' => 'dizel-forkliftler', 'en' => 'diesel-forklifts']),
                'description' => json_encode(['tr' => 'Dizel motorlu forklift modelleri', 'en' => 'Diesel engine forklift models']),
                'level' => 2,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 3. TRANSPALETLER
            [
                'category_id' => 165,
                'parent_id' => null,
                'title' => json_encode(['tr' => 'TRANSPALETLER', 'en' => 'PALLET TRUCKS']),
                'slug' => json_encode(['tr' => 'transpaletler', 'en' => 'pallet-trucks']),
                'description' => json_encode(['tr' => 'Elektrikli ve manuel transpalet çeşitleri', 'en' => 'Electric and manual pallet truck varieties']),
                'level' => 1,
                'sort_order' => 3,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 44,
                'parent_id' => 165,
                'title' => json_encode(['tr' => 'ELEKTRİKLİ TRANSPALETLER', 'en' => 'ELECTRIC PALLET TRUCKS']),
                'slug' => json_encode(['tr' => 'elektrikli-transpaletler', 'en' => 'electric-pallet-trucks']),
                'description' => json_encode(['tr' => 'Akülü transpalet modelleri', 'en' => 'Electric pallet truck models']),
                'level' => 2,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 166,
                'parent_id' => 165,
                'title' => json_encode(['tr' => 'MANUEL TRANSPALETLER', 'en' => 'MANUAL PALLET TRUCKS']),
                'slug' => json_encode(['tr' => 'manuel-transpaletler', 'en' => 'manual-pallet-trucks']),
                'description' => json_encode(['tr' => 'El ile kullanılan transpalet modelleri', 'en' => 'Manual pallet truck models']),
                'level' => 2,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 4. İSTİF MAKİNELERİ
            [
                'category_id' => 45,
                'parent_id' => null,
                'title' => json_encode(['tr' => 'İSTİF MAKİNELERİ', 'en' => 'STACKERS']),
                'slug' => json_encode(['tr' => 'istif-makineleri', 'en' => 'stackers']),
                'description' => json_encode(['tr' => 'İstif makinesi modelleri', 'en' => 'Stacker models']),
                'level' => 1,
                'sort_order' => 4,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 5. REACH TRUCK
            [
                'category_id' => 183,
                'parent_id' => null,
                'title' => json_encode(['tr' => 'REACH TRUCK', 'en' => 'REACH TRUCK']),
                'slug' => json_encode(['tr' => 'reach-truck', 'en' => 'reach-truck']),
                'description' => json_encode(['tr' => 'Reach truck modelleri', 'en' => 'Reach truck models']),
                'level' => 1,
                'sort_order' => 5,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 6. ORDER PICKER
            [
                'category_id' => 184,
                'parent_id' => null,
                'title' => json_encode(['tr' => 'ORDER PICKER', 'en' => 'ORDER PICKER']),
                'slug' => json_encode(['tr' => 'order-picker', 'en' => 'order-picker']),
                'description' => json_encode(['tr' => 'Order picker modelleri', 'en' => 'Order picker models']),
                'level' => 1,
                'sort_order' => 6,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 7. TOW TRUCK
            [
                'category_id' => 185,
                'parent_id' => null,
                'title' => json_encode(['tr' => 'TOW TRUCK', 'en' => 'TOW TRUCK']),
                'slug' => json_encode(['tr' => 'tow-truck', 'en' => 'tow-truck']),
                'description' => json_encode(['tr' => 'Çekici araç modelleri', 'en' => 'Tow truck models']),
                'level' => 1,
                'sort_order' => 7,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 8. İKİNCİ EL
            [
                'category_id' => 164,
                'parent_id' => null,
                'title' => json_encode(['tr' => 'İKİNCİ (2.) EL', 'en' => 'SECOND HAND']),
                'slug' => json_encode(['tr' => 'ikinci-el', 'en' => 'second-hand']),
                'description' => json_encode(['tr' => 'İkinci el iş makineleri', 'en' => 'Second hand industrial machines']),
                'level' => 1,
                'sort_order' => 8,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 168,
                'parent_id' => 164,
                'title' => json_encode(['tr' => 'TRANSPALET', 'en' => 'PALLET TRUCK']),
                'slug' => json_encode(['tr' => 'transpalet', 'en' => 'pallet-truck']),
                'description' => json_encode(['tr' => 'İkinci el transpaletler', 'en' => 'Second hand pallet trucks']),
                'level' => 2,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 173,
                'parent_id' => 168,
                'title' => json_encode(['tr' => 'MANUEL TRANSPALET', 'en' => 'MANUAL PALLET TRUCK']),
                'slug' => json_encode(['tr' => 'manuel-transpalet', 'en' => 'manual-pallet-truck']),
                'description' => json_encode(['tr' => 'İkinci el manuel transpaletler', 'en' => 'Second hand manual pallet trucks']),
                'level' => 3,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 172,
                'parent_id' => 168,
                'title' => json_encode(['tr' => 'ELEKTRİKLİ TRANSPALET', 'en' => 'ELECTRIC PALLET TRUCK']),
                'slug' => json_encode(['tr' => 'elektrikli-transpalet', 'en' => 'electric-pallet-truck']),
                'description' => json_encode(['tr' => 'İkinci el elektrikli transpaletler', 'en' => 'Second hand electric pallet trucks']),
                'level' => 3,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 169,
                'parent_id' => 164,
                'title' => json_encode(['tr' => 'FORKLİFTLER', 'en' => 'FORKLIFTS']),
                'slug' => json_encode(['tr' => 'forkliftler-ikinci-el', 'en' => 'forklifts-second-hand']),
                'description' => json_encode(['tr' => 'İkinci el forkliftler', 'en' => 'Second hand forklifts']),
                'level' => 2,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 175,
                'parent_id' => 169,
                'title' => json_encode(['tr' => 'DİZEL FORKLİFT', 'en' => 'DIESEL FORKLIFT']),
                'slug' => json_encode(['tr' => 'dizel-forklift', 'en' => 'diesel-forklift']),
                'description' => json_encode(['tr' => 'İkinci el dizel forkliftler', 'en' => 'Second hand diesel forklifts']),
                'level' => 3,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 174,
                'parent_id' => 169,
                'title' => json_encode(['tr' => 'AKÜLÜ FORKLİFT', 'en' => 'BATTERY FORKLIFT']),
                'slug' => json_encode(['tr' => 'akulu-forklift', 'en' => 'battery-forklift']),
                'description' => json_encode(['tr' => 'İkinci el akülü forkliftler', 'en' => 'Second hand battery forklifts']),
                'level' => 3,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 176,
                'parent_id' => 174,
                'title' => json_encode(['tr' => 'LİTYUM AKÜLÜ FORKLİFT', 'en' => 'LITHIUM BATTERY FORKLIFT']),
                'slug' => json_encode(['tr' => 'lityum-akulu-forklift', 'en' => 'lithium-battery-forklift']),
                'description' => json_encode(['tr' => 'İkinci el lityum akülü forkliftler', 'en' => 'Second hand lithium battery forklifts']),
                'level' => 4,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 177,
                'parent_id' => 174,
                'title' => json_encode(['tr' => 'TRAKSİYONER AKÜLÜ FORKLİFT', 'en' => 'TRACTION BATTERY FORKLIFT']),
                'slug' => json_encode(['tr' => 'traksiyoner-akulu-forklift', 'en' => 'traction-battery-forklift']),
                'description' => json_encode(['tr' => 'İkinci el traksiyon akülü forkliftler', 'en' => 'Second hand traction battery forklifts']),
                'level' => 4,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 170,
                'parent_id' => 164,
                'title' => json_encode(['tr' => 'İSTİF MAKİNELERİ', 'en' => 'STACKERS']),
                'slug' => json_encode(['tr' => 'istif-makineleri-ikinci-el', 'en' => 'stackers-second-hand']),
                'description' => json_encode(['tr' => 'İkinci el istif makineleri', 'en' => 'Second hand stackers']),
                'level' => 2,
                'sort_order' => 3,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 171,
                'parent_id' => 164,
                'title' => json_encode(['tr' => 'REACH TRUCK', 'en' => 'REACH TRUCK']),
                'slug' => json_encode(['tr' => 'reach-truck-ikinci-el', 'en' => 'reach-truck-second-hand']),
                'description' => json_encode(['tr' => 'İkinci el reach truck', 'en' => 'Second hand reach truck']),
                'level' => 2,
                'sort_order' => 4,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 9. YEDEK PARÇA - Ana Kategori
            [
                'category_id' => 50,
                'parent_id' => null,
                'title' => json_encode(['tr' => 'YEDEK PARÇA', 'en' => 'SPARE PARTS']),
                'slug' => json_encode(['tr' => 'yedek-parca', 'en' => 'spare-parts']),
                'description' => json_encode(['tr' => 'Forklift ve iş makineleri yedek parçaları', 'en' => 'Forklift and industrial machine spare parts']),
                'level' => 1,
                'sort_order' => 9,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 9.1. Lastik Jant Teker
            [
                'category_id' => 51,
                'parent_id' => 50,
                'title' => json_encode(['tr' => 'Lastik Jant Teker', 'en' => 'Tire Rim Wheel']),
                'slug' => json_encode(['tr' => 'lastik-jant-teker', 'en' => 'tire-rim-wheel']),
                'description' => json_encode(['tr' => 'Forklift lastik, jant ve teker çeşitleri', 'en' => 'Forklift tire, rim and wheel varieties']),
                'level' => 2,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 52,
                'parent_id' => 51,
                'title' => json_encode(['tr' => 'Siyah Dolgu Lastik', 'en' => 'Black Solid Tire']),
                'slug' => json_encode(['tr' => 'siyah-dolgu-lastik', 'en' => 'black-solid-tire']),
                'description' => json_encode(['tr' => 'Siyah dolgu lastik modelleri', 'en' => 'Black solid tire models']),
                'level' => 3,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 53,
                'parent_id' => 51,
                'title' => json_encode(['tr' => 'Beyaz Dolgu Lastik', 'en' => 'White Solid Tire']),
                'slug' => json_encode(['tr' => 'beyaz-dolgu-lastik', 'en' => 'white-solid-tire']),
                'description' => json_encode(['tr' => 'Beyaz dolgu lastik modelleri', 'en' => 'White solid tire models']),
                'level' => 3,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 54,
                'parent_id' => 51,
                'title' => json_encode(['tr' => 'Havalı Lastik', 'en' => 'Pneumatic Tire']),
                'slug' => json_encode(['tr' => 'havali-lastik', 'en' => 'pneumatic-tire']),
                'description' => json_encode(['tr' => 'Havalı lastik modelleri', 'en' => 'Pneumatic tire models']),
                'level' => 3,
                'sort_order' => 3,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 55,
                'parent_id' => 51,
                'title' => json_encode(['tr' => 'İç Lastik Şambrel', 'en' => 'Inner Tube Flap']),
                'slug' => json_encode(['tr' => 'ic-lastik-sambrel', 'en' => 'inner-tube-flap']),
                'description' => json_encode(['tr' => 'İç lastik ve şambrel', 'en' => 'Inner tube and flap']),
                'level' => 3,
                'sort_order' => 4,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 56,
                'parent_id' => 51,
                'title' => json_encode(['tr' => 'Jant - Segman', 'en' => 'Rim - Segment']),
                'slug' => json_encode(['tr' => 'jant-segman', 'en' => 'rim-segment']),
                'description' => json_encode(['tr' => 'Jant ve segman parçaları', 'en' => 'Rim and segment parts']),
                'level' => 3,
                'sort_order' => 5,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 57,
                'parent_id' => 51,
                'title' => json_encode(['tr' => 'Denge Tekeri', 'en' => 'Balance Wheel']),
                'slug' => json_encode(['tr' => 'denge-tekeri', 'en' => 'balance-wheel']),
                'description' => json_encode(['tr' => 'Denge tekerleri', 'en' => 'Balance wheels']),
                'level' => 3,
                'sort_order' => 6,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 58,
                'parent_id' => 51,
                'title' => json_encode(['tr' => 'Çatal Tekeri', 'en' => 'Fork Wheel']),
                'slug' => json_encode(['tr' => 'catal-tekeri', 'en' => 'fork-wheel']),
                'description' => json_encode(['tr' => 'Çatal tekerleri', 'en' => 'Fork wheels']),
                'level' => 3,
                'sort_order' => 7,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 59,
                'parent_id' => 51,
                'title' => json_encode(['tr' => 'Yürüyüş Tekeri', 'en' => 'Drive Wheel']),
                'slug' => json_encode(['tr' => 'yuruyus-tekeri', 'en' => 'drive-wheel']),
                'description' => json_encode(['tr' => 'Yürüyüş tekerleri', 'en' => 'Drive wheels']),
                'level' => 3,
                'sort_order' => 8,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 60,
                'parent_id' => 51,
                'title' => json_encode(['tr' => 'Platform Tekeri', 'en' => 'Platform Wheel']),
                'slug' => json_encode(['tr' => 'platform-tekeri', 'en' => 'platform-wheel']),
                'description' => json_encode(['tr' => 'Platform tekerleri', 'en' => 'Platform wheels']),
                'level' => 3,
                'sort_order' => 9,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 61,
                'parent_id' => 51,
                'title' => json_encode(['tr' => 'Transpalet Tekeri', 'en' => 'Pallet Truck Wheel']),
                'slug' => json_encode(['tr' => 'transpalet-tekeri', 'en' => 'pallet-truck-wheel']),
                'description' => json_encode(['tr' => 'Transpalet tekerleri', 'en' => 'Pallet truck wheels']),
                'level' => 3,
                'sort_order' => 10,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 62,
                'parent_id' => 51,
                'title' => json_encode(['tr' => 'Bijon', 'en' => 'Wheel Bolt']),
                'slug' => json_encode(['tr' => 'bijon', 'en' => 'wheel-bolt']),
                'description' => json_encode(['tr' => 'Tekerlek bijonları', 'en' => 'Wheel bolts']),
                'level' => 3,
                'sort_order' => 11,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 9.2. Motor Grubu
            [
                'category_id' => 63,
                'parent_id' => 50,
                'title' => json_encode(['tr' => 'Motor Grubu', 'en' => 'Engine Group']),
                'slug' => json_encode(['tr' => 'motor-grubu', 'en' => 'engine-group']),
                'description' => json_encode(['tr' => 'Motor ve motor parçaları', 'en' => 'Engine and engine parts']),
                'level' => 2,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 76,
                'parent_id' => 63,
                'title' => json_encode(['tr' => 'Devirdaim', 'en' => 'Water Pump']),
                'slug' => json_encode(['tr' => 'devirdaim', 'en' => 'water-pump']),
                'description' => json_encode(['tr' => 'Motor devirdaim pompaları', 'en' => 'Engine water pumps']),
                'level' => 3,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 77,
                'parent_id' => 63,
                'title' => json_encode(['tr' => 'Yakıt Otomatiği', 'en' => 'Fuel Automatic']),
                'slug' => json_encode(['tr' => 'yakit-otomatigi', 'en' => 'fuel-automatic']),
                'description' => json_encode(['tr' => 'Yakıt otomatik sistemleri', 'en' => 'Fuel automatic systems']),
                'level' => 3,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 78,
                'parent_id' => 63,
                'title' => json_encode(['tr' => 'Pervane', 'en' => 'Fan Blade']),
                'slug' => json_encode(['tr' => 'pervane', 'en' => 'fan-blade']),
                'description' => json_encode(['tr' => 'Motor pervane', 'en' => 'Engine fan blade']),
                'level' => 3,
                'sort_order' => 3,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 79,
                'parent_id' => 63,
                'title' => json_encode(['tr' => 'Şamandıra', 'en' => 'Float']),
                'slug' => json_encode(['tr' => 'samandira', 'en' => 'float']),
                'description' => json_encode(['tr' => 'Yakıt şamandırası', 'en' => 'Fuel float']),
                'level' => 3,
                'sort_order' => 4,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 80,
                'parent_id' => 63,
                'title' => json_encode(['tr' => 'Silindir Kapak Contası', 'en' => 'Cylinder Head Gasket']),
                'slug' => json_encode(['tr' => 'silindir-kapak-contasi', 'en' => 'cylinder-head-gasket']),
                'description' => json_encode(['tr' => 'Silindir kapak contaları', 'en' => 'Cylinder head gaskets']),
                'level' => 3,
                'sort_order' => 5,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 81,
                'parent_id' => 63,
                'title' => json_encode(['tr' => 'Piston', 'en' => 'Piston']),
                'slug' => json_encode(['tr' => 'piston', 'en' => 'piston']),
                'description' => json_encode(['tr' => 'Motor pistonları', 'en' => 'Engine pistons']),
                'level' => 3,
                'sort_order' => 6,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 82,
                'parent_id' => 63,
                'title' => json_encode(['tr' => 'Piston Kolu', 'en' => 'Connecting Rod']),
                'slug' => json_encode(['tr' => 'piston-kolu', 'en' => 'connecting-rod']),
                'description' => json_encode(['tr' => 'Piston kolları', 'en' => 'Connecting rods']),
                'level' => 3,
                'sort_order' => 7,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 83,
                'parent_id' => 63,
                'title' => json_encode(['tr' => 'Kayış', 'en' => 'Belt']),
                'slug' => json_encode(['tr' => 'kayis', 'en' => 'belt']),
                'description' => json_encode(['tr' => 'Motor kayışları', 'en' => 'Engine belts']),
                'level' => 3,
                'sort_order' => 8,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 84,
                'parent_id' => 63,
                'title' => json_encode(['tr' => 'Volant Dişlisi', 'en' => 'Flywheel Gear']),
                'slug' => json_encode(['tr' => 'volant-dislisi', 'en' => 'flywheel-gear']),
                'description' => json_encode(['tr' => 'Volant dişlileri', 'en' => 'Flywheel gears']),
                'level' => 3,
                'sort_order' => 9,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 85,
                'parent_id' => 63,
                'title' => json_encode(['tr' => 'Motor Yatağı', 'en' => 'Engine Bearing']),
                'slug' => json_encode(['tr' => 'motor-yatagi', 'en' => 'engine-bearing']),
                'description' => json_encode(['tr' => 'Motor yatakları', 'en' => 'Engine bearings']),
                'level' => 3,
                'sort_order' => 10,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 9.3. Çatal / Ataşman
            [
                'category_id' => 64,
                'parent_id' => 50,
                'title' => json_encode(['tr' => 'Çatal / Ataşman', 'en' => 'Fork / Attachment']),
                'slug' => json_encode(['tr' => 'catal-atasman', 'en' => 'fork-attachment']),
                'description' => json_encode(['tr' => 'Forklift çatalları ve ataşmanları', 'en' => 'Forklift forks and attachments']),
                'level' => 2,
                'sort_order' => 3,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 86,
                'parent_id' => 64,
                'title' => json_encode(['tr' => 'Çatal', 'en' => 'Fork']),
                'slug' => json_encode(['tr' => 'catal', 'en' => 'fork']),
                'description' => json_encode(['tr' => 'Forklift çatalları', 'en' => 'Forklift forks']),
                'level' => 3,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 87,
                'parent_id' => 64,
                'title' => json_encode(['tr' => 'Çatal Kılıf', 'en' => 'Fork Cover']),
                'slug' => json_encode(['tr' => 'catal-kilif', 'en' => 'fork-cover']),
                'description' => json_encode(['tr' => 'Çatal kılıfları', 'en' => 'Fork covers']),
                'level' => 3,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 9.4. Şanzıman Parçaları
            [
                'category_id' => 65,
                'parent_id' => 50,
                'title' => json_encode(['tr' => 'Şanzıman Parçaları', 'en' => 'Transmission Parts']),
                'slug' => json_encode(['tr' => 'sanziman-parcalari', 'en' => 'transmission-parts']),
                'description' => json_encode(['tr' => 'Şanzıman yedek parçaları', 'en' => 'Transmission spare parts']),
                'level' => 2,
                'sort_order' => 4,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 88,
                'parent_id' => 65,
                'title' => json_encode(['tr' => 'Segman Takımı', 'en' => 'Ring Set']),
                'slug' => json_encode(['tr' => 'segman-takimi', 'en' => 'ring-set']),
                'description' => json_encode(['tr' => 'Şanzıman segman takımları', 'en' => 'Transmission ring sets']),
                'level' => 3,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 89,
                'parent_id' => 65,
                'title' => json_encode(['tr' => 'Çelik Plate', 'en' => 'Steel Plate']),
                'slug' => json_encode(['tr' => 'celik-plate', 'en' => 'steel-plate']),
                'description' => json_encode(['tr' => 'Şanzıman çelik plakası', 'en' => 'Transmission steel plate']),
                'level' => 3,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 90,
                'parent_id' => 65,
                'title' => json_encode(['tr' => 'Balata', 'en' => 'Friction Disc']),
                'slug' => json_encode(['tr' => 'balata', 'en' => 'friction-disc']),
                'description' => json_encode(['tr' => 'Şanzıman balatası', 'en' => 'Transmission friction disc']),
                'level' => 3,
                'sort_order' => 3,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 91,
                'parent_id' => 65,
                'title' => json_encode(['tr' => 'Tork Converter', 'en' => 'Torque Converter']),
                'slug' => json_encode(['tr' => 'tork-converter', 'en' => 'torque-converter']),
                'description' => json_encode(['tr' => 'Tork konvertör', 'en' => 'Torque converter']),
                'level' => 3,
                'sort_order' => 4,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 92,
                'parent_id' => 65,
                'title' => json_encode(['tr' => 'Tork Sacı', 'en' => 'Torque Plate']),
                'slug' => json_encode(['tr' => 'tork-saci', 'en' => 'torque-plate']),
                'description' => json_encode(['tr' => 'Tork sacı', 'en' => 'Torque plate']),
                'level' => 3,
                'sort_order' => 5,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 93,
                'parent_id' => 65,
                'title' => json_encode(['tr' => 'Şanzıman Şaftı', 'en' => 'Transmission Shaft']),
                'slug' => json_encode(['tr' => 'sanziman-safti', 'en' => 'transmission-shaft']),
                'description' => json_encode(['tr' => 'Şanzıman şaftı', 'en' => 'Transmission shaft']),
                'level' => 3,
                'sort_order' => 6,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 94,
                'parent_id' => 65,
                'title' => json_encode(['tr' => 'Şanzıman Şaft Dişlisi', 'en' => 'Transmission Shaft Gear']),
                'slug' => json_encode(['tr' => 'sanziman-saft-dislisi', 'en' => 'transmission-shaft-gear']),
                'description' => json_encode(['tr' => 'Şanzıman şaft dişlisi', 'en' => 'Transmission shaft gear']),
                'level' => 3,
                'sort_order' => 7,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 9.5. Keçeler
            [
                'category_id' => 66,
                'parent_id' => 50,
                'title' => json_encode(['tr' => 'Keçeler', 'en' => 'Seals']),
                'slug' => json_encode(['tr' => 'keceler', 'en' => 'seals']),
                'description' => json_encode(['tr' => 'Forklift keçeleri', 'en' => 'Forklift seals']),
                'level' => 2,
                'sort_order' => 5,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 9.6. Direksiyon Grubu
            [
                'category_id' => 67,
                'parent_id' => 50,
                'title' => json_encode(['tr' => 'Direksiyon Grubu', 'en' => 'Steering Group']),
                'slug' => json_encode(['tr' => 'direksiyon-grubu', 'en' => 'steering-group']),
                'description' => json_encode(['tr' => 'Direksiyon parçaları', 'en' => 'Steering parts']),
                'level' => 2,
                'sort_order' => 6,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 95,
                'parent_id' => 67,
                'title' => json_encode(['tr' => 'Direksiyon Simidi', 'en' => 'Steering Wheel']),
                'slug' => json_encode(['tr' => 'direksiyon-simidi', 'en' => 'steering-wheel']),
                'description' => json_encode(['tr' => 'Direksiyon simitleri', 'en' => 'Steering wheels']),
                'level' => 3,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 96,
                'parent_id' => 67,
                'title' => json_encode(['tr' => 'Direksiyon Mafsalı', 'en' => 'Steering Joint']),
                'slug' => json_encode(['tr' => 'direksiyon-mafsali', 'en' => 'steering-joint']),
                'description' => json_encode(['tr' => 'Direksiyon mafsalları', 'en' => 'Steering joints']),
                'level' => 3,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 97,
                'parent_id' => 67,
                'title' => json_encode(['tr' => 'Direksiyon Mili', 'en' => 'Steering Shaft']),
                'slug' => json_encode(['tr' => 'direksiyon-mili', 'en' => 'steering-shaft']),
                'description' => json_encode(['tr' => 'Direksiyon milleri', 'en' => 'Steering shafts']),
                'level' => 3,
                'sort_order' => 3,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 98,
                'parent_id' => 67,
                'title' => json_encode(['tr' => 'Direksiyon Danfozu', 'en' => 'Steering Dampener']),
                'slug' => json_encode(['tr' => 'direksiyon-danfozu', 'en' => 'steering-dampener']),
                'description' => json_encode(['tr' => 'Direksiyon danfozları', 'en' => 'Steering dampeners']),
                'level' => 3,
                'sort_order' => 4,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 9.7. Asansör Grubu
            [
                'category_id' => 68,
                'parent_id' => 50,
                'title' => json_encode(['tr' => 'Asansör Grubu', 'en' => 'Mast Assembly']),
                'slug' => json_encode(['tr' => 'asansor-grubu', 'en' => 'mast-assembly']),
                'description' => json_encode(['tr' => 'Asansör parçaları', 'en' => 'Mast assembly parts']),
                'level' => 2,
                'sort_order' => 7,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 99,
                'parent_id' => 68,
                'title' => json_encode(['tr' => 'Kızak Takımı', 'en' => 'Slide Set']),
                'slug' => json_encode(['tr' => 'kizak-takimi', 'en' => 'slide-set']),
                'description' => json_encode(['tr' => 'Kızak takımları', 'en' => 'Slide sets']),
                'level' => 3,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 100,
                'parent_id' => 68,
                'title' => json_encode(['tr' => 'Side Shift Kızak', 'en' => 'Side Shift Slide']),
                'slug' => json_encode(['tr' => 'side-shift-kizak', 'en' => 'side-shift-slide']),
                'description' => json_encode(['tr' => 'Side shift kızakları', 'en' => 'Side shift slides']),
                'level' => 3,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 101,
                'parent_id' => 68,
                'title' => json_encode(['tr' => 'Asansör Ayar Teflonu', 'en' => 'Mast Adjustment Teflon']),
                'slug' => json_encode(['tr' => 'asansor-ayar-teflonu', 'en' => 'mast-adjustment-teflon']),
                'description' => json_encode(['tr' => 'Asansör ayar teflonları', 'en' => 'Mast adjustment teflons']),
                'level' => 3,
                'sort_order' => 3,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 102,
                'parent_id' => 68,
                'title' => json_encode(['tr' => 'Asansör Kep Burcu', 'en' => 'Mast Bushing']),
                'slug' => json_encode(['tr' => 'asansor-kep-burcu', 'en' => 'mast-bushing']),
                'description' => json_encode(['tr' => 'Asansör kep burcları', 'en' => 'Mast bushings']),
                'level' => 3,
                'sort_order' => 4,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 103,
                'parent_id' => 68,
                'title' => json_encode(['tr' => 'Makara', 'en' => 'Pulley']),
                'slug' => json_encode(['tr' => 'makara', 'en' => 'pulley']),
                'description' => json_encode(['tr' => 'Asansör makaraları', 'en' => 'Mast pulleys']),
                'level' => 3,
                'sort_order' => 5,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 104,
                'parent_id' => 68,
                'title' => json_encode(['tr' => 'Tilt Silindir Mili', 'en' => 'Tilt Cylinder Rod']),
                'slug' => json_encode(['tr' => 'tilt-silindir-mili', 'en' => 'tilt-cylinder-rod']),
                'description' => json_encode(['tr' => 'Tilt silindir milleri', 'en' => 'Tilt cylinder rods']),
                'level' => 3,
                'sort_order' => 6,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 105,
                'parent_id' => 68,
                'title' => json_encode(['tr' => 'Tilt Pistonu', 'en' => 'Tilt Piston']),
                'slug' => json_encode(['tr' => 'tilt-pistonu', 'en' => 'tilt-piston']),
                'description' => json_encode(['tr' => 'Tilt pistonları', 'en' => 'Tilt pistons']),
                'level' => 3,
                'sort_order' => 7,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 106,
                'parent_id' => 68,
                'title' => json_encode(['tr' => 'Side Shift Pistonu', 'en' => 'Side Shift Piston']),
                'slug' => json_encode(['tr' => 'side-shift-pistonu', 'en' => 'side-shift-piston']),
                'description' => json_encode(['tr' => 'Side shift pistonları', 'en' => 'Side shift pistons']),
                'level' => 3,
                'sort_order' => 8,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 107,
                'parent_id' => 68,
                'title' => json_encode(['tr' => 'Zincir', 'en' => 'Chain']),
                'slug' => json_encode(['tr' => 'zincir', 'en' => 'chain']),
                'description' => json_encode(['tr' => 'Asansör zincirleri', 'en' => 'Mast chains']),
                'level' => 3,
                'sort_order' => 9,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 9.8. Rulman Grubu
            [
                'category_id' => 69,
                'parent_id' => 50,
                'title' => json_encode(['tr' => 'Rulman Grubu', 'en' => 'Bearing Group']),
                'slug' => json_encode(['tr' => 'rulman-grubu', 'en' => 'bearing-group']),
                'description' => json_encode(['tr' => 'Rulman çeşitleri', 'en' => 'Bearing varieties']),
                'level' => 2,
                'sort_order' => 8,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 108,
                'parent_id' => 69,
                'title' => json_encode(['tr' => 'Rulman Ayna', 'en' => 'Bearing Mirror']),
                'slug' => json_encode(['tr' => 'rulman-ayna', 'en' => 'bearing-mirror']),
                'description' => json_encode(['tr' => 'Rulman aynaları', 'en' => 'Bearing mirrors']),
                'level' => 3,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 109,
                'parent_id' => 69,
                'title' => json_encode(['tr' => 'Rulman Asansör', 'en' => 'Mast Bearing']),
                'slug' => json_encode(['tr' => 'rulman-asansor', 'en' => 'mast-bearing']),
                'description' => json_encode(['tr' => 'Asansör rulmanları', 'en' => 'Mast bearings']),
                'level' => 3,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 110,
                'parent_id' => 69,
                'title' => json_encode(['tr' => 'Porya Rulman', 'en' => 'Thrust Bearing']),
                'slug' => json_encode(['tr' => 'porya-rulman', 'en' => 'thrust-bearing']),
                'description' => json_encode(['tr' => 'Porya rulmanları', 'en' => 'Thrust bearings']),
                'level' => 3,
                'sort_order' => 3,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 111,
                'parent_id' => 69,
                'title' => json_encode(['tr' => 'Kilit Bilya', 'en' => 'Lock Ball']),
                'slug' => json_encode(['tr' => 'kilit-bilya', 'en' => 'lock-ball']),
                'description' => json_encode(['tr' => 'Kilit bilyalar', 'en' => 'Lock balls']),
                'level' => 3,
                'sort_order' => 4,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 112,
                'parent_id' => 69,
                'title' => json_encode(['tr' => 'Rulman Zarfı', 'en' => 'Bearing Housing']),
                'slug' => json_encode(['tr' => 'rulman-zarfi', 'en' => 'bearing-housing']),
                'description' => json_encode(['tr' => 'Rulman zarfları', 'en' => 'Bearing housings']),
                'level' => 3,
                'sort_order' => 5,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 113,
                'parent_id' => 69,
                'title' => json_encode(['tr' => 'Rulman Taşıyıcı', 'en' => 'Bearing Carrier']),
                'slug' => json_encode(['tr' => 'rulman-tasiyici', 'en' => 'bearing-carrier']),
                'description' => json_encode(['tr' => 'Rulman taşıyıcıları', 'en' => 'Bearing carriers']),
                'level' => 3,
                'sort_order' => 6,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 115,
                'parent_id' => 69,
                'title' => json_encode(['tr' => 'Denge Rulmanı', 'en' => 'Balance Bearing']),
                'slug' => json_encode(['tr' => 'denge-rulmani', 'en' => 'balance-bearing']),
                'description' => json_encode(['tr' => 'Denge rulmanları', 'en' => 'Balance bearings']),
                'level' => 3,
                'sort_order' => 7,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 116,
                'parent_id' => 69,
                'title' => json_encode(['tr' => 'İğneli Rulman', 'en' => 'Needle Bearing']),
                'slug' => json_encode(['tr' => 'igneli-rulman', 'en' => 'needle-bearing']),
                'description' => json_encode(['tr' => 'İğneli rulmanlar', 'en' => 'Needle bearings']),
                'level' => 3,
                'sort_order' => 8,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 9.9. Elektrik / Elektronik / Akü
            [
                'category_id' => 70,
                'parent_id' => 50,
                'title' => json_encode(['tr' => 'Elektrik / Elektronik / Akü', 'en' => 'Electrical / Electronics / Battery']),
                'slug' => json_encode(['tr' => 'elektrik-elektronik-aku', 'en' => 'electrical-electronics-battery']),
                'description' => json_encode(['tr' => 'Elektrik ve elektronik parçalar', 'en' => 'Electrical and electronic parts']),
                'level' => 2,
                'sort_order' => 9,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 117,
                'parent_id' => 70,
                'title' => json_encode(['tr' => 'Akü Soketi', 'en' => 'Battery Socket']),
                'slug' => json_encode(['tr' => 'aku-soketi', 'en' => 'battery-socket']),
                'description' => json_encode(['tr' => 'Akü soketleri', 'en' => 'Battery sockets']),
                'level' => 3,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 118,
                'parent_id' => 70,
                'title' => json_encode(['tr' => 'Ampul', 'en' => 'Bulb']),
                'slug' => json_encode(['tr' => 'ampul', 'en' => 'bulb']),
                'description' => json_encode(['tr' => 'Aydınlatma ampulleri', 'en' => 'Light bulbs']),
                'level' => 3,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 119,
                'parent_id' => 70,
                'title' => json_encode(['tr' => 'Kontaktör', 'en' => 'Contactor']),
                'slug' => json_encode(['tr' => 'kontraktor', 'en' => 'contactor']),
                'description' => json_encode(['tr' => 'Elektrik kontaktörleri', 'en' => 'Electric contactors']),
                'level' => 3,
                'sort_order' => 3,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 120,
                'parent_id' => 70,
                'title' => json_encode(['tr' => 'Konvektör', 'en' => 'Converter']),
                'slug' => json_encode(['tr' => 'konvektor', 'en' => 'converter']),
                'description' => json_encode(['tr' => 'Elektrik konvertörleri', 'en' => 'Electric converters']),
                'level' => 3,
                'sort_order' => 4,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 121,
                'parent_id' => 70,
                'title' => json_encode(['tr' => 'Far', 'en' => 'Headlight']),
                'slug' => json_encode(['tr' => 'far', 'en' => 'headlight']),
                'description' => json_encode(['tr' => 'Forklift farları', 'en' => 'Forklift headlights']),
                'level' => 3,
                'sort_order' => 5,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 122,
                'parent_id' => 70,
                'title' => json_encode(['tr' => 'Termostat', 'en' => 'Thermostat']),
                'slug' => json_encode(['tr' => 'termostat', 'en' => 'thermostat']),
                'description' => json_encode(['tr' => 'Motor termostatları', 'en' => 'Engine thermostats']),
                'level' => 3,
                'sort_order' => 6,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 123,
                'parent_id' => 70,
                'title' => json_encode(['tr' => 'Korna', 'en' => 'Horn']),
                'slug' => json_encode(['tr' => 'korna', 'en' => 'horn']),
                'description' => json_encode(['tr' => 'Forklift kornaları', 'en' => 'Forklift horns']),
                'level' => 3,
                'sort_order' => 7,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 124,
                'parent_id' => 70,
                'title' => json_encode(['tr' => 'Fan', 'en' => 'Fan']),
                'slug' => json_encode(['tr' => 'fan', 'en' => 'fan']),
                'description' => json_encode(['tr' => 'Soğutma fanları', 'en' => 'Cooling fans']),
                'level' => 3,
                'sort_order' => 8,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 125,
                'parent_id' => 70,
                'title' => json_encode(['tr' => 'Vites - Sinyal Kolu', 'en' => 'Gear - Signal Lever']),
                'slug' => json_encode(['tr' => 'vites-sinyal-kolu', 'en' => 'gear-signal-lever']),
                'description' => json_encode(['tr' => 'Vites ve sinyal kolları', 'en' => 'Gear and signal levers']),
                'level' => 3,
                'sort_order' => 9,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 9.10. Forklift Dingil Parçaları
            [
                'category_id' => 71,
                'parent_id' => 50,
                'title' => json_encode(['tr' => 'Forklift Dingil Parçaları', 'en' => 'Forklift Axle Parts']),
                'slug' => json_encode(['tr' => 'forklift-dingil-parcalari', 'en' => 'forklift-axle-parts']),
                'description' => json_encode(['tr' => 'Dingil yedek parçaları', 'en' => 'Axle spare parts']),
                'level' => 2,
                'sort_order' => 10,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 126,
                'parent_id' => 71,
                'title' => json_encode(['tr' => 'Link Pimi', 'en' => 'Link Pin']),
                'slug' => json_encode(['tr' => 'link-pimi', 'en' => 'link-pin']),
                'description' => json_encode(['tr' => 'Dingil link pimleri', 'en' => 'Axle link pins']),
                'level' => 3,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 127,
                'parent_id' => 71,
                'title' => json_encode(['tr' => 'Link', 'en' => 'Link']),
                'slug' => json_encode(['tr' => 'link', 'en' => 'link']),
                'description' => json_encode(['tr' => 'Dingil linkleri', 'en' => 'Axle links']),
                'level' => 3,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 128,
                'parent_id' => 71,
                'title' => json_encode(['tr' => 'Akson', 'en' => 'Axle Shaft']),
                'slug' => json_encode(['tr' => 'akson', 'en' => 'axle-shaft']),
                'description' => json_encode(['tr' => 'Dingil aksonları', 'en' => 'Axle shafts']),
                'level' => 3,
                'sort_order' => 3,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 129,
                'parent_id' => 71,
                'title' => json_encode(['tr' => 'Akson Kapağı', 'en' => 'Axle Cover']),
                'slug' => json_encode(['tr' => 'akson-kapagi', 'en' => 'axle-cover']),
                'description' => json_encode(['tr' => 'Akson kapakları', 'en' => 'Axle covers']),
                'level' => 3,
                'sort_order' => 4,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 130,
                'parent_id' => 71,
                'title' => json_encode(['tr' => 'Yönlü Plaka', 'en' => 'Directional Plate']),
                'slug' => json_encode(['tr' => 'yonlu-plaka', 'en' => 'directional-plate']),
                'description' => json_encode(['tr' => 'Yönlendirme plakaları', 'en' => 'Directional plates']),
                'level' => 3,
                'sort_order' => 5,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 131,
                'parent_id' => 71,
                'title' => json_encode(['tr' => 'Dingil Askı Burcu', 'en' => 'Axle Mounting Bushing']),
                'slug' => json_encode(['tr' => 'dingil-aski-burcu', 'en' => 'axle-mounting-bushing']),
                'description' => json_encode(['tr' => 'Dingil askı burcları', 'en' => 'Axle mounting bushings']),
                'level' => 3,
                'sort_order' => 6,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 132,
                'parent_id' => 71,
                'title' => json_encode(['tr' => 'Perno Mili', 'en' => 'King Pin']),
                'slug' => json_encode(['tr' => 'perno-mili', 'en' => 'king-pin']),
                'description' => json_encode(['tr' => 'Perno milleri', 'en' => 'King pins']),
                'level' => 3,
                'sort_order' => 7,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 133,
                'parent_id' => 71,
                'title' => json_encode(['tr' => 'Porya', 'en' => 'Thrust Washer']),
                'slug' => json_encode(['tr' => 'porya', 'en' => 'thrust-washer']),
                'description' => json_encode(['tr' => 'Dingil poryaları', 'en' => 'Axle thrust washers']),
                'level' => 3,
                'sort_order' => 8,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 134,
                'parent_id' => 71,
                'title' => json_encode(['tr' => 'Rot Başı', 'en' => 'Tie Rod End']),
                'slug' => json_encode(['tr' => 'rot-basi', 'en' => 'tie-rod-end']),
                'description' => json_encode(['tr' => 'Rot başları', 'en' => 'Tie rod ends']),
                'level' => 3,
                'sort_order' => 9,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 9.11. Forklift Aksesuarları
            [
                'category_id' => 72,
                'parent_id' => 50,
                'title' => json_encode(['tr' => 'Forklift Aksesuarları', 'en' => 'Forklift Accessories']),
                'slug' => json_encode(['tr' => 'forklift-aksesuarlari', 'en' => 'forklift-accessories']),
                'description' => json_encode(['tr' => 'Forklift aksesuarları', 'en' => 'Forklift accessories']),
                'level' => 2,
                'sort_order' => 11,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 135,
                'parent_id' => 72,
                'title' => json_encode(['tr' => 'Bakalit', 'en' => 'Bakelite']),
                'slug' => json_encode(['tr' => 'bakalit', 'en' => 'bakelite']),
                'description' => json_encode(['tr' => 'Bakalit parçalar', 'en' => 'Bakelite parts']),
                'level' => 3,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 136,
                'parent_id' => 72,
                'title' => json_encode(['tr' => 'Kabin', 'en' => 'Cabin']),
                'slug' => json_encode(['tr' => 'kabin', 'en' => 'cabin']),
                'description' => json_encode(['tr' => 'Forklift kabinleri', 'en' => 'Forklift cabins']),
                'level' => 3,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 137,
                'parent_id' => 72,
                'title' => json_encode(['tr' => 'Amortisör', 'en' => 'Shock Absorber']),
                'slug' => json_encode(['tr' => 'amortisor', 'en' => 'shock-absorber']),
                'description' => json_encode(['tr' => 'Amortisörler', 'en' => 'Shock absorbers']),
                'level' => 3,
                'sort_order' => 3,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 138,
                'parent_id' => 72,
                'title' => json_encode(['tr' => 'Gösterge Paneli', 'en' => 'Instrument Panel']),
                'slug' => json_encode(['tr' => 'gosterge-paneli', 'en' => 'instrument-panel']),
                'description' => json_encode(['tr' => 'Gösterge panelleri', 'en' => 'Instrument panels']),
                'level' => 3,
                'sort_order' => 4,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 9.12. Pompalar
            [
                'category_id' => 73,
                'parent_id' => 50,
                'title' => json_encode(['tr' => 'Pompalar', 'en' => 'Pumps']),
                'slug' => json_encode(['tr' => 'pompalar', 'en' => 'pumps']),
                'description' => json_encode(['tr' => 'Pompa çeşitleri', 'en' => 'Pump varieties']),
                'level' => 2,
                'sort_order' => 12,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 139,
                'parent_id' => 73,
                'title' => json_encode(['tr' => 'Yağ Pompası', 'en' => 'Oil Pump']),
                'slug' => json_encode(['tr' => 'yag-pompasi', 'en' => 'oil-pump']),
                'description' => json_encode(['tr' => 'Yağ pompaları', 'en' => 'Oil pumps']),
                'level' => 3,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 140,
                'parent_id' => 73,
                'title' => json_encode(['tr' => 'Hidrolik Pompa', 'en' => 'Hydraulic Pump']),
                'slug' => json_encode(['tr' => 'hidrolik-pompa', 'en' => 'hydraulic-pump']),
                'description' => json_encode(['tr' => 'Hidrolik pompalar', 'en' => 'Hydraulic pumps']),
                'level' => 3,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 141,
                'parent_id' => 73,
                'title' => json_encode(['tr' => 'Şanzıman Pompası', 'en' => 'Transmission Pump']),
                'slug' => json_encode(['tr' => 'sanziman-pompasi', 'en' => 'transmission-pump']),
                'description' => json_encode(['tr' => 'Şanzıman pompaları', 'en' => 'Transmission pumps']),
                'level' => 3,
                'sort_order' => 3,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 142,
                'parent_id' => 73,
                'title' => json_encode(['tr' => 'Yakıt Pompası', 'en' => 'Fuel Pump']),
                'slug' => json_encode(['tr' => 'yakit-pompasi', 'en' => 'fuel-pump']),
                'description' => json_encode(['tr' => 'Yakıt pompaları', 'en' => 'Fuel pumps']),
                'level' => 3,
                'sort_order' => 4,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 9.13. Fren Grubu
            [
                'category_id' => 74,
                'parent_id' => 50,
                'title' => json_encode(['tr' => 'Fren Grubu', 'en' => 'Brake Group']),
                'slug' => json_encode(['tr' => 'fren-grubu', 'en' => 'brake-group']),
                'description' => json_encode(['tr' => 'Fren sistemi parçaları', 'en' => 'Brake system parts']),
                'level' => 2,
                'sort_order' => 13,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 143,
                'parent_id' => 74,
                'title' => json_encode(['tr' => 'Fren Ana Merkezi', 'en' => 'Master Cylinder']),
                'slug' => json_encode(['tr' => 'fren-ana-merkezi', 'en' => 'master-cylinder']),
                'description' => json_encode(['tr' => 'Fren ana merkezleri', 'en' => 'Master cylinders']),
                'level' => 3,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 144,
                'parent_id' => 74,
                'title' => json_encode(['tr' => 'Fren Balatası', 'en' => 'Brake Pad']),
                'slug' => json_encode(['tr' => 'fren-balatasi', 'en' => 'brake-pad']),
                'description' => json_encode(['tr' => 'Fren balataları', 'en' => 'Brake pads']),
                'level' => 3,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 145,
                'parent_id' => 74,
                'title' => json_encode(['tr' => 'Fren Tekerlek Merkezi', 'en' => 'Wheel Cylinder']),
                'slug' => json_encode(['tr' => 'fren-tekerlek-merkezi', 'en' => 'wheel-cylinder']),
                'description' => json_encode(['tr' => 'Fren tekerlek merkezleri', 'en' => 'Wheel cylinders']),
                'level' => 3,
                'sort_order' => 3,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 146,
                'parent_id' => 74,
                'title' => json_encode(['tr' => 'Sabitleme Levhası', 'en' => 'Backing Plate']),
                'slug' => json_encode(['tr' => 'sabitleme-levhasi', 'en' => 'backing-plate']),
                'description' => json_encode(['tr' => 'Fren sabitleme levhaları', 'en' => 'Brake backing plates']),
                'level' => 3,
                'sort_order' => 4,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 147,
                'parent_id' => 74,
                'title' => json_encode(['tr' => 'Fren Cırcırı', 'en' => 'Brake Ratchet']),
                'slug' => json_encode(['tr' => 'fren-circiri', 'en' => 'brake-ratchet']),
                'description' => json_encode(['tr' => 'Fren cırcırları', 'en' => 'Brake ratchets']),
                'level' => 3,
                'sort_order' => 5,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 9.14. Filtreler
            [
                'category_id' => 75,
                'parent_id' => 50,
                'title' => json_encode(['tr' => 'Filtreler', 'en' => 'Filters']),
                'slug' => json_encode(['tr' => 'filtreler', 'en' => 'filters']),
                'description' => json_encode(['tr' => 'Filtre çeşitleri', 'en' => 'Filter varieties']),
                'level' => 2,
                'sort_order' => 14,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 148,
                'parent_id' => 75,
                'title' => json_encode(['tr' => 'Hava Fitresi', 'en' => 'Air Filter']),
                'slug' => json_encode(['tr' => 'hava-filtresi', 'en' => 'air-filter']),
                'description' => json_encode(['tr' => 'Hava filtreleri', 'en' => 'Air filters']),
                'level' => 3,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 149,
                'parent_id' => 75,
                'title' => json_encode(['tr' => 'Hidrolik Filtresi', 'en' => 'Hydraulic Filter']),
                'slug' => json_encode(['tr' => 'hidrolik-filtresi', 'en' => 'hydraulic-filter']),
                'description' => json_encode(['tr' => 'Hidrolik filtreleri', 'en' => 'Hydraulic filters']),
                'level' => 3,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 150,
                'parent_id' => 75,
                'title' => json_encode(['tr' => 'Şanzıman Filtresi', 'en' => 'Transmission Filter']),
                'slug' => json_encode(['tr' => 'sanziman-filtresi', 'en' => 'transmission-filter']),
                'description' => json_encode(['tr' => 'Şanzıman filtreleri', 'en' => 'Transmission filters']),
                'level' => 3,
                'sort_order' => 3,
                'is_active' => true,
                'show_in_menu' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 10. ARŞİV
            [
                'category_id' => 167,
                'parent_id' => null,
                'title' => json_encode(['tr' => 'ARŞİV', 'en' => 'ARCHIVE']),
                'slug' => json_encode(['tr' => 'arsiv', 'en' => 'archive']),
                'description' => json_encode(['tr' => 'Arşiv kategorisi', 'en' => 'Archive category']),
                'level' => 1,
                'sort_order' => 10,
                'is_active' => false,
                'show_in_menu' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Insert categories in batches
        $chunks = array_chunk($categories, 50);
        foreach ($chunks as $chunk) {
            DB::table('shop_categories')->insert($chunk);
        }

        $this->command->info('✅ Shop kategorileri başarıyla eklendi! (' . count($categories) . ' kategori)');
    }
}
