<?php

namespace Modules\AI\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Helpers\TenantHelpers;

class ComprehensiveSectorSeeder extends Seeder
{
    /**
     * KAPSAMLI SEKTÖR SEEDER - 200+ SEKTÖR
     * Git'ten restore edilmiş comprehensive sector listesi
     */
    public function run(): void
    {
        if (!TenantHelpers::isCentral()) {
            return;
        }
        
        echo "🎯 Kapsamlı sektör listesi yükleniyor (200+ sektör)...\n";

        // Mevcut sektörleri temizle
        DB::table('ai_profile_sectors')->truncate();

        // Tüm sektörleri yükle
        $this->loadComprehensiveSectors();

        echo "✅ Kapsamlı sektör listesi tamamlandı!\n";
    }
    
    /**
     * Tüm sektörleri yükle - Git'ten restore edilmiş
     */
    private function loadComprehensiveSectors(): void
    {
        echo "📥 Kapsamlı sektör listesi yükleniyor...\n";
        
        $sectors = [
            // Ana kategoriler (ID 1-20)
            ['id' => 1, 'code' => 'teknoloji', 'name' => 'Teknoloji', 'category_id' => null, 'description' => 'Teknoloji ve bilişim sektörleri', 'emoji' => '💻', 'color' => 'primary', 'keywords' => 'teknoloji,bilişim,yazılım,web', 'is_subcategory' => 0, 'possible_services' => ['Web Tasarımı', 'Yazılım Geliştirme', 'Mobil Uygulama', 'Siber Güvenlik', 'Yapay Zeka', 'Bulut Teknolojileri', 'DevOps', 'Veritabanı Yönetimi', 'IoT Sistemleri', 'Blockchain', 'VR & AR', 'Gaming']],
            ['id' => 2, 'code' => 'pazarlama', 'name' => 'Pazarlama', 'category_id' => null, 'description' => 'Pazarlama ve reklam sektörleri', 'emoji' => '📈', 'color' => 'success', 'keywords' => 'pazarlama,reklam,marketing', 'is_subcategory' => 0, 'possible_services' => ['Dijital Pazarlama', 'Sosyal Medya Yönetimi', 'Reklam Kampanyası', 'İçerik Pazarlama', 'Email Pazarlama', 'Influencer Pazarlama', 'Halkla İlişkiler', 'Marka Yönetimi', 'Etkinlik Pazarlama', 'Growth Hacking', 'SEO & SEM', 'Sosyal Medya Reklamları']],
            ['id' => 3, 'code' => 'hizmet', 'name' => 'Hizmet', 'category_id' => null, 'description' => 'Hizmet sektörleri', 'emoji' => '🤝', 'color' => 'warning', 'keywords' => 'hizmet,danışmanlık,service', 'is_subcategory' => 0, 'possible_services' => ['Müşteri Danışmanlığı', 'Satış ve Pazarlama', 'Proje Yönetimi', 'Müşteri Hizmetleri', 'Eğitim ve Seminer', 'Teknik Destek', 'Danışmanlık Hizmetleri', 'İş Geliştirme', 'Kalıte Kontrol', 'Lojistik Hizmetleri', 'Bakım Onarım', 'Güvenlik Hizmetleri']],
            ['id' => 4, 'code' => 'ticaret', 'name' => 'Ticaret', 'category_id' => null, 'description' => 'Ticaret ve e-ticaret', 'emoji' => '🛒', 'color' => 'danger', 'keywords' => 'ticaret,satış,e-ticaret', 'is_subcategory' => 0, 'possible_services' => ['Perakende Satış', 'E-ticaret', 'Toptan Ticaret', 'İthalat & İhracat', 'Lojistik', 'Marketplace', 'Dropshipping', 'Affiliate Marketing', 'B2B Hizmetleri', 'B2C Hizmetleri', 'Online Satış', 'Stok Yönetimi']],
            ['id' => 5, 'code' => 'saglik', 'name' => 'Sağlık', 'category_id' => null, 'description' => 'Sağlık ve tıp sektörleri', 'emoji' => '⚕️', 'color' => 'info', 'keywords' => 'sağlık,tıp,hastane', 'is_subcategory' => 0, 'possible_services' => ['Genel Sağlık', 'Hastane Hizmetleri', 'Diş Hekimliği', 'Eczane', 'Psikoloji & Psikiyatri', 'Fizyoterapi', 'Alternatif Tıp', 'Beslenme & Diyet', 'Estetik & Güzellik', 'Veteriner', 'Sağlık Danışmanlığı', 'Tıbbi Cihaz']],
            ['id' => 6, 'code' => 'egitim', 'name' => 'Eğitim', 'category_id' => null, 'description' => 'Eğitim ve öğretim', 'emoji' => '🎓', 'color' => 'secondary', 'keywords' => 'eğitim,öğretim,school', 'is_subcategory' => 0, 'possible_services' => ['Genel Eğitim', 'Okul', 'Dil Kursu', 'Online Eğitim', 'Meslek Eğitimi', 'Üniversite', 'Özel Ders', 'Kurumsal Eğitim', 'Anaokulu', 'Sınav Hazırlık', 'Eğitim Danışmanlığı', 'Eğitim Teknolojisi']],
            ['id' => 7, 'code' => 'yemek_icecek', 'name' => 'Yemek & İçecek', 'category_id' => null, 'description' => 'Yemek ve içecek sektörleri', 'emoji' => '🍽️', 'color' => 'orange', 'keywords' => 'yemek,içecek,restoran', 'is_subcategory' => 0, 'possible_services' => ['Restoran', 'Kafe', 'Fırın & Pastane', 'Catering', 'Fast Food', 'Bar & Pub', 'Yemek Servisi', 'Dondurma', 'Organik Gıda', 'Yemek Üretimi', 'Mutfak Danışmanlığı', 'Yemek Eğitimi']],
            ['id' => 8, 'code' => 'sanat_tasarim', 'name' => 'Sanat & Tasarım', 'category_id' => null, 'description' => 'Sanat ve tasarım sektörleri', 'emoji' => '🎨', 'color' => 'purple', 'keywords' => 'sanat,tasarım,grafik', 'is_subcategory' => 0, 'possible_services' => ['Grafik Tasarım', 'Fotoğrafçılık', 'Video Prodüksiyon', 'İç Mimarlık', 'Animasyon', 'Müzik', 'Moda & Tekstil', 'Mücevher', 'El Sanatları', 'Podcast', 'Streaming', 'Kreatif Tasarım']],
            ['id' => 9, 'code' => 'spor_wellness', 'name' => 'Spor & Wellness', 'category_id' => null, 'description' => 'Spor ve sağlık sektörleri', 'emoji' => '🏃', 'color' => 'green', 'keywords' => 'spor,fitness,wellness', 'is_subcategory' => 0, 'possible_services' => ['Fitness', 'Yoga & Pilates', 'Kişisel Antrenörlük', 'Yüzme', 'Dövüş Sanatları', 'Dans', 'Açık Hava Sporları', 'Spa & Wellness', 'Spor Ekipmanları', 'Spor Danışmanlığı', 'Spor Eğitimi', 'Spor Terapisi']],
            ['id' => 10, 'code' => 'otomotiv', 'name' => 'Otomotiv', 'category_id' => null, 'description' => 'Otomotiv ve ulaşım', 'emoji' => '🚗', 'color' => 'dark', 'keywords' => 'otomotiv,ulaşım,araba', 'is_subcategory' => 0, 'possible_services' => ['Araç Satışı', 'Araç Tamiri', 'Araç Bakımı', 'Lastik Hizmetleri', 'Ekspertiz', 'Sigorta', 'Araç Kiralama', 'Oto Galeri', 'Yedek Parça', 'Mekanik Servis', 'Elektrik Servis', 'Kaporta']],
            ['id' => 11, 'code' => 'finans_sigorta', 'name' => 'Finans & Sigorta', 'category_id' => null, 'description' => 'Finans ve sigorta sektörleri', 'emoji' => '💰', 'color' => 'yellow', 'keywords' => 'finans,sigorta,banka', 'is_subcategory' => 0, 'possible_services' => ['Bankacılık', 'Kredi', 'Sigorta', 'Yatırım Danışmanlığı', 'Emlak Finansmanı', 'Bireysel Emeklilik', 'Döviz İşlemleri', 'Leasing', 'Faktoring', 'Borçlanma Danışmanlığı', 'Vergi Danışmanlığı', 'Muhasebe']],
            ['id' => 12, 'code' => 'hukuk', 'name' => 'Hukuk', 'category_id' => null, 'description' => 'Hukuk ve danışmanlık', 'emoji' => '⚖️', 'color' => 'indigo', 'keywords' => 'hukuk,avukat,legal', 'is_subcategory' => 0, 'possible_services' => ['Hukuki Danışmanlık', 'Dava Takibi', 'Hukuki İnceleme', 'Sözleşme Hazırlama', 'Ceza Hukuku', 'Medeni Hukuk', 'Ticaret Hukuku', 'Aile Hukuku', 'Emlak Hukuku', 'Vergi Hukuku', 'Araç Hukuku', 'Miras Hukuku']],
            ['id' => 13, 'code' => 'emlak_insaat', 'name' => 'Emlak & İnşaat', 'category_id' => null, 'description' => 'Emlak ve inşaat sektörleri', 'emoji' => '🏠', 'color' => 'blue', 'keywords' => 'emlak,inşaat,ev', 'is_subcategory' => 0, 'possible_services' => ['Emlak Satışı', 'Emlak Kiralık', 'Emlak Değerleme', 'Gayrimenkul Danışmanlığı', 'İnşaat', 'Tadilar', 'Proje Yönetimi', 'Mimari Tasarım', 'Dekorasyon', 'Tadilat', 'Ev Bakımı', 'Bahçe Düzenleme']],
            ['id' => 14, 'code' => 'guzellik_bakim', 'name' => 'Güzellik & Bakım', 'category_id' => null, 'description' => 'Güzellik ve bakım sektörleri', 'emoji' => '💄', 'color' => 'rose', 'keywords' => 'güzellik,bakım,kuaför', 'is_subcategory' => 0, 'possible_services' => ['Kuaför', 'Berber', 'Cilt Bakımı', 'Makyaj', 'Maniküür', 'Pediküür', 'Lazer Epilasyon', 'Saç Bakımı', 'Güzellik Salonu', 'Estetik', 'Masaj', 'Spa']],
            ['id' => 15, 'code' => 'turizm', 'name' => 'Turizm', 'category_id' => null, 'description' => 'Turizm ve seyahat', 'emoji' => '✈️', 'color' => 'teal', 'keywords' => 'turizm,seyahat,otel', 'is_subcategory' => 0, 'possible_services' => ['Otel İşletmeciliği', 'Tur Operatörlüğü', 'Seyahat Acentesi', 'Rehberlik', 'Konaklama', 'Ulaştırma', 'Gezi Programı', 'Kültür Turları', 'Doğa Turları', 'Gastronomi Turları', 'Kongre Turizmi', 'Sağlık Turizmi']],
            ['id' => 16, 'code' => 'tarim', 'name' => 'Tarım', 'category_id' => null, 'description' => 'Tarım ve hayvancılık', 'emoji' => '🌾', 'color' => 'green', 'keywords' => 'tarım,hayvancılık,çiftlik', 'is_subcategory' => 0, 'possible_services' => ['Bitkisel Üretim', 'Hayvancılık', 'Seracılık', 'Organik Tarım', 'Sulama Sistemleri', 'Tarım Makineleri', 'Gübre Satışı', 'Tohum Satışı', 'Veterinerlik', 'Çiftlik Danışmanlığı', 'Arıcılık', 'Su Ürünleri']],
            ['id' => 17, 'code' => 'sanayi', 'name' => 'Sanayi', 'category_id' => null, 'description' => 'Sanayi ve üretim', 'emoji' => '🏭', 'color' => 'gray', 'keywords' => 'sanayi,üretim,fabrika', 'is_subcategory' => 0, 'possible_services' => ['Makine Üretimi', 'Metal İşleme', 'Plastik Üretim', 'Tekstil Üretim', 'Gıda İşleme', 'Kimya Sanayi', 'Otomotiv Parça', 'İnşaat Malzemesi', 'Elektronik Üretim', 'Sanayi Danışmanlığı', 'Üretim Planlama', 'Kalite Kontrol']],
            ['id' => 18, 'code' => 'diger_hizmetler', 'name' => 'Diğer Hizmetler', 'category_id' => null, 'description' => 'Diğer hizmet sektörleri', 'emoji' => '🔧', 'color' => 'secondary', 'keywords' => 'diğer,hizmet,genel', 'is_subcategory' => 0, 'possible_services' => ['Genel Danışmanlık', 'İş Geliştirme', 'Proje Yönetimi', 'Araştırma', 'Analiz Hizmetleri', 'Özel Hizmetler', 'Konsültasyon', 'Koordinasyon', 'Organizasyon', 'Destek Hizmetleri', 'Özelleştirilmiş Çözümler', 'Stratejik Planlama']],
            
            // TEKNOLOJİ Alt Sektörleri (ID 21-50)
            ['id' => 21, 'code' => 'web', 'name' => 'Web Tasarım & Geliştirme', 'category_id' => 1, 'description' => 'Website tasarım, UI/UX, frontend/backend geliştirme', 'emoji' => '🌐', 'color' => 'primary', 'keywords' => 'web,tasarım,ui,ux,website,frontend,backend', 'is_subcategory' => 1, 'possible_services' => ['Website Tasarımı', 'UI/UX Tasarım', 'Frontend Geliştirme', 'Backend Geliştirme', 'Responsive Tasarım', 'E-ticaret Siteleri', 'Kurumsal Web Siteleri', 'Kişisel Bloglar', 'WordPress Geliştirme', 'Laravel Geliştirme', 'React/Vue.js Geliştirme', 'API Geliştirme']],
            ['id' => 22, 'code' => 'software', 'name' => 'Yazılım Geliştirme', 'category_id' => 1, 'description' => 'Mobil ve web uygulamaları, masaüstü yazılım', 'emoji' => '⚡', 'color' => 'primary', 'keywords' => 'yazılım,geliştirme,kod,programming,app', 'is_subcategory' => 1, 'possible_services' => ['Mobil Uygulama Geliştirme', 'Web Uygulaması Geliştirme', 'Masaüstü Yazılım', 'Yazılım Danışmanlığı', 'Sistem Entegrasyonu', 'Veritabanı Yönetimi', 'Kod İnceleme', 'Yazılım Testi', 'Teknik Dokümantasyon', 'Proje Yönetimi']],
            ['id' => 23, 'code' => 'mobile', 'name' => 'Mobil Uygulama', 'category_id' => 1, 'description' => 'iOS ve Android uygulamaları, React Native, Flutter', 'emoji' => '📱', 'color' => 'primary', 'keywords' => 'mobil,uygulama,ios,android,app,react,flutter', 'is_subcategory' => 1, 'possible_services' => ['iOS Uygulama Geliştirme', 'Android Uygulama Geliştirme', 'React Native Geliştirme', 'Flutter Geliştirme', 'Hibrit Uygulama Geliştirme', 'Uygulama Mağazası Yayınlama', 'Uygulama Bakım ve Güncelleme', 'Push Notification Entegrasyonu', 'Uygulama Analizi', 'Uygulama Performans Optimizasyonu']],
            ['id' => 24, 'code' => 'cybersecurity', 'name' => 'Siber Güvenlik', 'category_id' => 1, 'description' => 'Siber güvenlik hizmetleri, penetrasyon testleri', 'emoji' => '🔒', 'color' => 'primary', 'keywords' => 'güvenlik,siber,security,koruma,pentest', 'is_subcategory' => 1, 'possible_services' => ['Penetrasyon Testleri', 'Güvenlik Danışmanlığı', 'Siber Güvenlik Eğitimi', 'Zararlı Yazılım Analizi', 'Güvenlik Duvarı Kurulumu', 'Veri Şifreleme', 'Güvenlik Politikaları', 'Olay Müdahale', 'Güvenlik Denetimi', 'İç Tehdit Analizi']],
            ['id' => 25, 'code' => 'ai_ml', 'name' => 'Yapay Zeka & ML', 'category_id' => 1, 'description' => 'Yapay zeka, makine öğrenmesi, veri analizi', 'emoji' => '🤖', 'color' => 'primary', 'keywords' => 'ai,ml,yapay,zeka,makine,öğrenmesi,veri', 'is_subcategory' => 1, 'possible_services' => ['Makine Öğrenmesi Modelleri', 'Veri Analizi', 'Yapay Zeka Danışmanlığı', 'Chatbot Geliştirme', 'Görüntü İşleme', 'Doğal Dil İşleme', 'Tahmin Modelleri', 'Otomasyon Çözümleri', 'Büyük Veri Analizi', 'AI Eğitimi']],
            ['id' => 26, 'code' => 'blockchain_crypto', 'name' => 'Blockchain & Kripto', 'category_id' => 1, 'description' => 'Blockchain teknolojisi, kripto danışmanlığı', 'emoji' => '₿', 'color' => 'primary', 'keywords' => 'blockchain,kripto,bitcoin,ethereum,web3', 'is_subcategory' => 1, 'possible_services' => ['Blockchain Geliştirme', 'Kripto Para Danışmanlığı', 'Smart Contract Geliştirme', 'NFT Marketplace', 'DeFi Uygulamaları', 'Token Geliştirme', 'Blockchain Eğitimi', 'Kripto Cüzdan Geliştirme', 'Blockchain Danışmanlığı', 'Web3 Geliştirme']],
            ['id' => 27, 'code' => 'cloud', 'name' => 'Bulut Teknolojileri', 'category_id' => 1, 'description' => 'AWS, Azure, Google Cloud hizmetleri', 'emoji' => '☁️', 'color' => 'primary', 'keywords' => 'cloud,bulut,aws,azure,google,hosting', 'is_subcategory' => 1, 'possible_services' => ['AWS Hizmetleri', 'Azure Hizmetleri', 'Google Cloud Hizmetleri', 'Bulut Migrasyonu', 'Bulut Güvenliği', 'Sunucu Yönetimi', 'Bulut Optimizasyonu', 'Yedekleme Çözümleri', 'Monitoring ve İzleme', 'Bulut Eğitimi']],
            ['id' => 28, 'code' => 'devops', 'name' => 'DevOps & Altyapı', 'category_id' => 1, 'description' => 'DevOps, CI/CD, sistem yönetimi', 'emoji' => '🔧', 'color' => 'primary', 'keywords' => 'devops,ci,cd,altyapı,sistem,yönetimi', 'is_subcategory' => 1, 'possible_services' => ['CI/CD Pipeline Kurulumu', 'DevOps Danışmanlığı', 'Sistem Yönetimi', 'Konteyner Teknolojileri', 'Kubernetes Yönetimi', 'Altyapı Otomasyonu', 'Monitoring ve Alerting', 'Log Yönetimi', 'Performans Optimizasyonu', 'DevOps Eğitimi']],
            ['id' => 29, 'code' => 'database', 'name' => 'Veritabanı & Big Data', 'category_id' => 1, 'description' => 'Veritabanı yönetimi, big data analizi', 'emoji' => '🗄️', 'color' => 'primary', 'keywords' => 'veritabanı,database,big,data,analiz', 'is_subcategory' => 1, 'possible_services' => ['Veritabanı Tasarımı', 'Veritabanı Yönetimi', 'Big Data Analizi', 'Veri Modelleme', 'Veri Migrasyonu', 'Performans Optimizasyonu', 'Veri Güvenliği', 'Yedekleme ve Kurtarma', 'Veri Görselleştirme', 'Veritabanı Eğitimi']],
            ['id' => 30, 'code' => 'iot', 'name' => 'IoT & Akıllı Sistemler', 'category_id' => 1, 'description' => 'Internet of Things, akıllı ev sistemleri', 'emoji' => '🏠', 'color' => 'primary', 'keywords' => 'iot,akıllı,sistemler,sensör,otomasyon', 'is_subcategory' => 1, 'possible_services' => ['IoT Sistem Geliştirme', 'Akıllı Ev Sistemleri', 'Sensör Entegrasyonu', 'Otomasyon Çözümleri', 'IoT Danışmanlığı', 'Veri Toplama ve İşleme', 'Uzaktan Monitoring', 'IoT Güvenliği', 'Edge Computing', 'IoT Eğitimi']],
            
            // PAZARLAMA Alt Sektörleri (ID 51-70)
            ['id' => 51, 'code' => 'digital_marketing', 'name' => 'Dijital Pazarlama', 'category_id' => 2, 'description' => 'SEO, SEM, sosyal medya pazarlama', 'emoji' => '🚀', 'color' => 'success', 'keywords' => 'dijital,pazarlama,seo,sem,sosyal,medya', 'is_subcategory' => 1, 'possible_services' => ['SEO Optimizasyonu', 'Google Ads Yönetimi', 'Facebook Ads', 'Instagram Ads', 'YouTube Ads', 'LinkedIn Ads', 'E-mail Pazarlama', 'Influencer Pazarlama', 'Affiliate Pazarlama', 'Conversion Rate Optimization', 'Google Analytics', 'Pazarlama Otomasyonu']],
            ['id' => 52, 'code' => 'social_media', 'name' => 'Sosyal Medya Yönetimi', 'category_id' => 2, 'description' => 'Instagram, Facebook, LinkedIn yönetimi', 'emoji' => '📲', 'color' => 'success', 'keywords' => 'sosyal,medya,instagram,facebook,linkedin', 'is_subcategory' => 1, 'possible_services' => ['Instagram Yönetimi', 'Facebook Yönetimi', 'Twitter Yönetimi', 'LinkedIn Yönetimi', 'TikTok Yönetimi', 'YouTube Yönetimi', 'İçerik Planlama', 'Sosyal Medya Tasarımı', 'Topluluk Yönetimi', 'Sosyal Medya Analizi', 'Hashtagging', 'Sosyal Medya Reklamları']],
            ['id' => 53, 'code' => 'advertising', 'name' => 'Reklam Ajansı', 'category_id' => 2, 'description' => 'Reklam kampanyaları, kreatif tasarım', 'emoji' => '📢', 'color' => 'success', 'keywords' => 'reklam,ajans,kampanya,kreatif,tasarım', 'is_subcategory' => 1, 'possible_services' => ['Reklam Kampanyası Tasarımı', 'Kreatif Tasarım', 'Marka Konumlandırma', 'Reklam Stratejisi', 'Medya Planlama', 'Grafik Tasarım', 'Video Prodüksiyonu', 'Fotoğraf Çekimi', 'Copywriting', 'Outdoor Reklam', 'TV Reklamı', 'Radyo Reklamı']],
            ['id' => 54, 'code' => 'content_marketing', 'name' => 'İçerik Pazarlama', 'category_id' => 2, 'description' => 'Blog yazılımı, video içerik, podcast', 'emoji' => '📝', 'color' => 'success', 'keywords' => 'içerik,pazarlama,blog,video,podcast', 'is_subcategory' => 1, 'possible_services' => ['Blog Yazarlığı', 'İçerik Stratejisi', 'Video İçerik Üretimi', 'Podcast Üretimi', 'E-book Hazırlama', 'Infografik Tasarımı', 'Sosyal Medya İçeriği', 'SEO İçerik Yazımı', 'İçerik Planlama', 'Çeviri ve Lokalizasyon', 'İçerik Editörlüğü', 'İçerik Analizi']],
            ['id' => 55, 'code' => 'email_marketing', 'name' => 'Email Pazarlama', 'category_id' => 2, 'description' => 'E-mail kampanyaları, newsletter', 'emoji' => '📧', 'color' => 'success', 'keywords' => 'email,pazarlama,newsletter,kampanya', 'is_subcategory' => 1, 'possible_services' => ['E-mail Kampanyası Tasarımı', 'Newsletter Hazırlama', 'E-mail Otomasyonu', 'Lead Nurturing', 'E-mail Template Tasarımı', 'A/B Testing', 'Liste Segmentasyonu', 'E-mail Analizi', 'Deliverability Optimizasyonu', 'CRM Entegrasyonu', 'Drip Campaigns', 'E-mail Copywriting']],
            ['id' => 56, 'code' => 'influencer', 'name' => 'Influencer Pazarlama', 'category_id' => 2, 'description' => 'Influencer campaign yönetimi', 'emoji' => '🌟', 'color' => 'success', 'keywords' => 'influencer,pazarlama,campaign,sosyal', 'is_subcategory' => 1, 'possible_services' => ['Influencer Bulma', 'Kampanya Yönetimi', 'İçerik Planlama', 'Performans Takibi', 'Mikro Influencer Marketing', 'Makro Influencer Marketing', 'Nano Influencer Marketing', 'Influencer Sözleşmeleri', 'ROI Analizi', 'Influencer Eğitimi', 'Uzun Vadeli Ortaklıklar', 'Influencer Etkinlik Yönetimi']],
            ['id' => 57, 'code' => 'pr', 'name' => 'Halkla İlişkiler', 'category_id' => 2, 'description' => 'PR, basın ilişkileri, marka itibarı', 'emoji' => '📰', 'color' => 'success', 'keywords' => 'pr,halkla,ilişkiler,basın,marka', 'is_subcategory' => 1, 'possible_services' => ['Basın Bülteni Yazımı', 'Medya İlişkileri', 'Kriz İletişimi', 'Marka İtibarı Yönetimi', 'Etkinlik Organizasyonu', 'Basın Konferansı', 'Medya Monitoring', 'Influencer Relations', 'Corporate Communications', 'Investor Relations', 'Internal Communications', 'Toplumsal Sorumluluk']],
            ['id' => 58, 'code' => 'brand_management', 'name' => 'Marka Yönetimi', 'category_id' => 2, 'description' => 'Marka stratejisi, konumlandırma', 'emoji' => '🏷️', 'color' => 'success', 'keywords' => 'marka,yönetimi,strateji,konumlandırma', 'is_subcategory' => 1, 'possible_services' => ['Marka Stratejisi', 'Marka Kimliği Tasarımı', 'Logo Tasarımı', 'Marka Rehberi', 'Marka Konumlandırma', 'Marka Araştırması', 'Marka Değerlendirme', 'Rebranding', 'Marka Koruma', 'Marka Deneyimi', 'Marka Hikayesi', 'Marka Mimarisi']],
            ['id' => 59, 'code' => 'event_marketing', 'name' => 'Etkinlik Pazarlama', 'category_id' => 2, 'description' => 'Etkinlik organizasyonu, lansman', 'emoji' => '🎉', 'color' => 'success', 'keywords' => 'etkinlik,pazarlama,organizasyon,lansman', 'is_subcategory' => 1, 'possible_services' => ['Etkinlik Planlama', 'Kongre Organizasyonu', 'Fuar Organizasyonu', 'Lansman Etkinlikleri', 'Kurumsal Etkinlikler', 'Hybrid Etkinlikler', 'Sanal Etkinlikler', 'Etkinlik Pazarlama', 'Sponsor Bulma', 'Etkinlik Teknolojisi', 'Etkinlik Analizi', 'Post-Event Marketing']],
            ['id' => 60, 'code' => 'growth_hacking', 'name' => 'Growth Hacking', 'category_id' => 2, 'description' => 'Büyüme stratejileri, viral pazarlama', 'emoji' => '📊', 'color' => 'success', 'keywords' => 'growth,hacking,büyüme,viral,pazarlama', 'is_subcategory' => 1, 'possible_services' => ['Growth Strategy', 'Viral Marketing', 'A/B Testing', 'Funnel Optimization', 'User Acquisition', 'Retention Strategies', 'Referral Programs', 'Product Marketing', 'Growth Analytics', 'Marketing Automation', 'Customer Journey Mapping', 'Experiment Design']],
            
            // SAĞLIK Alt Sektörleri (ID 71-100)
            ['id' => 71, 'code' => 'health', 'name' => 'Genel Sağlık', 'category_id' => 5, 'description' => 'Genel sağlık hizmetleri, pratisyen hekim', 'emoji' => '⚕️', 'color' => 'info', 'keywords' => 'sağlık,genel,pratisyen,hekim,doktor', 'is_subcategory' => 1, 'possible_services' => ['Genel Muayene', 'Sağlık Kontrolü', 'Aşılama', 'Kan Tahlili', 'Tansiyon Ölçümü', 'Kalp Dinleme', 'Sağlık Danışmanlığı', 'Hastalık Teşhisi', 'İlaç Reçetesi', 'Sağlık Raporu', 'Hasta Takibi', 'Sevk İşlemi']],
            ['id' => 72, 'code' => 'hospital', 'name' => 'Hastane', 'category_id' => 5, 'description' => 'Hastane hizmetleri, klinik', 'emoji' => '🏥', 'color' => 'info', 'keywords' => 'hastane,klinik,tıbbi,hizmet,tedavi', 'is_subcategory' => 1, 'possible_services' => ['Acil Servis', 'Yatan Hasta Hizmeti', 'Poliklinik', 'Ameliyathane', 'Yoğun Bakım', 'Radyoloji', 'Laboratuvar', 'Eczane', 'Ambulans', 'Hasta Nakli', 'Tıbbi Görüntüleme', 'Hasta Kabul']],
            ['id' => 73, 'code' => 'dental', 'name' => 'Diş Hekimliği', 'category_id' => 5, 'description' => 'Diş tedavisi, ağız sağlığı', 'emoji' => '🦷', 'color' => 'info', 'keywords' => 'diş,hekimliği,ağız,sağlığı,dental', 'is_subcategory' => 1, 'possible_services' => ['Diş Muayenesi', 'Diş Temizliği', 'Diş Dolgusu', 'Diş Çekimi', 'Kanal Tedavisi', 'Diş Protezi', 'Diş İmplantı', 'Diş Beyazlatma', 'Ortodonti', 'Diş Eti Tedavisi', 'Periodontoloji', 'Oral Cerrahi']],
            ['id' => 74, 'code' => 'pharmacy', 'name' => 'Eczane', 'category_id' => 5, 'description' => 'Eczane hizmetleri, ilaç danışmanlığı', 'emoji' => '💊', 'color' => 'info', 'keywords' => 'eczane,ilaç,danışmanlık,pharmacy', 'is_subcategory' => 1, 'possible_services' => ['İlaç Satışı', 'İlaç Danışmanlığı', 'Reçete Okuma', 'Vitamin Takviyesi', 'Tıbbi Cihaz Satışı', 'Kan Şekeri Ölçümü', 'Tansiyon Ölçümü', 'İlaç Siparişi', 'Sağlık Ürünleri', 'Bebek Mama ve Bezi', 'Kozmetik Ürünler', 'İlaç Etkileşimi Kontrolü']],
            ['id' => 75, 'code' => 'psychology', 'name' => 'Psikoloji & Psikiyatri', 'category_id' => 5, 'description' => 'Psikolojik destek, terapi', 'emoji' => '🧠', 'color' => 'info', 'keywords' => 'psikoloji,psikiyatri,terapi,destek', 'is_subcategory' => 1, 'possible_services' => ['Psikolojik Danışmanlık', 'Psikoterapi', 'Aile Terapisi', 'Çift Terapisi', 'Çocuk Psikolojisi', 'Depresyon Tedavisi', 'Anksiyete Tedavisi', 'Travma Terapisi', 'Grup Terapisi', 'Psikiyatrik İlaç Yönetimi', 'Stres Yönetimi', 'Davranış Terapisi']],
            ['id' => 76, 'code' => 'physiotherapy', 'name' => 'Fizyoterapi', 'category_id' => 5, 'description' => 'Fizyoterapi, rehabilitasyon', 'emoji' => '🤲', 'color' => 'info', 'keywords' => 'fizyoterapi,rehabilitasyon,tedavi', 'is_subcategory' => 1, 'possible_services' => ['Fizyoterapi Seansları', 'Rehabilitasyon', 'Egzersiz Terapisi', 'Manyal Terapi', 'Elektroterapi', 'Hidroterapi', 'Spor Fizyoterapisi', 'Nörolojik Fizyoterapi', 'Ortopedik Fizyoterapi', 'Soluk Alış Terapisi', 'Postural Eğitim', 'Ağrı Yönetimi']],
            ['id' => 77, 'code' => 'alternative_medicine', 'name' => 'Alternatif Tıp', 'category_id' => 5, 'description' => 'Akupunktur, bitkisel tedavi', 'emoji' => '🌿', 'color' => 'info', 'keywords' => 'alternatif,tıp,akupunktur,bitkisel', 'is_subcategory' => 1, 'possible_services' => ['Akupunktur', 'Bitkisel Tedavi', 'Homeopati', 'Osteopati', 'Refleksoloji', 'Aromaterapi', 'Yoga Terapisi', 'Reiki', 'Hirudoterapi', 'Kupa Terapisi', 'Doğal Beslenme Danışmanlığı', 'Enerji Terapisi']],
            ['id' => 78, 'code' => 'nutrition', 'name' => 'Beslenme & Diyet', 'category_id' => 5, 'description' => 'Diyetisyen, beslenme danışmanlığı', 'emoji' => '🥗', 'color' => 'info', 'keywords' => 'beslenme,diyet,diyetisyen,sağlık', 'is_subcategory' => 1, 'possible_services' => ['Beslenme Danışmanlığı', 'Diyet Programı', 'Kilo Verme Programı', 'Kilo Alma Programı', 'Spor Beslenmesi', 'Hastalık Diyeti', 'Beslenme Eğitimi', 'Yemek Planı', 'Vücut Kompozisyonu Analizi', 'Metabolizma Analizi', 'Detoks Programı', 'Beslenme Takibi']],
            ['id' => 79, 'code' => 'aesthetic', 'name' => 'Estetik & Güzellik', 'category_id' => 5, 'description' => 'Estetik cerrahi, güzellik merkezi', 'emoji' => '💅', 'color' => 'info', 'keywords' => 'estetik,güzellik,cerrahi,merkezi', 'is_subcategory' => 1, 'possible_services' => ['Estetik Cerrahi', 'Botoks', 'Dolgu', 'Lazer Epilasyon', 'Cilt Bakımı', 'Anti-aging', 'Liposuction', 'Meme Estetik', 'Burun Estetik', 'Yüz Germe', 'Cilt Yenileme', 'Leke Tedavisi']],
            ['id' => 80, 'code' => 'veterinary', 'name' => 'Veteriner', 'category_id' => 5, 'description' => 'Veteriner hizmetleri, hayvan sağlığı', 'emoji' => '🐕', 'color' => 'info', 'keywords' => 'veteriner,hayvan,sağlığı,hizmet', 'is_subcategory' => 1, 'possible_services' => ['Hayvan Muayenesi', 'Hayvan Aşılama', 'Hayvan Cerrahisi', 'Hayvan Diş Bakımı', 'Hayvan Laboratu varı', 'Pet Grooming', 'Hayvan Radiografisi', 'Kedi Kısırlaştırma', 'Köpek Eğitimi', 'Hayvan Pansumanı', 'Acil Veteriner', 'Hayvan Sağlık Sertifikası']],
            
            // EĞİTİM Alt Sektörleri (ID 101-120)
            ['id' => 101, 'code' => 'education', 'name' => 'Genel Eğitim', 'category_id' => 6, 'description' => 'Eğitim hizmetleri, öğretim', 'emoji' => '🎓', 'color' => 'secondary', 'keywords' => 'eğitim,öğretim,ders,kurs', 'is_subcategory' => 1, 'possible_services' => ['Genel Eğitim', 'Öğretim', 'Ders Verme', 'Kurs', 'Eğitim Danışmanlığı', 'Eğitim Planı', 'Müfredat Hazırlama', 'Eğitim Materyali', 'Öğrenci Değerlendirme', 'Eğitim Yönetimi', 'Eğitim Koordinatörlüğü', 'Eğitim Teknolojisi']],
            ['id' => 102, 'code' => 'school', 'name' => 'Okul', 'category_id' => 6, 'description' => 'Okul eğitimi, öğrenci hizmetleri', 'emoji' => '🏫', 'color' => 'secondary', 'keywords' => 'okul,öğrenci,eğitim,sınıf', 'is_subcategory' => 1, 'possible_services' => ['Okul Öncesi Eğitim', 'İlkokul Eğitimi', 'Ortaokul Eğitimi', 'Lise Eğitimi', 'Sınıf Yönetimi', 'Öğrenci Rehberliği', 'Veli Toplantısı', 'Okul Etkinlikleri', 'Öğrenci Kulupleri', 'Spor Etkinlikleri', 'Kütüphane', 'Laboratu var']],
            ['id' => 103, 'code' => 'language', 'name' => 'Dil Kursu', 'category_id' => 6, 'description' => 'Yabancı dil eğitimi, çeviri', 'emoji' => '🗣️', 'color' => 'secondary', 'keywords' => 'dil,kurs,yabancı,çeviri,language', 'is_subcategory' => 1, 'possible_services' => ['İngilizce Kursu', 'Almanca Kursu', 'Fransızca Kursu', 'Rusca Kursu', 'Arapça Kursu', 'Çince Kursu', 'Japonca Kursu', 'İspanyolca Kursu', 'Yabancı Dil Çevirisi', 'Konver sasyon Kursu', 'Gramer Eğitimi', 'Dil Sertifikası Hazırlık']],
            ['id' => 104, 'code' => 'online_education', 'name' => 'Online Eğitim', 'category_id' => 6, 'description' => 'Uzaktan eğitim, e-learning', 'emoji' => '💻', 'color' => 'secondary', 'keywords' => 'online,eğitim,uzaktan,e-learning', 'is_subcategory' => 1, 'possible_services' => ['Online Kurs', 'Uzaktan Eğitim', 'E-learning', 'Video Dersler', 'Canlı Ders', 'Online Sınav', 'Eğitim Platformı', 'LMS Yönetimi', 'Online Sertifika', 'İnteraktif İçerik', 'Eğitim Analitiği', 'Mobil Eğitim']],
            ['id' => 105, 'code' => 'vocational', 'name' => 'Meslek Eğitimi', 'category_id' => 6, 'description' => 'Meslek kursu, sertifika programı', 'emoji' => '🔧', 'color' => 'secondary', 'keywords' => 'meslek,eğitimi,kurs,sertifika', 'is_subcategory' => 1, 'possible_services' => ['Meslek Kursu', 'Sertifika Programı', 'Beceri Geliştirme', 'Staj Programı', 'Meslek Danışmanlığı', 'Teknik Eğitim', 'Uygulamalı Eğitim', 'Meslek Lisanslama', 'İş Yerleştirme', 'Kariyer Rehberliği', 'Uzmanlık Eğitimi', 'Meslek Standardı']],
            ['id' => 106, 'code' => 'university', 'name' => 'Üniversite', 'category_id' => 6, 'description' => 'Yükseköğretim, akademik', 'emoji' => '🎓', 'color' => 'secondary', 'keywords' => 'üniversite,yükseköğretim,akademik', 'is_subcategory' => 1, 'possible_services' => ['Lisans Eğitimi', 'Yüksek Lisans', 'Doktora', 'Akademik Danışmanlık', 'Araştırma', 'Yayıncılık', 'Tez Danışmanlığı', 'Bilimsel Proje', 'Konferans', 'Seminer', 'Akademik Yazım', 'Peer Review']],
            ['id' => 107, 'code' => 'tutoring', 'name' => 'Özel Ders', 'category_id' => 6, 'description' => 'Özel dersler, birebir eğitim', 'emoji' => '📚', 'color' => 'secondary', 'keywords' => 'özel,ders,birebir,eğitim', 'is_subcategory' => 1, 'possible_services' => ['Matematik Dersi', 'Fizik Dersi', 'Kimya Dersi', 'Biyoloji Dersi', 'Tarih Dersi', 'Coğrafya Dersi', 'Edebiyat Dersi', 'İngilizce Dersi', 'Birebir Eğitim', 'Grup Dersi', 'Sınav Hazırlık', 'Ödev Yardımı']],
            ['id' => 108, 'code' => 'training', 'name' => 'Kurumsal Eğitim', 'category_id' => 6, 'description' => 'Şirket eğitimleri, workshop', 'emoji' => '🏢', 'color' => 'secondary', 'keywords' => 'kurumsal,eğitim,şirket,workshop', 'is_subcategory' => 1, 'possible_services' => ['Kurumsal Eğitim', 'Personel Eğitimi', 'Liderlik Eğitimi', 'Satış Eğitimi', 'İletişim Eğitimi', 'Takım Çalışması', 'Workshop', 'Seminer', 'Eğitim Danışmanlığı', 'Performance Coaching', 'Motivasyon Eğitimi', 'Stres Yönetimi Eğitimi']],
            ['id' => 109, 'code' => 'kindergarten', 'name' => 'Anaokulu', 'category_id' => 6, 'description' => 'Anaokulu, okul öncesi eğitim', 'emoji' => '🧸', 'color' => 'secondary', 'keywords' => 'anaokulu,okul,öncesi,eğitim', 'is_subcategory' => 1, 'possible_services' => ['Okul Öncesi Eğitim', 'Çocuk Bakımı', 'Oyun Eğitimi', 'Sosyal Gelişim', 'Motor Gelişim', 'Dil Gelişimi', 'Kreatif Etkinlikler', 'Müzik Eğitimi', 'Sanat Eğitimi', 'Çocuk Psikolojisi', 'Veli Eğitimi', 'Beslenme Programı']],
            ['id' => 110, 'code' => 'exam_prep', 'name' => 'Sınav Hazırlık', 'category_id' => 6, 'description' => 'YKS, ALES, KPSS hazırlık', 'emoji' => '📝', 'color' => 'secondary', 'keywords' => 'sınav,hazırlık,yks,ales,kpss', 'is_subcategory' => 1, 'possible_services' => ['YKS Hazırlık', 'ALES Hazırlık', 'KPSS Hazırlık', 'DGS Hazırlık', 'TOEFL Hazırlık', 'IELTS Hazırlık', 'Sınav Teknikleri', 'Deneme Sınavı', 'Sınav Stres Yönetimi', 'Konu Tekrarı', 'Soru Çözümü', 'Bireysel Hazırlık']],
            
            // YEMEK & İÇECEK Alt Sektörleri (ID 121-140)
            ['id' => 121, 'code' => 'food', 'name' => 'Yemek & İçecek', 'category_id' => 7, 'description' => 'Genel yemek ve içecek hizmetleri', 'emoji' => '🍽️', 'color' => 'orange', 'keywords' => 'yemek,içecek,food,restoran', 'is_subcategory' => 1, 'possible_services' => ['Yemek Hazırlama', 'Yemek Servisi', 'Özel Menü Tasarımı', 'Yemek Danışmanlığı', 'Beslenme Planı', 'Diyet Yemekleri', 'Vegan Yemekler', 'Vejetaryen Seçenekler', 'Geleneksel Yemekler', 'Dünya Mutfağı', 'Yerel Lezzetler', 'Sağlıklı Beslenme']],
            ['id' => 122, 'code' => 'restaurant', 'name' => 'Restoran', 'category_id' => 7, 'description' => 'Restoran, lokanta hizmetleri', 'emoji' => '🍴', 'color' => 'orange', 'keywords' => 'restoran,lokanta,yemek,meal', 'is_subcategory' => 1, 'possible_services' => ['Restoran Hizmeti', 'Yemek Menüsü', 'Servis', 'Rezervasyon', 'Açık Büfe', 'A la Carte', 'Grup Yemekleri', 'Özel Etkinlik Yemekleri', 'Çocuk Menüsü', 'Alkollü İçecekler', 'Tatlı Servisi', 'Kahvaltı Servisi']],
            ['id' => 123, 'code' => 'cafe', 'name' => 'Kafe', 'category_id' => 7, 'description' => 'Kafe, kahvehane, coffee shop', 'emoji' => '☕', 'color' => 'orange', 'keywords' => 'kafe,kahve,coffee,shop', 'is_subcategory' => 1, 'possible_services' => ['Kahve', 'Çay', 'Tatlı', 'Wifi', 'Çalışma Alanı', 'Toplantı Salonu', 'Özel Kahve Çeşitleri', 'Sıcak İçecekler', 'Soğuk İçecekler', 'Atıştırmalık', 'Kahvaltı', 'Sakin Ortam']],
            ['id' => 124, 'code' => 'bakery', 'name' => 'Fırın & Pastane', 'category_id' => 7, 'description' => 'Fırın, pastane, ekmek üretimi', 'emoji' => '🥐', 'color' => 'orange', 'keywords' => 'fırın,pastane,ekmek,pasta', 'is_subcategory' => 1, 'possible_services' => ['Ekmek', 'Pasta', 'Kurabiye', 'Doğum Günü Pastası', 'Düğün Pastası', 'Börek', 'Poğaça', 'Simit', 'Açma', 'Baklava', 'Tatlı Çeşitleri', 'Özel Sipariş Pastalar']],
            ['id' => 125, 'code' => 'catering', 'name' => 'Catering', 'category_id' => 7, 'description' => 'Catering hizmetleri, etkinlik yemekleri', 'emoji' => '🍱', 'color' => 'orange', 'keywords' => 'catering,etkinlik,yemek,servis', 'is_subcategory' => 1, 'possible_services' => ['Etkinlik Catering', 'Düğün Yemekleri', 'Kurumsal Catering', 'Toplu Yemek', 'Özel Etkinlik Servisi', 'Kokteyller', 'Büfe Servisi', 'Menü Planlama', 'Servis Ekibi', 'Ekipman Kiralama', 'İçecek Servisi', 'Tatlı Servisi']],
            ['id' => 126, 'code' => 'fast_food', 'name' => 'Fast Food', 'category_id' => 7, 'description' => 'Fast food, hızlı yemek servisi', 'emoji' => '🍔', 'color' => 'orange', 'keywords' => 'fast,food,hızlı,yemek', 'is_subcategory' => 1, 'possible_services' => ['Hamburger', 'Pizza', 'Döner', 'Pide', 'Lahmacun', 'Sandviç', 'Tavuk Menüleri', 'Patates Kızartması', 'Soğuk İçecekler', 'Hızlı Servis', 'Paket Servis', 'Drive-Thru']],
            ['id' => 127, 'code' => 'bar', 'name' => 'Bar & Pub', 'category_id' => 7, 'description' => 'Bar, pub, içecek servisi', 'emoji' => '🍺', 'color' => 'orange', 'keywords' => 'bar,pub,içecek,alkol', 'is_subcategory' => 1, 'possible_services' => ['Alkollü İçecekler', 'Bira Çeşitleri', 'Kokteyl', 'Meyhane Kültürü', 'Canlı Müzik', 'DJ', 'Atıştırmalık', 'Meze Çeşitleri', 'Rakı Sofrası', 'Şarap Çeşitleri', 'Sosyal Ortam', 'Eğlence']],
            ['id' => 128, 'code' => 'food_delivery', 'name' => 'Yemek Servisi', 'category_id' => 7, 'description' => 'Yemek teslimatı, online sipariş', 'emoji' => '🚚', 'color' => 'orange', 'keywords' => 'yemek,servisi,teslimat,delivery', 'is_subcategory' => 1, 'possible_services' => ['Yemek Teslimatı', 'Online Sipariş', 'Mobil Uygulama', 'Hızlı Teslimat', 'Sıcak Teslimat', 'Paket Servis', 'Toplu Sipariş', 'Kurumsal Teslimat', 'Öğle Yemeği Servisi', 'Akşam Yemeği Servisi', '7/24 Servis', 'Ev Yemekleri Servisi']],
            ['id' => 129, 'code' => 'ice_cream', 'name' => 'Dondurma', 'category_id' => 7, 'description' => 'Dondurma, tatlı hizmetleri', 'emoji' => '🍦', 'color' => 'orange', 'keywords' => 'dondurma,tatlı,dessert,ice', 'is_subcategory' => 1, 'possible_services' => ['Dondurma Çeşitleri', 'Gelato', 'Frozen Yogurt', 'Milkshake', 'Smoothie', 'Waffle', 'Krep', 'Tatlı Soslar', 'Meyveli Dondurma', 'Özel Tatlar', 'Parti Dondurmalar', 'Dondurma Pastası']],
            ['id' => 130, 'code' => 'organic_food', 'name' => 'Organik Gıda', 'category_id' => 7, 'description' => 'Organik gıda, sağlıklı beslenme', 'emoji' => '🥬', 'color' => 'orange', 'keywords' => 'organik,gıda,sağlıklı,beslenme', 'is_subcategory' => 1, 'possible_services' => ['Organik Sebze', 'Organik Meyve', 'Doğal Ürünler', 'Glutensiz Gıda', 'Vegan Ürünler', 'Süt Ürünleri', 'Tahıl Ürünleri', 'Doğal Bal', 'Organik Et', 'Sağlıklı Atıştırmalık', 'Detoks Ürünleri', 'Beslenme Danışmanlığı']],
            
            // SANAT & TASARIM Alt Sektörleri (ID 141-160)
            ['id' => 141, 'code' => 'art_design', 'name' => 'Sanat & Tasarım', 'category_id' => 8, 'description' => 'Genel sanat ve tasarım hizmetleri', 'emoji' => '🎨', 'color' => 'purple', 'keywords' => 'sanat,tasarım,art,design', 'is_subcategory' => 1, 'possible_services' => ['Sanat Eğitimi', 'Resim Kursu', 'Heykel Atölyesi', 'Sanat Danışmanlığı', 'Sanat Eseri Değerlendirme', 'Sanat Galeri Yönetimi', 'Sanat Etkinlik Organizasyonu', 'Kreatif Atölye', 'Sanat Terapisi', 'Kolaj Sanatı', 'Mixed Media', 'Sanat Projesi Yönetimi']],
            ['id' => 142, 'code' => 'graphic_design', 'name' => 'Grafik Tasarım', 'category_id' => 8, 'description' => 'Logo, kurumsal kimlik, grafik', 'emoji' => '🖼️', 'color' => 'purple', 'keywords' => 'grafik,tasarım,logo,kimlik', 'is_subcategory' => 1, 'possible_services' => ['Logo Tasarımı', 'Kurumsal Kimlik', 'Broşür Tasarımı', 'Poster Tasarımı', 'Web Tasarımı', 'Ambalaj Tasarımı', 'Kartvizit Tasarımı', 'Banner Tasarımı', 'İllüstrasyon', 'İnfografik Tasarımı', 'Katalog Tasarımı', 'Sosyal Medya Tasarımları']],
            ['id' => 143, 'code' => 'photography', 'name' => 'Fotoğrafçılık', 'category_id' => 8, 'description' => 'Fotoğraf çekimi, düğün fotoğrafçılığı', 'emoji' => '📸', 'color' => 'purple', 'keywords' => 'fotoğraf,çekim,düğün,photography', 'is_subcategory' => 1, 'possible_services' => ['Düğün Fotoğrafçılığı', 'Portre Çekimi', 'Ürün Fotoğrafçılığı', 'Mimari Fotoğraf', 'Doğa Fotoğrafçılığı', 'Stüdyo Çekimi', 'Etkinlik Fotoğrafçılığı', 'Bebek Fotoğrafçılığı', 'Moda Fotoğrafçılığı', 'Sokak Fotoğrafçılığı', 'Fotoğraf Editleme', 'Fotoğraf Albümü']],
            ['id' => 144, 'code' => 'video_production', 'name' => 'Video Prodüksiyon', 'category_id' => 8, 'description' => 'Video çekimi, montaj, prodüksiyon', 'emoji' => '🎥', 'color' => 'purple', 'keywords' => 'video,prodüksiyon,çekim,montaj', 'is_subcategory' => 1, 'possible_services' => ['Video Çekimi', 'Video Montajı', 'Kurumsal Film', 'Reklam Filmi', 'Düğün Videosu', 'Drone Çekimi', 'Canlı Yayın', 'Video Editleme', 'Ses Kayıt', 'Müzik Video', 'Belgesel Çekimi', 'Sosyal Medya Videoları']],
            ['id' => 145, 'code' => 'interior_design', 'name' => 'İç Mimarlık', 'category_id' => 8, 'description' => 'İç mekan tasarımı, dekorasyon', 'emoji' => '🏠', 'color' => 'purple', 'keywords' => 'iç,mimarlık,tasarım,dekorasyon', 'is_subcategory' => 1, 'possible_services' => ['İç Mekan Tasarımı', 'Ev Dekorasyonu', 'Ofis Tasarımı', 'Mağaza Tasarımı', 'Mobilya Seçimi', 'Renk Danışmanlığı', 'Aydınlatma Tasarımı', 'Mekan Planlama', 'Dekorasyon Danışmanlığı', 'Feng Shui Danışmanlığı', 'Home Staging', 'Tekstil Seçimi']],
            ['id' => 146, 'code' => 'animation', 'name' => 'Animasyon', 'category_id' => 8, 'description' => '2D/3D animasyon, motion graphics', 'emoji' => '🎬', 'color' => 'purple', 'keywords' => 'animasyon,2d,3d,motion,graphics', 'is_subcategory' => 1, 'possible_services' => ['2D Animasyon', '3D Animasyon', 'Motion Graphics', 'Karakter Tasarımı', 'Stop Motion', 'Explainer Video', 'Logo Animasyonu', 'Çizgi Film', 'Whiteboard Animasyon', 'İnfografik Animasyon', 'Oyun Animasyonu', 'Reklam Animasyonu']],
            ['id' => 147, 'code' => 'music', 'name' => 'Müzik', 'category_id' => 8, 'description' => 'Müzik prodüksiyonu, ses kayıt', 'emoji' => '🎵', 'color' => 'purple', 'keywords' => 'müzik,prodüksiyon,ses,kayıt', 'is_subcategory' => 1, 'possible_services' => ['Müzik Prodüksiyonu', 'Ses Kayıt', 'Miksleme', 'Mastering', 'Müzik Aranjmanı', 'Beste Yapımı', 'Jingle Prodüksiyonu', 'Podcast Müziği', 'Albüm Yapımı', 'Demo Kayıt', 'Vokal Kayıt', 'Enstrümantal Kayıt']],
            ['id' => 148, 'code' => 'fashion', 'name' => 'Moda & Tekstil', 'category_id' => 8, 'description' => 'Moda tasarımı, tekstil', 'emoji' => '👗', 'color' => 'purple', 'keywords' => 'moda,tekstil,tasarım,fashion', 'is_subcategory' => 1, 'possible_services' => ['Moda Tasarımı', 'Kıyafet Tasarımı', 'Tekstil Tasarımı', 'Kumaş Seçimi', 'Moda Danışmanlığı', 'Kişisel Stil Danışmanlığı', 'Koleksiyon Tasarımı', 'Moda İllüstrasyonu', 'Trend Analizi', 'Moda Fotoğrafçılığı', 'Moda Defilesi', 'Kostüm Tasarımı']],
            ['id' => 149, 'code' => 'jewelry', 'name' => 'Mücevher', 'category_id' => 8, 'description' => 'Mücevher tasarımı, kuyumculuk', 'emoji' => '💎', 'color' => 'purple', 'keywords' => 'mücevher,kuyumcu,tasarım,jewelry', 'is_subcategory' => 1, 'possible_services' => ['Mücevher Tasarımı', 'Özel Takı Tasarımı', 'Yüzük Tasarımı', 'Kolye Tasarımı', 'Bilezik Tasarımı', 'Küpe Tasarımı', 'Mücevher Tamiri', 'Antika Mücevher Restorasyonu', 'Değerli Taş Seçimi', 'Nişan Yüzüğü', 'Alyans Tasarımı', 'Mücevher Değerlendirme']],
            ['id' => 150, 'code' => 'crafts', 'name' => 'El Sanatları', 'category_id' => 8, 'description' => 'El yapımı ürünler, zanaat', 'emoji' => '🧵', 'color' => 'purple', 'keywords' => 'el,sanatları,zanaat,handmade', 'is_subcategory' => 1, 'possible_services' => ['El Yapımı Ürünler', 'Handmade Takı', 'Örgü & Dantel', 'Ahşap İşçiliği', 'Seramik & Çömlek', 'Cam Sanatı', 'Deri İşçiliği', 'Kaligrafi', 'Ebru Sanatı', 'Filografi', 'Decoupage', 'Makrome']],
            
            // SPOR & WELLNESS Alt Sektörleri (ID 161-180)
            ['id' => 161, 'code' => 'sports', 'name' => 'Spor', 'category_id' => 9, 'description' => 'Genel spor hizmetleri', 'emoji' => '⚽', 'color' => 'green', 'keywords' => 'spor,fitness,antrenman,sports', 'is_subcategory' => 1, 'possible_services' => ['Spor Eğitimi', 'Antrenman', 'Spor Danışmanlığı', 'Beslenme Planı', 'Performans Analizi', 'Spor Fizyoterapisi', 'Takım Antrenmanları', 'Bireysel Antrenman', 'Spor Psikolog', 'Spor Masajı', 'Kondisyon Antrenmanı', 'Spor Rehberliği']],
            ['id' => 162, 'code' => 'fitness', 'name' => 'Fitness', 'category_id' => 9, 'description' => 'Fitness salonu, spor salonu', 'emoji' => '🏋️', 'color' => 'green', 'keywords' => 'fitness,spor,salonu,gym', 'is_subcategory' => 1, 'possible_services' => ['Fitness Antrenmanı', 'Grup Dersleri', 'Kilo Verme Programı', 'Kas Geliştirme', 'Kardio Antrenmanı', 'Functional Training', 'CrossFit', 'HIIT', 'Zumba', 'Step', 'Body Pump', 'Personal Training']],
            ['id' => 163, 'code' => 'yoga', 'name' => 'Yoga & Pilates', 'category_id' => 9, 'description' => 'Yoga dersleri, pilates', 'emoji' => '🧘', 'color' => 'green', 'keywords' => 'yoga,pilates,ders,wellness', 'is_subcategory' => 1, 'possible_services' => ['Hatha Yoga', 'Vinyasa Yoga', 'Ashtanga Yoga', 'Yin Yoga', 'Hot Yoga', 'Pilates Mat', 'Pilates Reformer', 'Meditasyon', 'Nefes Çalışması', 'Esneklik Antrenmanı', 'Mindfulness', 'Stres Azaltma']],
            ['id' => 164, 'code' => 'personal_training', 'name' => 'Kişisel Antrenörlük', 'category_id' => 9, 'description' => 'Kişisel antrenör, özel ders', 'emoji' => '🏃', 'color' => 'green', 'keywords' => 'kişisel,antrenör,özel,ders', 'is_subcategory' => 1, 'possible_services' => ['Kişisel Program', 'Birebir Antrenman', 'Beslenme Danışmanlığı', 'Vücut Analizi', 'Hedef Belirleme', 'Motivasyon Desteği', 'Home Training', 'Online Antrenman', 'Sporcu Beslenmesi', 'Recovery Programı', 'Injury Prevention', 'Lifestyle Coaching']],
            ['id' => 165, 'code' => 'swimming', 'name' => 'Yüzme', 'category_id' => 9, 'description' => 'Yüzme dersleri, havuz', 'emoji' => '🏊', 'color' => 'green', 'keywords' => 'yüzme,havuz,ders,swimming', 'is_subcategory' => 1, 'possible_services' => ['Yüzme Dersi', 'Su Güvenliği', 'Serbest Yüzme', 'Kurbaga Yüzme', 'Sirtüstü Yüzme', 'Kelebek Yüzme', 'Aqua Aerobik', 'Su Polo', 'Dalma', 'Yarış Hazırlık', 'Teknik Geliştirme', 'Su Terapisi']],
            ['id' => 166, 'code' => 'martial_arts', 'name' => 'Dövüş Sanatları', 'category_id' => 9, 'description' => 'Karate, kickbox, dövüş', 'emoji' => '🥋', 'color' => 'green', 'keywords' => 'dövüş,sanatları,karate,kickbox', 'is_subcategory' => 1, 'possible_services' => ['Karate', 'Taekwondo', 'Kickbox', 'Muay Thai', 'Boks', 'Judo', 'Jiu-Jitsu', 'Aikido', 'Kung Fu', 'MMA', 'Krav Maga', 'Savunma Sanatları']],
            ['id' => 167, 'code' => 'dance', 'name' => 'Dans', 'category_id' => 9, 'description' => 'Dans dersleri, koreografi', 'emoji' => '💃', 'color' => 'green', 'keywords' => 'dans,ders,koreografi,dance', 'is_subcategory' => 1, 'possible_services' => ['Salsa', 'Bachata', 'Tango', 'Vals', 'Hip Hop', 'Contemporary', 'Bale', 'Jazz Dance', 'Latin Dans', 'Halk Oyunları', 'Modern Dans', 'Koreografi']],
            ['id' => 168, 'code' => 'outdoor_sports', 'name' => 'Açık Hava Sporları', 'category_id' => 9, 'description' => 'Trekking, dağcılık, kamp', 'emoji' => '🏔️', 'color' => 'green', 'keywords' => 'açık,hava,sporları,trekking', 'is_subcategory' => 1, 'possible_services' => ['Trekking', 'Dağcılık', 'Kamp', 'Doğa Yürüyüşü', 'Bisiklet Turu', 'Kaya Tırmanışı', 'Rafting', 'Kayak', 'Paragliding', 'Sörf', 'Dalgıçlık', 'Orienteering']],
            ['id' => 169, 'code' => 'spa', 'name' => 'Spa & Wellness', 'category_id' => 9, 'description' => 'Spa, masaj, wellness', 'emoji' => '🧖', 'color' => 'green', 'keywords' => 'spa,masaj,wellness,rahatlama', 'is_subcategory' => 1, 'possible_services' => ['Masaj Terapisi', 'Aromaterapi', 'Hot Stone Masaj', 'Thai Masaj', 'Refleksoloji', 'Sauna', 'Buhar Banyo', 'Jakuzi', 'Cilt Bakımı', 'Anti-stress Terapi', 'Detoks Programı', 'Wellness Danışmanlık']],
            ['id' => 170, 'code' => 'sports_equipment', 'name' => 'Spor Ekipmanları', 'category_id' => 9, 'description' => 'Spor malzemeleri, ekipman', 'emoji' => '🏀', 'color' => 'green', 'keywords' => 'spor,ekipman,malzeme,equipment', 'is_subcategory' => 1, 'possible_services' => ['Spor Ekipman Satışı', 'Fitness Cihazları', 'Spor Giyim', 'Spor Ayakkabısı', 'Olta Takımı', 'Bisiklet', 'Kosu Bandı', 'Dumbbell', 'Yoga Matları', 'Spor Çantaları', 'Protein Takviyesi', 'Spor Aksesuar']],
            
            // TİCARET Alt Sektörleri (ID 181-200)
            ['id' => 181, 'code' => 'retail', 'name' => 'Perakende', 'category_id' => 4, 'description' => 'Perakende satış, mağaza', 'emoji' => '🛍️', 'color' => 'danger', 'keywords' => 'perakende,mağaza,satış,retail', 'is_subcategory' => 1, 'possible_services' => ['Mağaza Satışı', 'Müşteri Hizmetleri', 'Kasa İşlemleri', 'Stok Yönetimi', 'İade & Değişim', 'Kampanya Yönetimi', 'Mağaza Düzeni', 'Görsel Merchandising', 'Envanter Yönetimi', 'Satış Danışmanlığı', 'Kasiyer Hizmetleri', 'Mağaza Güvenliği']],
            ['id' => 182, 'code' => 'ecommerce', 'name' => 'E-ticaret', 'category_id' => 4, 'description' => 'Online satış, e-ticaret', 'emoji' => '🛒', 'color' => 'danger', 'keywords' => 'e-ticaret,online,satış,ecommerce', 'is_subcategory' => 1, 'possible_services' => ['E-ticaret Sitesi', 'Online Mağaza', 'Dijital Ödeme', 'Kargo Entegrasyonu', 'Online Müşteri Hizmetleri', 'E-İhale', 'Marketplace Satış', 'Sosyal Medya Satış', 'Mobil Uygulama', 'SEO Optimizasyonu', 'Google Ads', 'E-mail Marketing']],
            ['id' => 183, 'code' => 'wholesale', 'name' => 'Toptan Ticaret', 'category_id' => 4, 'description' => 'Toptan satış, dağıtım', 'emoji' => '📦', 'color' => 'danger', 'keywords' => 'toptan,ticaret,dağıtım,wholesale', 'is_subcategory' => 1, 'possible_services' => ['Toptan Satış', 'Dağıtım', 'Bayilik', 'Stok Yönetimi', 'Depo Hizmetleri', 'B2B Satış', 'Sipariş Yönetimi', 'Fatura & Faturalandırma', 'Kredi Yönetimi', 'Lojistik Çözümleri', 'Tedarikçi Yönetimi', 'Fiyat Yönetimi']],
            ['id' => 184, 'code' => 'import_export', 'name' => 'İthalat & İhracat', 'category_id' => 4, 'description' => 'Dış ticaret, ithalat, ihracat', 'emoji' => '🚢', 'color' => 'danger', 'keywords' => 'ithalat,ihracat,dış,ticaret', 'is_subcategory' => 1, 'possible_services' => ['İthalat İşlemleri', 'İhracat İşlemleri', 'Gümrük Danışmanlığı', 'Dış Ticaret Danışmanlığı', 'Nakliye Organizasyonu', 'Belge Hazırlama', 'Sigorta İşlemleri', 'Doviz İşlemleri', 'Tedarikçi Bulma', 'Müşteri Bulma', 'Fuar Organizasyonu', 'Ticari Misyon']],
            ['id' => 185, 'code' => 'logistics', 'name' => 'Lojistik', 'category_id' => 4, 'description' => 'Kargo, nakliye, lojistik', 'emoji' => '🚚', 'color' => 'danger', 'keywords' => 'lojistik,kargo,nakliye,logistics', 'is_subcategory' => 1, 'possible_services' => ['Kargo Hizmetleri', 'Nakliye', 'Depolama', 'Dağıtım', 'Express Kargo', 'Uluslararası Kargo', 'E-ticaret Lojistiği', '3PL Hizmetleri', 'Supply Chain Yönetimi', 'Envanter Yönetimi', 'Takip Sistemi', 'Same Day Delivery']],
            ['id' => 186, 'code' => 'marketplace', 'name' => 'Marketplace', 'category_id' => 4, 'description' => 'Online pazaryeri, platform', 'emoji' => '🏪', 'color' => 'danger', 'keywords' => 'marketplace,pazaryeri,platform', 'is_subcategory' => 1, 'possible_services' => ['Marketplace Yönetimi', 'Satıcı Entegrasyonu', 'Online Pazaryeri', 'Platform Hizmetleri', 'Ödeme Sistemi', 'Komisyon Yönetimi', 'Müşteri Desteği', 'Satıcı Paneli', 'Sipariş Yönetimi', 'Analytics', 'Marketing Araçları', 'Güvenlik Sistemi']],
            ['id' => 187, 'code' => 'dropshipping', 'name' => 'Dropshipping', 'category_id' => 4, 'description' => 'Dropshipping iş modeli', 'emoji' => '📤', 'color' => 'danger', 'keywords' => 'dropshipping,iş,modeli,stoksuz', 'is_subcategory' => 1, 'possible_services' => ['Dropshipping Başlama', 'Tedarikçi Bulma', 'Ürün Araştırması', 'Stoksuz Satış', 'E-ticaret Entegrasyonu', 'Sipariş Otomasyonu', 'Kargo Yönetimi', 'Müşteri Hizmetleri', 'Kar Marjı Hesaplama', 'Trend Analizi', 'Pazarlama Stratejisi', 'Platform Danışmanlığı']],
            ['id' => 188, 'code' => 'affiliate', 'name' => 'Affiliate Marketing', 'category_id' => 4, 'description' => 'Affiliate pazarlama, komisyon', 'emoji' => '🤝', 'color' => 'danger', 'keywords' => 'affiliate,pazarlama,komisyon', 'is_subcategory' => 1, 'possible_services' => ['Affiliate Program Yönetimi', 'Komisyon Sistemi', 'Partner Bulma', 'Link Yönetimi', 'Performance Takip', 'Affiliate Recruitment', 'Ödeme Yönetimi', 'Tracking Sistemi', 'Rapor ve Analiz', 'Affiliate Eğitimi', 'Program Stratejisi', 'Fraud Protection']],
            ['id' => 189, 'code' => 'b2b', 'name' => 'B2B Hizmetleri', 'category_id' => 4, 'description' => 'İşletmeler arası ticaret', 'emoji' => '🏢', 'color' => 'danger', 'keywords' => 'b2b,işletme,ticaret,business', 'is_subcategory' => 1, 'possible_services' => ['B2B Satış', 'Kurumsal Çözümler', 'B2B E-ticaret', 'Toptan Satış', 'Kurumsal Müşteri Yönetimi', 'B2B Pazarlama', 'Lead Generation', 'CRM Yönetimi', 'B2B Consulting', 'Kurumsal Anlaşmalar', 'Volume Pricing', 'Enterprise Sales']],
            ['id' => 190, 'code' => 'b2c', 'name' => 'B2C Hizmetleri', 'category_id' => 4, 'description' => 'İşletme müşteri ticareti', 'emoji' => '👥', 'color' => 'danger', 'keywords' => 'b2c,müşteri,ticaret,consumer', 'is_subcategory' => 1, 'possible_services' => ['Perakende Satış', 'Müşteri Deneyimi', 'Consumer Marketing', 'Müşteri Hizmetleri', 'CRM', 'Loyalty Program', 'Customer Support', 'Social Commerce', 'Personalization', 'Customer Journey', 'Retention Strategy', 'Consumer Analytics']],
            
            // ÖZEL TÜRK SEKTÖRLER (ID 201-220)
            ['id' => 201, 'code' => 'berber', 'name' => 'Berber', 'category_id' => 14, 'description' => 'Berberlık, erkek kuaförü', 'emoji' => '✂️', 'color' => 'rose', 'keywords' => 'berber,kuaför,saç,erkek', 'is_subcategory' => 1, 'possible_services' => ['Saç Kesimi', 'Saç Yıkama', 'Saç Şekillendirme', 'Sakal Tıraşı', 'Bıyık Kesimi', 'Saç Boyama', 'Saç Makyajı', 'Saç Bakımı', 'Saç Masajı', 'Saç Wax Uygulaması', 'Kayzer Tıraşı', 'Ücretsiz Çay Kahve']],
            ['id' => 202, 'code' => 'kuafor', 'name' => 'Kuaför', 'category_id' => 14, 'description' => 'Kadın kuaförü, saç bakım', 'emoji' => '💇', 'color' => 'rose', 'keywords' => 'kuaför,saç,bakım,kadın', 'is_subcategory' => 1, 'possible_services' => ['Saç Kesimi', 'Saç Boyama', 'Saç Perma', 'Saç Düzleştirme', 'Saç Fön', 'Saç Şekillendirme', 'Saç Bakımı', 'Saç Masajı', 'Saç Toplama', 'Saç Röfle', 'Saç Extensions', 'Gelin Saçı', 'Saç Kaynağı', 'Saç Makyajı', 'Saç Spa', 'Saç Keratin']],
            ['id' => 203, 'code' => 'gelinlik', 'name' => 'Gelinlik', 'category_id' => 14, 'description' => 'Gelinlik, düğün kıyafeti', 'emoji' => '👰', 'color' => 'rose', 'keywords' => 'gelinlik,düğün,kıyafet,wedding', 'is_subcategory' => 1, 'possible_services' => ['Gelinlik Tasarımı', 'Gelinlik Dikim', 'Gelinlik Ölçü Alma', 'Gelinlik Prova', 'Gelinlik Değişimi', 'Gelinlik Temizleme', 'Düğün Konsepti', 'Gelinlik Aksesuarları', 'Düğün Çiçekçiliği', 'Düğün Fotoğrafçılığı', 'Nikah Kıyafetleri', 'Damatlık Danışmanlığı', 'Düğün Organizasyonu', 'Gelinlik Kiralama', 'Özel Tasarım Gelinlik', 'Gelinlik Veil ve Tüller']],
            ['id' => 204, 'code' => 'ayakkabi', 'name' => 'Ayakkabı', 'category_id' => 14, 'description' => 'Ayakkabı satış, tamiri', 'emoji' => '👠', 'color' => 'rose', 'keywords' => 'ayakkabı,satış,tamir,shoe', 'is_subcategory' => 1, 'possible_services' => ['Ayakkabı Satışı', 'Ayakkabı Tamiri', 'Ayakkabı Boyama', 'Ayakkabı Temizleme', 'Ayakkabı Ölçü', 'Özel Tasarım Ayakkabı', 'Ayakkabı Yenileme', 'Ayakkabı Modifikasyonu', 'Ayakkabı Parlatma', 'Ayakkabı Bakımı', 'Ayakkabı Aksesuar', 'Ayakkabı Danışmanlığı']],
            ['id' => 205, 'code' => 'terzi', 'name' => 'Terzi', 'category_id' => 14, 'description' => 'Terzillik, kıyafet dikim', 'emoji' => '🧵', 'color' => 'rose', 'keywords' => 'terzi,kıyafet,dikim,tailor', 'is_subcategory' => 1, 'possible_services' => ['Kıyafet Dikim', 'Kıyafet Değişimi', 'Kıyafet Onarımı', 'Ölçü Alma', 'Prova', 'Kıyafet Daraltma', 'Kıyafet Uzatma', 'Fermuarlık', 'Düğme Dikme', 'Kıyafet Tasarımı', 'Kıyafet Yenileme', 'Özel Tasarım Kıyafet', 'Kıyafet Danışmanlığı', 'Kumaş Seçimi', 'Kıyafet Kopya', 'Kıyafet Restorasyonu']],
            ['id' => 206, 'code' => 'mobilyaci', 'name' => 'Mobilyacı', 'category_id' => 13, 'description' => 'Mobilya üretimi, satışı', 'emoji' => '🛋️', 'color' => 'blue', 'keywords' => 'mobilya,üretim,satış,furniture', 'is_subcategory' => 1, 'possible_services' => ['Mobilya Üretimi', 'Mobilya Satışı', 'Mobilya Tamiri', 'Mobilya Restorasyonu', 'Özel Tasarım Mobilya', 'Mobilya Montajı', 'Mobilya Boyama', 'Mobilya Vernikleme', 'Mobilya Döşeme', 'Mobilya Danışmanlığı', 'Mobilya Nakliye', 'Mobilya Bakımı', 'Antika Mobilya', 'Mobilya Yenileme', 'Mobilya Modifikasyonu', 'Mobilya Tasarımı']],
            ['id' => 207, 'code' => 'halici', 'name' => 'Halıcı', 'category_id' => 13, 'description' => 'Halı satışı, temizleme', 'emoji' => '🪟', 'color' => 'blue', 'keywords' => 'halı,satış,temizleme,carpet', 'is_subcategory' => 1, 'possible_services' => ['Halı Satışı', 'Halı Temizleme', 'Halı Yıkama', 'Halı Onarımı', 'Halı Restorasyonu', 'Antika Halı', 'El Dokuma Halı', 'Halı Danışmanlığı', 'Halı Değerlendirme', 'Halı Nakliye', 'Halı Serme', 'Halı Koruma', 'Halı Bakımı', 'Özel Tasarım Halı', 'Halı Kiralama', 'Halı Ekspertiz']],
            ['id' => 208, 'code' => 'elektrikci', 'name' => 'Elektrikçi', 'category_id' => 18, 'description' => 'Elektrik tesisatı, onarım', 'emoji' => '⚡', 'color' => 'secondary', 'keywords' => 'elektrik,tesisat,onarım,electric', 'is_subcategory' => 1, 'possible_services' => ['Elektrik Tesisatı', 'Elektrik Onarımı', 'Elektrik Kontrol', 'Elektrik Bakımı', 'Elektrik Panosu', 'Elektrik Güvenliği', 'Elektrik Ölçümü', 'Elektrik Danışmanlığı', 'Elektrik Projesi', 'Elektrik Malzeme', 'Elektrik Montajı', 'Elektrik Arıza', 'Elektrik Sertifikası', 'Elektrik Denetimi', 'Elektrik Yenileme', 'Elektrik Optimizasyonu']],
            ['id' => 209, 'code' => 'tesisatci', 'name' => 'Tesisatçı', 'category_id' => 18, 'description' => 'Su, doğalgaz tesisatı', 'emoji' => '🔧', 'color' => 'secondary', 'keywords' => 'tesisat,su,doğalgaz,plumbing', 'is_subcategory' => 1, 'possible_services' => ['Su Tesisatı', 'Doğalgaz Tesisatı', 'Tesisat Onarımı', 'Tesisat Bakımı', 'Tesisat Kontrol', 'Tesisat Arıza', 'Tesisat Danışmanlığı', 'Tesisat Projesi', 'Tesisat Malzeme', 'Tesisat Montajı', 'Tesisat Yenileme', 'Tesisat Temizleme', 'Tesisat Sertifikası', 'Tesisat Denetimi', 'Tesisat Optimizasyonu', 'Tesisat Güvenliği']],
            ['id' => 210, 'code' => 'boyaci', 'name' => 'Boyacı', 'category_id' => 18, 'description' => 'Boya, badana hizmetleri', 'emoji' => '🎨', 'color' => 'secondary', 'keywords' => 'boya,badana,hizmet,paint', 'is_subcategory' => 1, 'possible_services' => ['Duvar Boyama', 'Tavan Boyama', 'Kapı Boyama', 'Pencere Boyama', 'Badana', 'Boya Danışmanlığı', 'Boya Renk Seçimi', 'Boya Malzeme', 'Boya Hazırlığı', 'Boya Bakımı', 'Boya Temizleme', 'Boya Onarımı', 'Dekoratif Boya', 'Özel Boya', 'Boya Projesi', 'Boya Yenileme']],
            
            // MODERN SEKTÖRLER (ID 221-250)
            ['id' => 221, 'code' => 'podcast', 'name' => 'Podcast', 'category_id' => 8, 'description' => 'Podcast üretimi, ses içeriği', 'emoji' => '🎙️', 'color' => 'purple', 'keywords' => 'podcast,ses,içerik,audio', 'is_subcategory' => 1, 'possible_services' => ['Podcast Üretimi', 'Ses Kaydi', 'Podcast Montajı', 'Podcast Yayıncılık', 'Ses Editörlüğü', 'Podcast Pazarlama', 'Sesli Kitap', 'Radyo Programı', 'Voice Over', 'Jenerik Müziği', 'Podcast Danışmanlık', 'Ses Branding']],
            ['id' => 222, 'code' => 'streaming', 'name' => 'Streaming', 'category_id' => 8, 'description' => 'Canlı yayın, streaming', 'emoji' => '📺', 'color' => 'purple', 'keywords' => 'streaming,canlı,yayın,live', 'is_subcategory' => 1, 'possible_services' => ['Canlı Yayın', 'Twitch Streaming', 'YouTube Live', 'Facebook Live', 'Instagram Live', 'Gaming Stream', 'IRL Streaming', 'Podcast Live', 'Webinar', 'Online Etkinlik', 'Stream Setup', 'Content Creation']],
            ['id' => 223, 'code' => 'gaming', 'name' => 'Gaming', 'category_id' => 1, 'description' => 'Oyun geliştirme, e-spor', 'emoji' => '🎮', 'color' => 'primary', 'keywords' => 'gaming,oyun,e-spor,game', 'is_subcategory' => 1, 'possible_services' => ['Oyun Geliştirme', 'Mobil Oyun', 'Web Oyunu', 'PC Oyunu', 'E-spor', 'Game Design', 'Oyun Testi', 'Oyun Pazarlama', 'Oyun Yayıncılık', 'Oyun Stream', 'Oyun Coaching', 'Oyun Turnuva']],
            ['id' => 224, 'code' => 'nft', 'name' => 'NFT', 'category_id' => 1, 'description' => 'NFT marketplace, dijital sanat', 'emoji' => '🖼️', 'color' => 'primary', 'keywords' => 'nft,dijital,sanat,marketplace', 'is_subcategory' => 1, 'possible_services' => ['NFT Oluşturma', 'NFT Marketplace', 'Dijital Sanat', 'NFT Pazarlama', 'Smart Contract', 'NFT Koleksiyonu', 'Crypto Art', 'NFT Trading', 'NFT Consulting', 'Blockchain Sanat', 'NFT Yatırım', 'Digital Collectibles']],
            ['id' => 225, 'code' => 'metaverse', 'name' => 'Metaverse', 'category_id' => 1, 'description' => 'Metaverse, sanal dünya', 'emoji' => '🌐', 'color' => 'primary', 'keywords' => 'metaverse,sanal,dünya,virtual', 'is_subcategory' => 1, 'possible_services' => ['Metaverse Geliştirme', 'Sanal Dünya', 'Virtual Real Estate', 'Avatar Creation', 'Virtual Events', '3D Modeling', 'Metaverse Marketing', 'Virtual Commerce', 'Digital Twin', 'Virtual Meetings', 'Metaverse Consulting', 'VR Experience']],
            ['id' => 226, 'code' => 'vr_ar', 'name' => 'VR & AR', 'category_id' => 1, 'description' => 'Sanal gerçeklik, artırılmış gerçeklik', 'emoji' => '🥽', 'color' => 'primary', 'keywords' => 'vr,ar,sanal,gerçeklik', 'is_subcategory' => 1, 'possible_services' => ['VR Uygulama Geliştirme', 'AR Uygulama Geliştirme', 'Sanal Gerçeklik', 'Artırılmış Gerçeklik', '3D Modelleme', 'VR Eğitim', 'AR Marketing', 'VR Gaming', '360 Video', 'VR Mimari', 'AR Filtre', 'Mixed Reality']],
            ['id' => 227, 'code' => 'drone', 'name' => 'Drone', 'category_id' => 1, 'description' => 'Drone hizmetleri, havacılık', 'emoji' => '🚁', 'color' => 'primary', 'keywords' => 'drone,havacılık,hizmet,aerial', 'is_subcategory' => 1, 'possible_services' => ['Drone Çekimi', 'Hava Fotoğrafçılığı', 'Drone Video', 'Harita Çıkarma', 'Tarım Dronu', 'Güvenlik Dronu', 'Kargo Dronu', 'Drone Eğitimi', 'Drone Tamiri', 'Drone Kiralama', 'Drone Pilotluğu', 'Ağru Fotoğraflar']],
            ['id' => 228, 'code' => 'robotics', 'name' => 'Robotik', 'category_id' => 1, 'description' => 'Robotik sistemler, otomasyon', 'emoji' => '🤖', 'color' => 'primary', 'keywords' => 'robotik,sistem,otomasyon,robot', 'is_subcategory' => 1, 'possible_services' => ['Robot Geliştirme', 'Otomasyon Sistemleri', 'Endüstriyel Robot', 'Hizmet Robotu', 'AI Robot', 'Robot Programlama', 'Robotik Danışmanlık', 'Robot Bakımı', 'Robotik Eğitim', 'Otonom Sistemler', 'Robot Entegrasyonu', 'Robotik Çözümler']],
            ['id' => 229, 'code' => 'renewable_energy', 'name' => 'Yenilenebilir Enerji', 'category_id' => 17, 'description' => 'Güneş, rüzgar enerjisi', 'emoji' => '🌞', 'color' => 'gray', 'keywords' => 'yenilenebilir,enerji,güneş,rüzgar', 'is_subcategory' => 1, 'possible_services' => ['Güneş Enerjisi', 'Rüzgar Enerjisi', 'Hidroelektrik', 'Biomass Enerji', 'Jeotermal Enerji', 'Enerji Depolama', 'Enerji Verimliliği', 'Enerji Danışmanlığı', 'Enerji Yönetimi', 'Yeqil Enerji', 'Enerji Projesi', 'Karbon Ayak İzi']],
            ['id' => 230, 'code' => 'sustainability', 'name' => 'Sürdürülebilirlik', 'category_id' => 17, 'description' => 'Çevre, sürdürülebilirlik', 'emoji' => '🌱', 'color' => 'gray', 'keywords' => 'sürdürülebilirlik,çevre,yeşil', 'is_subcategory' => 1, 'possible_services' => ['Çevre Danışmanlığı', 'Sürdürülebilirlik Raporu', 'Yeşil Sertifika', 'Atik Yönetimi', 'Karbon Neffel', 'Çevre Denetimi', 'Ekolojik Ayak İzi', 'Yeşil Binalar', 'Çevre Projesi', 'Organic Sertifikasyon', 'Circular Economy', 'ESG Danışmanlık']],
        ];
        
        $addedCount = 0;
        foreach ($sectors as $sector) {
            try {
                DB::table('ai_profile_sectors')->insert([
                    'id' => $sector['id'],
                    'code' => $sector['code'],
                    'name' => $sector['name'],
                    'category_id' => $sector['category_id'],
                    'description' => $sector['description'],
                    'emoji' => $sector['emoji'],
                    'icon' => null,
                    'color' => $sector['color'],
                    'keywords' => $sector['keywords'],
                    'is_subcategory' => $sector['is_subcategory'],
                    'possible_services' => isset($sector['possible_services']) ? json_encode($sector['possible_services']) : null,
                    'is_active' => 1,
                    'sort_order' => $sector['id'],
                    'created_at' => now(),
                    'updated_at' => now()
                ]);
                $addedCount++;
                
                if ($addedCount % 20 == 0) {
                    echo "📊 {$addedCount} sektör eklendi...\n";
                }
            } catch (\Exception $e) {
                echo "⚠️ Sektör ID {$sector['id']} atlandı: " . $e->getMessage() . "\n";
                continue;
            }
        }
        
        echo "✅ Kapsamlı sektör listesi: {$addedCount} sektör başarıyla yüklendi!\n";
        
        // Final check - toplam sektör sayısını göster
        $totalSectors = DB::table('ai_profile_sectors')->count();
        echo "📊 Veritabanında toplam {$totalSectors} sektör var\n";
    }
}