@extends('themes.blank.layouts.app')
{{-- V4: LANDING PAGE VARIANT --}}
@section('module_content')
<div class="min-h-screen bg-white dark:bg-gray-900">
@php
$currentLocale=app()->getLocale();$title=$item->getTranslated('title',$currentLocale);$shortDescription=$item->getTranslated('short_description',$currentLocale);$longDescription=$item->getTranslated('long_description',$currentLocale);$moduleSlugService=app(\App\Services\ModuleSlugService::class);$indexSlug=$moduleSlugService->getMultiLangSlug('Shop','index',$currentLocale);$defaultLocale=get_tenant_default_locale();$localePrefix=$currentLocale!==$defaultLocale?'/'.$currentLocale:'';$shopIndexUrl=$localePrefix.'/'.$indexSlug;$featuredImage=$item->getFirstMedia('featured_image');$galleryImages=$item->getMedia('gallery');$resolveLocalized=static function($data)use($currentLocale,$defaultLocale){if(!is_array($data))return $data;return $data[$currentLocale]??$data[$defaultLocale]??$data['en']??reset($data);};$useCases=[];if(is_array($item->use_cases)){$resolvedUseCases=$resolveLocalized($item->use_cases);if(is_array($resolvedUseCases))$useCases=array_values(array_filter($resolvedUseCases));}$siblingVariants=$siblingVariants??collect();$parentProduct=$parentProduct??null;
@endphp
@if($parentProduct)<div class="bg-blue-600 text-white py-3 text-center"><a href="{{ \Modules\Shop\App\Http\Controllers\Front\ShopController::resolveProductUrl($parentProduct,$currentLocale) }}" class="hover:underline"><i class="fa-solid fa-arrow-left mr-2"></i>Ana Ürün: {{ $parentProduct->getTranslated('title',$currentLocale) }}</a></div>@endif
<section class="relative bg-gradient-to-br from-purple-900 via-blue-700 to-blue-600 text-white py-24"><div class="container mx-auto px-4 text-center"><span class="inline-block px-6 py-2 bg-purple-500 text-white text-sm font-bold rounded-full mb-6">VARYANT ÜRÜN</span><h1 class="text-5xl md:text-6xl font-extrabold mb-6">{{ $title }}</h1>@if($shortDescription)<p class="text-xl mb-12 max-w-2xl mx-auto">{{ $shortDescription }}</p>@endif<div class="flex flex-col sm:flex-row gap-6 justify-center"><a href="#contact" class="bg-white text-blue-900 px-10 py-4 rounded-full text-lg font-bold hover:bg-gray-100">TEKLİF AL</a><a href="tel:02167553555" class="border-3 border-white text-white px-10 py-4 rounded-full text-lg font-bold hover:bg-white hover:text-blue-900">ARA</a></div></div></section>
@if($galleryImages->count()>0)<section class="py-16"><div class="container mx-auto px-4"><div class="grid grid-cols-2 md:grid-cols-4 gap-4">@foreach($galleryImages as $image)<a href="{{ $image->getUrl() }}" class="glightbox block rounded-xl overflow-hidden" data-gallery="v"><img src="{{ $image->hasGeneratedConversion('medium')?$image->getUrl('medium'):$image->getUrl() }}" alt="" class="w-full h-48 object-cover"></a>@endforeach</div></div></section>@endif
@if($longDescription)<section class="py-16 bg-gray-50 dark:bg-gray-800"><div class="container mx-auto px-4 max-w-4xl"><div class="prose max-w-none dark:prose-invert">@parsewidgets($longDescription)</div></div></section>@endif
@if(!empty($useCases))<section class="py-16"><div class="container mx-auto px-4"><h2 class="text-4xl font-bold text-center mb-12">Kullanım Alanları</h2><div class="grid md:grid-cols-2 gap-6">@foreach($useCases as $case)<div class="flex gap-4 p-6 bg-blue-50 dark:bg-blue-900/20 rounded-xl"><i class="fa-solid fa-check text-blue-600 text-xl mt-1"></i><span class="text-gray-700 dark:text-gray-300">{{ $case }}</span></div>@endforeach</div></div></section>@endif
@if($siblingVariants->count()>0)<section class="py-16 bg-gray-50 dark:bg-gray-800"><div class="container mx-auto px-4"><h2 class="text-4xl font-bold text-center mb-12">Diğer Varyantlar</h2><div class="grid md:grid-cols-4 gap-6">@foreach($siblingVariants as $variant)@php $variantTitle=$variant->getTranslated('title',$currentLocale)??$variant->sku;$variantUrl=\Modules\Shop\App\Http\Controllers\Front\ShopController::resolveProductUrl($variant,$currentLocale);$variantImage=$variant->getFirstMedia('featured_image');@endphp<a href="{{ $variantUrl }}" class="block border-2 hover:border-blue-500 rounded-xl p-4">@if($variantImage)<img src="{{ $variantImage->hasGeneratedConversion('thumb')?$variantImage->getUrl('thumb'):$variantImage->getUrl() }}" alt="{{ $variantTitle }}" class="w-full h-32 object-cover rounded mb-3">@endif<h3 class="font-bold">{{ $variantTitle }}</h3></a>@endforeach</div></div></section>@endif
<section id="contact" class="py-16 bg-gradient-to-r from-blue-600 to-purple-600 text-white"><div class="container mx-auto px-4"><h2 class="text-4xl font-bold text-center mb-8">Teklif Al</h2><form action="{{ route('shop.quote.submit') }}" method="POST" class="max-w-2xl mx-auto space-y-6 bg-white/10 backdrop-blur-lg rounded-2xl p-8">@csrf<input type="hidden" name="product_id" value="{{ $item->product_id }}"><input type="hidden" name="product_title" value="{{ $title }}"><div class="grid md:grid-cols-2 gap-6"><input type="text" name="name" required placeholder="Ad Soyad *" class="px-4 py-3 bg-white/20 border-0 rounded-lg text-white placeholder-white/70"><input type="email" name="email" required placeholder="E-posta *" class="px-4 py-3 bg-white/20 border-0 rounded-lg text-white placeholder-white/70"></div><input type="tel" name="phone" required placeholder="Telefon *" class="w-full px-4 py-3 bg-white/20 border-0 rounded-lg text-white placeholder-white/70"><textarea name="message" rows="4" placeholder="Mesajınız" class="w-full px-4 py-3 bg-white/20 border-0 rounded-lg text-white placeholder-white/70"></textarea><button type="submit" class="w-full bg-white text-blue-900 font-bold py-4 rounded-lg text-lg">TEKLİF İSTE</button></form></div></section>
</div>
@endsection
