@extends('themes.blank.layouts.app')
{{-- V5: DARK PREMIUM VARIANT --}}
@section('module_content')
<div class="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-blue-900 text-white">
@php
$currentLocale=app()->getLocale();$title=$item->getTranslated('title',$currentLocale);$shortDescription=$item->getTranslated('short_description',$currentLocale);$longDescription=$item->getTranslated('long_description',$currentLocale);$featuredImage=$item->getFirstMedia('featured_image');$galleryImages=$item->getMedia('gallery');$resolveLocalized=static function($data)use($currentLocale){if(!is_array($data))return $data;return $data[$currentLocale]??$data['tr']??$data['en']??reset($data);};$useCases=[];if(is_array($item->use_cases)){$resolvedUseCases=$resolveLocalized($item->use_cases);if(is_array($resolvedUseCases))$useCases=array_values(array_filter($resolvedUseCases));}$siblingVariants=$siblingVariants??collect();$parentProduct=$parentProduct??null;
@endphp
@if($parentProduct)<div class="backdrop-blur-xl bg-blue-600/30 border-b border-blue-500/50 py-4 text-center"><a href="{{ \Modules\Shop\App\Http\Controllers\Front\ShopController::resolveProductUrl($parentProduct,$currentLocale) }}" class="hover:underline"><i class="fa-solid fa-arrow-left mr-2"></i>Ana Ürün: {{ $parentProduct->getTranslated('title',$currentLocale) }}</a></div>@endif
<section class="py-24"><div class="max-w-7xl mx-auto px-6"><div class="grid lg:grid-cols-2 gap-12 items-center">@if($featuredImage)<div><div class="relative"><div class="absolute inset-0 bg-gradient-to-r from-purple-500 to-blue-500 blur-3xl opacity-30"></div><img src="{{ $featuredImage->hasGeneratedConversion('large')?$featuredImage->getUrl('large'):$featuredImage->getUrl() }}" alt="{{ $title }}" class="relative w-full rounded-3xl border border-white/10 shadow-2xl shadow-purple-500/20"></div></div>@endif<div><div class="inline-block px-5 py-2 bg-gradient-to-r from-purple-500 to-pink-500 text-white text-sm font-bold rounded-full mb-6">VARYANT</div><h1 class="text-5xl font-black mb-6 bg-gradient-to-r from-white to-purple-300 bg-clip-text text-transparent">{{ $title }}</h1>@if($shortDescription)<p class="text-xl text-gray-300 mb-8">{{ $shortDescription }}</p>@endif<div class="flex gap-4"><a href="#contact" class="px-10 py-4 bg-gradient-to-r from-purple-600 to-blue-600 rounded-2xl font-bold shadow-lg shadow-purple-500/50">TEKLİF AL</a><a href="tel:02167553555" class="px-10 py-4 backdrop-blur-xl bg-white/10 border-2 border-white/20 rounded-2xl font-bold">ARA</a></div></div></div></div></section>
@if($galleryImages->count()>0)<section class="py-16"><div class="max-w-7xl mx-auto px-6"><div class="grid grid-cols-2 md:grid-cols-4 gap-4">@foreach($galleryImages as $image)<a href="{{ $image->getUrl() }}" class="glightbox block rounded-2xl overflow-hidden border border-white/10 hover:border-purple-500/50" data-gallery="vg"><img src="{{ $image->hasGeneratedConversion('medium')?$image->getUrl('medium'):$image->getUrl() }}" alt="" class="w-full h-48 object-cover"></a>@endforeach</div></div></section>@endif
@if($longDescription)<section class="py-16"><div class="max-w-4xl mx-auto px-6"><div class="backdrop-blur-xl bg-white/5 border border-white/10 rounded-3xl p-8"><div class="prose prose-invert max-w-none">@parsewidgets($longDescription)</div></div></div></section>@endif
@if(!empty($useCases))<section class="py-16"><div class="max-w-7xl mx-auto px-6"><h2 class="text-4xl font-bold text-center mb-12">Kullanım Alanları</h2><div class="grid md:grid-cols-2 gap-6">@foreach($useCases as $case)<div class="flex gap-4 p-6 backdrop-blur-xl bg-white/5 border border-white/10 rounded-2xl hover:border-blue-500/50 transition-all"><i class="fa-solid fa-check text-blue-400 text-xl mt-1"></i><span>{{ $case }}</span></div>@endforeach</div></div></section>@endif
@if($siblingVariants->count()>0)<section class="py-16"><div class="max-w-7xl mx-auto px-6"><h2 class="text-4xl font-bold text-center mb-12">Diğer Varyantlar</h2><div class="grid md:grid-cols-4 gap-6">@foreach($siblingVariants as $variant)@php $variantTitle=$variant->getTranslated('title',$currentLocale)??$variant->sku;$variantUrl=\Modules\Shop\App\Http\Controllers\Front\ShopController::resolveProductUrl($variant,$currentLocale);$variantImage=$variant->getFirstMedia('featured_image');@endphp<a href="{{ $variantUrl }}" class="block backdrop-blur-xl bg-white/5 border border-white/10 hover:border-purple-500/50 rounded-2xl p-4">@if($variantImage)<img src="{{ $variantImage->hasGeneratedConversion('thumb')?$variantImage->getUrl('thumb'):$variantImage->getUrl() }}" alt="{{ $variantTitle }}" class="w-full h-32 object-cover rounded-xl mb-3">@endif<h3 class="font-bold">{{ $variantTitle }}</h3></a>@endforeach</div></div></section>@endif
<section id="contact" class="py-16"><div class="max-w-4xl mx-auto px-6"><h2 class="text-4xl font-bold text-center mb-12 bg-gradient-to-r from-white to-purple-300 bg-clip-text text-transparent">Teklif Al</h2><form action="{{ route('shop.quote.submit') }}" method="POST" class="space-y-6 backdrop-blur-xl bg-white/10 border border-white/20 rounded-3xl p-8">@csrf<input type="hidden" name="product_id" value="{{ $item->product_id }}"><input type="hidden" name="product_title" value="{{ $title }}"><div class="grid md:grid-cols-2 gap-6"><input type="text" name="name" required placeholder="Ad Soyad *" class="px-5 py-4 bg-white/10 border border-white/20 rounded-xl text-white placeholder-white/60"><input type="email" name="email" required placeholder="E-posta *" class="px-5 py-4 bg-white/10 border border-white/20 rounded-xl text-white placeholder-white/60"></div><input type="tel" name="phone" required placeholder="Telefon *" class="w-full px-5 py-4 bg-white/10 border border-white/20 rounded-xl text-white placeholder-white/60"><textarea name="message" rows="4" placeholder="Mesajınız" class="w-full px-5 py-4 bg-white/10 border border-white/20 rounded-xl text-white placeholder-white/60"></textarea><button type="submit" class="w-full px-10 py-5 bg-gradient-to-r from-purple-600 to-blue-600 rounded-xl font-bold shadow-lg shadow-purple-500/50">TEKLİF İSTE</button></form></div></section>
</div>
@endsection
