-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Anamakine: localhost:3306
-- Üretim Zamanı: 08 Oca 2026, 20:10:07
-- Sunucu sürümü: 10.11.15-MariaDB
-- PHP Sürümü: 8.4.16

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `muzibu_com_tr_yedek`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `muzibu_radios`
--

CREATE TABLE `muzibu_radios` (
  `id` int(11) NOT NULL,
  `title_tr` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `thumb` varchar(255) DEFAULT NULL,
  `created` datetime NOT NULL DEFAULT current_timestamp(),
  `meta_title` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `meta_keywords` varchar(500) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `meta_description` varchar(500) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Tablo döküm verisi `muzibu_radios`
--

INSERT INTO `muzibu_radios` (`id`, `title_tr`, `slug`, `thumb`, `created`, `meta_title`, `meta_keywords`, `meta_description`) VALUES
(2, 'Radio Blues', 'radio-blues', 'SECTOR_V5COiW-ucWtIp-tn7y8S-JVI0BY-Znmo8j-xN1jMo.jpg', '2025-05-16 21:24:22', 'Radyo Blues | Telifsiz Radyo', 'blues müzik yayını, telifsiz blues playlist, işletme müzik yayını, blues radyo, yasal müzik yayını, bar müzikleri telifsiz, Muzibu Radyo, blues background music, royalty-free blues music, soulful music stream, acoustic blues radio, blues lounge playlist', 'Radio Blues ile işletmenizde ruhu olan telifsiz müzik yayını yapın. Yasal blues playlistleriyle samimi, nostaljik ve etkileyici bir atmosfer oluşturun.'),
(3, 'Radio Rock', 'radio-rock', 'SECTOR_qNW7GE-lo98WM-zgi1P6-Xn3M29-TJCW80-D7NLIS.jpeg', '2025-05-16 21:25:16', 'Radio Rock | Telifsiz Rock Müzik | Muzibu Radyo', 'telifsiz rock müzik, işletme için müzik yayını, lisanslı rock playlist, yasal müzik yayını, Muzibu Radyo, royalty-free rock music, rock bar playlist, licensed business music, telif hakkı olmayan müzik, cafe için rock müzik, mağaza yayını telifsiz, enerjik müzik yayını', 'Radio Rock ile işletmenizde telifsiz ve lisanslı rock müzik yayını yapın. Bar, kafe ve mağazalarda enerjik, yasal playlistlerle güçlü bir atmosfer oluşturun.'),
(5, 'Radio Reggae', 'radio-reggae', 'SECTOR_CoTmMV-5eqjY9-qtbCt0-ofLk48-CJ9FRM-2nr8kz.jpeg', '2025-05-21 18:34:40', 'Radio Reggae | Telifsiz Reggae Müzik Yayını | Muzibu Radyo', 'işletme için müzik yayını, telifsiz reggae müzik, lisanslı reggae playlist, yasal müzik hizmeti, Muzibu Radyo, royalty-free reggae music, licensed business music, reggae cafe playlist, tropical shop music, telif hakkı olmayan müzik, işletmeler için yasal müzik, bar için telifsiz yayın, telifsiz müzik', 'Radio Reggae ile işletmenizde telifsiz ve lisanslı reggae müzik yayını yapın. Kafe, restoran, mağaza ve otellerde pozitif ruhlu, yasal ve özgür bir müzik atmosferi oluşturun.'),
(6, 'Radio R&amp;B Soul', 'radio-rb-soul', 'SECTOR_yRM6TW-yVzlPc-pfrLyS-LlZcwP-y7ori7-VgBYhc.jpeg', '2025-05-21 19:38:40', 'Radio R&amp;B Soul | Telifsiz Radyo', 'r&amp;b müzik yayını, soul playlist telifsiz, yasal müzik yayını, işletme müzik çözümleri, Muzibu Radyo, royalty-free soul music, chill r&amp;b radio, smooth vibes playlist, cafe soul music, lounge r&amp;b stream, relaxing r&amp;b soul, acoustic soul radio', 'Radio R&amp;B Soul ile işletmenizde yumuşak R&amp;B ve soul tınılarıyla telifsiz müzik yayını yapın. Yasal playlistlerle duygulu, sıcak ve akıcı bir atmosfer oluşturun.'),
(7, 'Radio Classical', 'radio-classical', 'SECTOR_CHQqnk-hbIkBR-2hczbX-K6K5Zi-aUuVxM-Qra189.jpg', '2025-05-21 20:28:11', 'Radio Classical | Telifsiz Klasik Müzik Yayını | Muzibu Radyo', 'klasik müzik yayını, telifsiz klasik playlist, yasal müzik yayını, işletme müzik çözümleri, Muzibu Radyo, classical music radio, royalty-free classical music, ambient classical stream, violin and piano playlist, relaxing classical background, elegant store music, cafe classical playlist', 'Radio Classical ile işletmenize klasik müziğin zarafetini taşıyın. Telifsiz ve yasal klasik müzik playlistleriyle huzurlu, entelektüel ve etkileyici bir atmosfer oluşturun.'),
(8, 'Radio House', 'radio-house', 'SECTOR_EgSkF1-QfT16H-Er9cSJ-6T7RZD-BkSar2-SoXdBY.jpg', '2025-05-21 21:39:03', 'Radio House | Telifsiz House, Chill ve Deep House Yayını | Muzibu Radyo', 'house müzik yayını, telifsiz chill house, deep house playlist, yasal müzik yayını, restoran bar müziği, Muzibu Radyo, royalty-free house music, chill deep stream, organic house vibes, lounge house playlist, cafe house music, upbeat electronic radio', 'Radio House ile işletmenizde modern, ritmik ve telifsiz house müzik yayını yapın. Chill, deep ve organic house playlistlerle yasal ve enerjik bir atmosfer oluşturun.'),
(9, 'Radio Jazz', 'radio-jazz', 'SECTOR_IX8Hc1-ftPcJJ-jkN5dl-8nnWIf-Dn5DJh-UvuX9T.jpeg', '2025-05-21 21:43:38', 'Radio Jazz | Telifsiz Radyo', 'jazz müzik yayını, telifsiz caz playlist, yasal müzik yayını, swing cafe müzikleri, Muzibu Radyo, royalty-free jazz music, smooth jazz stream, chill jazz playlist, jazz bar ambience, lounge jazz vibes, acoustic jazz radio, elegant cafe music', 'Radio Jazz ile işletmenize telifsiz caz müzik yayını katın. Yasal swing, chill ve klasik jazz playlistleriyle zarif, samimi ve akıcı bir atmosfer oluşturun.'),
(11, 'Radio Funk', 'radio-funk', 'SECTOR_VyGVf6-7N1raS-0eu13i-BrlZCu-dMaIjz-MVOwJD.jpeg', '2025-05-21 22:06:42', 'Radio Funk | Telifsiz Funk, Groove ve R&amp;B Yayını | İşletmenize Ritmi Taşıyın', 'funk müzik yayını, telifsiz groove müzik, bar için müzik, telifsiz r&amp;b yayını, Muzibu radyo, funk playlist, royalty-free funk, groovy beats stream, retro funk vibes, nu funk playlist, işletme için müzik yayını, r&amp;b lounge', 'Radio Funk ile bar, pub ve mağazalarda telifsiz funk müzik yayını yapın. Groove ritimleri, retro funk ve modern R&amp;B sound&#039;larıyla ortamınızı canlandırın.'),
(12, 'Radio Country', 'radio-country', 'SECTOR_nzY443-Tn3L7r-KfJiKK-QGdInf-yGNPyZ-GfnNTC.jpg', '2025-05-21 22:51:31', 'Radio Country | Telifsiz Country ve Akustik Müzik Yayını | Muzibu Radyo', 'country müzik yayını, akustik country playlist, telifsiz country müzikleri, işletme müzik yayını, Muzibu Radyo, yasal country yayını, royalty-free country music, acoustic folk radio, americana playlist stream, cafe country vibes, southern acoustic music, chill cowboy ambience', 'Radio Country ile işletmenize sıcak, samimi ve akustik country müzikler taşıyın. Telifsiz ve yasal playlistlerle doğal, sade ve keyifli bir atmosfer oluşturun.'),
(13, 'Radio Slow Brew', 'radio-slow-brew', 'SECTOR_O8ijTD-1VV2di-L6Wvu7-TdoXP9-tTQ1ng-IQ79xY.jpeg', '2025-05-22 18:44:34', 'Radio Slow Brew | Telifsiz Akustik ve Chill Müzik Yayını | Telifsiz Radyo', 'telifsiz müzik, işletme için telifsiz müzik, akustik müzik yayını, telifsiz radyo, lisanslı müzik yayını, Muzibu Radyo, royalty-free acoustic music, coffee shop playlist, chill cafe müziği, lo-fi playlist işletme, relaxing background music, yasal müzik hizmeti', 'Radio Slow Brew ile kahve dükkanları ve mağazalarda telifsiz müzik yayını yapın. Akustik, lo-fi ve chill playlistlerle yasal, sakin ve huzurlu bir atmosfer oluşturun.'),
(14, 'Radio Medium Roast', 'radio-medium-roast', 'SECTOR_yej7sy-7K9Vpr-ka2iAr-XWTDHM-GdmJFS-8tKToK.jpeg', '2025-05-22 19:00:17', 'Radio Medium Roast | Telifsiz Chill Pop, Soul ve Jazz Yayını | Muzibu Radyo', 'kahve dükkanı müzik yayını, telifsiz soul playlist, chill pop müzik, yasal cafe müziği, Muzibu Radyo, royalty-free coffee shop music, medium roast vibes, acoustic chill stream, pop jazz playlist, soul R&amp;B radio, blues rock background, chillhop cafe music', 'Radio Medium Roast ile kahve dükkanları ve butik mekanlarda dengeli, telifsiz müzik yayını yapın. Chill pop, soul, blues rock ve jazz playlistlerle samimi ve yasal bir atmosfer oluşturun.'),
(15, 'Radio Double Shot', 'double-shot', 'SECTOR_ra3jli-nrPPBp-rUtywP-gHKU3w-16yARM-4HymTJ.jpeg', '2025-05-22 19:10:16', 'Radio Double Shot | Telifsiz Pop, Funk ve Latin Müzik Yayını | Muzibu Radyo', 'pop müzik yayını, nu funk playlist, latin pop müzikleri, telifsiz dans müziği, yasal müzik yayını, işletme playlistleri, Muzibu Radyo, royalty-free dance music, upbeat latin stream, electro pop radio, energetic music playlist, spanish dance pop', 'Radio Double Shot ile işletmenize enerjik ve modern bir atmosfer katın. Telifsiz electro pop, nu funk ve Latin playlistlerle yasal, ritmik ve eğlenceli müzik yayını yapın.'),
(16, 'Radio House Blend', 'radio-house-blend', 'SECTOR_WHxSs0-59hZG6-mtx3rm-qP9KSJ-A9ycNx-ufMi6C.jpeg', '2025-05-22 19:25:55', 'Radio House Blend | Telifsiz Chill, Deep ve Afro House Yayını | Muzibu Radyo', 'house müzik yayını, chill house playlist, afro house radyo, telifsiz deep house, yasal müzik yayını, Muzibu Radyo, royalty-free house music, organic house stream, lounge bar playlist, jazz house vibes, soft house music, minimal house flow', 'Radio House Blend ile işletmenizde minimal, deep, chill ve afro house karışımı telifsiz müzik yayını yapın. Yasal playlistlerle ritmik, akıcı ve modern bir atmosfer oluşturun.'),
(17, 'Barista Rap', 'radio-barista', 'SECTOR_2JxJyg-gwSS24-eSLEJk-kxKMdk-fVqnWc-nlJTix.jpg', '2025-05-22 19:40:35', 'Barista Rap Radyo | Telifsiz Radyo', 'barista rap radyo, telifsiz rap müzik, lo-fi radyo yayını, işletme müzik yayını, kahve dükkanı playlist, rap cafe müzikleri, yasal müzik yayını, chill rap playlist, Muzibu Radyo, royalty-free rap music, lo-fi hip hop radio, coffee shop background music', 'Barista Rap Radyo ile kahve dükkanları, cafeler ve modern mekanlar için özel hazırlanmış telifsiz rap ve lo-fi müzik yayını. Yasal, ritmik ve dinamik atmosfer yaratın!'),
(18, 'Radio Lo-Fi Beans', 'radio-lo-fi-beans', 'SECTOR_Qh02Bb-f2FrLL-V5n7mB-zolt9p-FQUeZd-r0gxrD.jpg', '2025-05-22 23:36:32', 'Radio Lo-Fi Beans | Telifsiz Lo-Fi Chill ve Coffee Shop Müzik Yayını | Muzibu Radyo', 'lo-fi müzik yayını, telifsiz kahve dükkanı müziği, lo-fi playlist, yasal chill müzik, Muzibu Radyo, royalty-free lo-fi music, coffee shop background music, chill beats stream, cozy cafe music, study music playlist, mellow lofi radio, relaxing cafe vibes', 'Radio Lo-Fi Beans ile kahve dükkanınızda ya da çalışma alanınızda telifsiz lo-fi müzik yayını yapın. Yasal playlistlerle rahat, odaklanmaya uygun ve samimi bir atmosfer oluşturun.'),
(19, 'Radio Café Latino', 'radio-cafe-latino', 'SECTOR_zS4uT7-ExTUdl-1e7rbX-KTMC3p-4nPzZi-1Fx2cQ.jpg', '2025-05-22 23:50:36', 'Radio Café Latino | Telifsiz Latin Müzik Yayını | Muzibu Radyo', 'latin cafe müzikleri, telifsiz latin playlist, cafe latino radyo, işletme müzik yayını, yasal müzik yayını, Muzibu Radyo, latin jazz playlist, royalty-free latin music, salsa cafe music, bossa nova chill, cafe ambience latino, tropical background music', 'Radio Café Latino ile kafenizde Latin ritimleriyle dolu telifsiz müzik yayını yapın. Salsa, bossa ve Latin jazz playlistleriyle enerjik, samimi bir atmosfer oluşturun.'),
(20, 'Radio Decaf Dreams', 'radio-decaf-dreams', 'SECTOR_5dbmvM-xRoqzk-GDbPRY-NzuOT4-kneu65-sHig9j.jpeg', '2025-05-22 23:57:36', 'Radio Decaf Dreams | Telifsiz Sakin Klasik ve Ambient Müzikler | Muzibu Radyo', 'sakin müzik yayını, ambient klasik playlist, telifsiz piyano müzik, Muzibu Radyo yayını, yasal müzik çalma, lo-fi klasik karışımı, royalty-free classical ambient, decaf playlist radio, soft piano background, cozy cafe music, elegant music stream, relaxing instrumental vibes', 'Radio Decaf Dreams ile işletmenize klasik piyano, ambient ve lo-fi tınılarla huzur taşıyın. Telifsiz ve yasal playlistlerle rafine, sakin ve dingin bir ortam yaratın.'),
(22, 'Radio Chill', 'radio-chill', 'SECTOR_MwZGwz-paVhJ3-Z0ZHol-ZIaLoP-UxDOTG-YziNiQ.jpg', '2025-05-23 02:42:40', 'Radio Chill | Telifsiz Radyo', 'chill müzik yayını, lo-fi radyo playlist, telifsiz cafe müziği, yasal müzik yayını, işletme müzik çözümleri, Muzibu Radyo, royalty-free chill music, lo-fi background stream, downtempo playlist, ambient chill mix, cafe chill radio, relaxing beats playlist', 'Radio Chill ile işletmenizde sakin ve modern bir atmosfer oluşturun. Telifsiz chill, lo-fi ve downtempo müziklerle yasal ve kesintisiz yayın keyfi sunun.'),
(23, 'Radio Cafe Acoustic', 'radio-cafe-acoustic', 'SECTOR_OLEd9D-tuBo3W-ph0myF-NkDsip-KEMOJj-RmFA86.jpg', '2025-05-23 23:07:09', 'Radio Cafe Acoustic | Telifsiz Akustik Cafe Yayını | Muzibu Radyo', 'cafe akustik müzik, telifsiz cafe playlist, akustik radyo yayını, yasal müzik yayını, kafe müzikleri, Muzibu Radyo, acoustic cafe music, royalty-free acoustic playlist, coffee shop background music, relaxing acoustic stream, cafe ambience music, acoustic chill playlist', 'Radio Cafe Acoustic ile kafe ortamınızda doğal ve huzurlu bir atmosfer kurun. Telifsiz ve yasal akustik playlistlerle müşterilerinize keyifli bir müzik deneyimi sunun.'),
(25, 'Radio Daily Pop', 'radio-daily-pop', 'SECTOR_4fQNM2-etUm5W-snCRf7-VMVLoD-z0XMEb-pRe9GP.jpg', '2025-05-23 23:16:07', 'Radio Daily Pop | Telifsiz Pop ve Günlük Hit Müzikler | Muzibu Radyo', 'pop müzik yayını, telifsiz pop playlist, günlük hit müzikler, yasal müzik yayını, işletme müzik çözümleri, Muzibu Radyo, royalty-free pop music, daily pop stream, cafe pop vibes, upbeat playlist radio, modern pop background, energetic retail music', 'Radio Daily Pop ile işletmenizde gün boyu enerjik, telifsiz pop müzikler çalsın. Yasal playlistlerle dinamik, neşeli ve modern bir atmosfer oluşturun.'),
(27, 'Radio Table No.9', 'radio-table-no9', 'SECTOR_Oi7LhC-iIVpBz-z3DrYG-GhaT5U-DNpv26-TPG5wJ.jpeg', '2025-05-24 22:15:13', 'Radio Table No.9 | Telifsiz Jazz ve Lounge Müzik Yayını | Telifsiz Radyo', 'telifsiz müzik, işletme için telifsiz müzik, jazz müzik yayını, lounge playlist telifsiz, telifsiz Radyo, royalty-free jazz music, elegant restaurant music, table no.9 vibes, yasal müzik yayını, cafe için telifsiz müzik, lisanslı müzik hizmeti, fine dining playlist', 'Radio Table No.9 ile işletmenizde sofistike ve telifsiz müzik yayını yapın. Jazz, lounge ve akustik playlistlerle yasal, zarif ve sakin bir atmosfer oluşturun.'),
(28, 'Radio Flow House', 'radio-flow-house', 'SECTOR_EAuKZ9-hUuNB0-WMyYNS-FlG5iZ-CekW3Y-BkbjsC.jpeg', '2025-05-25 21:14:18', 'Radio Flow House | Telifsiz Minimal House Müzik | Chill &amp; Organic Sound', 'minimal house müzik yayını, deep house lounge radyo, organik house playlist, restoran bar müzik yayını, telifsiz chill müzik, Muzibu lounge house, royalty-free house music, flow radio station, stylish restaurant music, relaxing electronic beats, slow bpm lounge, cool mood stream', 'Radio Flow House ile mekanınıza akıcı, telifsiz ve chill house tınıları katın. Minimal, deep ve organik house müzikle modern bir atmosfer yaratın. Lisanslı yayınla fark yaratın.'),
(29, 'Radio Bella Table', 'radio-belle-table', 'SECTOR_Rqski5-ooFA7Y-eQCHmu-TFrLva-Wy9mzM-n9pa5m.jpg', '2025-05-27 11:39:01', 'Radio Bella Table | Telifsiz Fransız Lounge ve Jazz Yayını | Muzibu', 'fransız lounge müzik, telifsiz jazz yayını, gypsy jazz playlist, french swing playlist, işletme müzik yayını, akustik lounge müzik, yasal müzik yayını, Muzibu Radyo, french background music, royalty-free french jazz, elegant cafe music, belle table ambience', 'Radio Belle Table ile şık restoranlar ve cafeler için Fransız tarzı telifsiz müzik yayını yapın. Gypsy jazz, swing ve acoustic lounge playlistleriyle sofistike bir atmosfer oluşturun.'),
(30, 'Radio Velvet Hour', 'radio-velvet-hour', 'SECTOR_UM5U55-ZfyFal-irvUbl-XeCWWK-4CjVqI-WVqRcY.jpeg', '2025-05-27 12:22:03', 'Radio Velvet Hour | Telifsiz Akşam Lounge Müzik Yayını | Telifsiz Radyo', 'telifsiz müzik, işletme için telifsiz müzik, lounge müzik yayını, akşam müziği, telifsiz Radyo, royalty-free evening music, velvet hour vibes, wine bar playlist, lisanslı lounge müzik, yasal müzik yayını, chill soul playlist, fine dining müziği', 'Radio Velvet Hour ile işletmenizde gün batımından geceye geçişte yumuşak ve telifsiz müzik yayını yapın. Lüks lounge, soul ve chill ezgilerle yasal ve zarif bir atmosfer oluşturun.'),
(31, 'Radio Nu Groove', 'radio-nu-groove', 'SECTOR_dbrQWI-3CEZBU-TgeaIE-4yUThz-t0Fe82-7WTyWp.jpeg', '2025-05-27 13:51:40', 'Radio Nu Groove | Telifsiz Funk, Nu-Disco ve Groove Yayını | Muzibu Radyo', 'groove müzik yayını, telifsiz funk playlist, nu disco radyo, yasal müzik yayını, Muzibu Radyo, royalty-free groove music, nu funk stream, upbeat disco playlist, stylish bar music, energetic cafe playlist, retro modern music, chill funk vibes', 'Radio Nu Groove ile işletmenize ritim ve stil katın. Telifsiz funk, nu-disco ve groove playlistlerle yasal, enerjik ve modern bir müzik atmosferi oluşturun.'),
(32, 'Radio Low Sun', 'radio-low-sun', 'SECTOR_LL2KF2-bDx6Lo-AQ1Epn-Itgzzh-eVkq9N-BjITfX.jpeg', '2025-05-27 17:31:30', 'Radio Low Sun | Telifsiz Chill House ve Sunset Müzik Yayını | Muzibu Radyo', 'sunset müzik yayını, chill house playlist, telifsiz lounge müzik, Muzibu Radyo, gün batımı müziği, yasal müzik yayını, royalty-free sunset music, chill house stream, beach lounge playlist, relaxing electronic music, low sun vibes, cafe sunset music', 'Radio Low Sun ile işletmenizde gün batımı atmosferi yaratın. Telifsiz chill house, lounge ve sunset playlistlerle yasal ve huzurlu müzik yayını sunun.'),
(33, 'Radio Electric Velvet', 'radio-electric-velvet', 'SECTOR_mmfDL1-1SkT8h-wVocQn-w9qoY5-zOoR3i-OmpRL1.jpeg', '2025-05-27 21:37:15', 'Radio Electric Velvet | Telifsiz Indie Dance ve Nu Disco Yayını | Muzibu Radyo', 'indie dance yayını, nu disco playlist, telifsiz funk müzikleri, yasal müzik yayını, Muzibu Radyo, upbeat dance stream, royalty-free nu disco, electro funk playlist, retro modern music, cafe dance vibes, stylish bar music, nu funk radio', 'Radio Electric Velvet ile işletmenizde dans, nu funk ve indie tınılarıyla telifsiz müzik yayını yapın. Yasal playlistlerle enerjik, stil sahibi ve retro-modern bir atmosfer oluşturun.'),
(36, 'Radio Midnight Ritual', 'radio-midnight-ritual-', 'SECTOR_QMHeqm-urjY08-NTvQli-UmmMjR-BX6nts-drgi0S.jpeg', '2025-05-28 13:54:03', 'Radio Midnight Ritual | Lo-Fi, Ambient ve Mistik Telifsiz Müzik | Muzibu Radyo', 'mistik müzik yayını, gece radyo yayını, lo-fi bar müziği, ambient playlist, telifsiz fon müziği, royalty-free ambient music, midnight ritual playlist, dark chill radio, lo-fi spiritual stream, moody background music, meditation cafe playlist, night lounge ambiance', 'Radio Midnight Ritual ile geceye eşlik eden lo-fi, ambient ve karanlık tınılarla mistik bir atmosfer yaratın. Telifsiz ve yasal müzik yayınıyla işletmenize derinlik katın.'),
(37, 'Radio Noir &amp; Neat', 'radio-noir-neat', 'SECTOR_RitTx6-wRry8z-Sjxhii-FrZXNJ-HE7ySn-W9nAFg.jpeg', '2025-05-28 13:59:25', 'Radio Noir &amp; Neat | Telifsiz Jazz, Blues ve Lounge Müzik Yayını | Muzibu Radyo', 'gece müzik yayını, telifsiz jazz playlist, blues bar müziği, yasal lounge müzik, Muzibu Radyo, royalty-free noir music, dark lounge stream, whiskey bar music, blues jazz ambience, night mood playlist, elegant bar radio, smooth background music', 'Radio Noir &amp; Neat ile bar, lounge ve gece mekanlarında telifsiz müzik yayını yapın. Jazz, blues ve chill lounge playlistlerle yasal, zarif ve karakterli bir atmosfer oluşturun.'),
(38, 'Radio Cosmic Funk', 'radio-cosmic-funk-barpub', 'SECTOR_0Nu1gl-dTyYw6-ZXzPmP-hDkYSx-ASBDtv-gR8q5B.jpeg', '2025-05-28 14:17:12', 'Radio Cosmic Funk | Telifsiz Funk, Groove ve Space Vibes | Muzibu Radyo', 'funk müzik yayını, telifsiz groove playlist, cosmic funk radyo, yasal müzik yayını, işletme müzik çözümleri, Muzibu Radyo, royalty-free funk music, space groove stream, retro funk playlist, disco funk radio, nu funk background, energetic cafe music', 'Radio Cosmic Funk ile işletmenizde funk, groove ve uzay esintili telifsiz müzik yayını yapın. Yasal ve enerjik playlistlerle eğlenceli, özgün ve retro-modern bir atmosfer yaratın.'),
(39, 'Radio Velvet Smoke', 'radio-velvet-smoke-barpub', 'SECTOR_encpth-QQSEQM-GxOcSB-wK6wMk-lxxhua-J1gW8N.jpeg', '2025-05-28 14:43:30', 'Radio Velvet Smoke | Telifsiz Jazz &amp; Lounge Müzik Yayını', 'telifsiz müzik, işletme için telifsiz müzik, jazz müzik yayını, cigar lounge müziği, cafe Radyo, royalty-free jazz lounge, velvet smoke playlist, bar için telifsiz müzik, yasal müzik yayını, dark lounge vibes, lisanslı müzik hizmeti, blues bar playlist', 'Radio Velvet Smoke ile işletmenizde derin, zarif ve telifsiz müzik yayını yapın. Jazz, blues ve dark lounge playlistlerle yasal, stil sahibi ve dingin bir atmosfer oluşturun.'),
(41, 'Radio Bossa Lounge', 'radio-bossa-lounge-barpub', 'SECTOR_eIC3gm-hXQBsJ-V8ZCuX-JC12Ro-LZvMhB-eOGdmm.jpg', '2025-05-28 15:24:46', 'Radio Bossa Lounge | Telifsiz Bossa Nova ve Lounge Yayını | Muzibu Radyo', 'bossa nova müzik yayını, telifsiz latin lounge, işletme müzik yayını, yasal bossa nova playlist, restoran müziği, Muzibu Radyo, bossa lounge radyo, relaxing latin jazz, royalty-free bossa nova, brazilian lounge music, tropical background music, chill bossa stream', 'Radio Bossa Lounge ile işletmenize Latin esintili, huzurlu ve telifsiz bir müzik deneyimi sunun. Bossa nova ve lounge tarzında yasal playlistlerle zarif bir atmosfer yaratın.'),
(42, 'Radio LoGlow', 'radio-loglow-barpub', 'SECTOR_PYYUiT-P8HbMr-yvtiok-D4rBZ5-ytRU0U-V2I4bO.jpeg', '2025-05-28 15:41:20', 'Radio LoGlow | Lo-Fi &amp; Chill Vibes ile Telifsiz Arka Plan Müzikleri', 'lofi müzik yayını, chill telifsiz müzik, lo-glow playlist, Muzibu Radyo, genç odaklı müzik yayını, telifsiz modern müzik, lo-fi coffee music, royalty-free chill beats, lofi café background music, lo-fi radio stream, urban chill vibes, lo-fi relaxing music', 'Radio LoGlow, kafeler, butik mağazalar ve modern çalışma alanları için lo-fi ve chill telifsiz müzik yayınları sunar. Sakin, cool ve etkileyici ambiyans burada.'),
(43, 'Radio Slowburn Rock', 'radio-slowburn-rock-barpub', 'SECTOR_6YVVoY-0ZLJhE-yAwlSz-dGefS5-NNth0P-F4f6aR.jpeg', '2025-05-28 16:05:01', 'Radio Slowburn Rock | Telifsiz Rock Müzik Yayını | Telifsiz Radyo', 'telifsiz müzik, işletme için telifsiz müzik, rock müzik yayını, yasal müzik yayını, Muzibu Radyo, royalty-free rock music, soft rock playlist, acoustic rock stream, slowburn rock vibes, cafe rock müziği, lisanslı müzik hizmeti, chill rock background', 'Radio Slowburn Rock ile işletmenizde telifsiz rock müzik yayını yapın. Akustik rock, blues rock ve soft rock playlistlerle yasal, dengeli ve karakterli bir atmosfer oluşturun.'),
(44, 'Radio Bourbon Blues', 'radio-bourbon-blues-barpub', 'SECTOR_xXQnjH-2zxWVx-6O8BZT-7Cthxb-mmrdKG-QoKg0y.jpg', '2025-05-28 17:41:14', 'Radio Bourbon Blues | Telifsiz Bar &amp; Pub Blues Yayını | Muzibu', 'bourbon blues radyo, bar blues playlist, telifsiz pub müzikleri, delta blues yayını, british blues playlist, yasal müzik yayını, Muzibu Radyo, blues bar ambience, royalty-free blues radio, whiskey bar music, moody blues playlist, soulful bar music', 'Radio Bourbon Blues ile bar, pub ve gece atmosferlerine özel telifsiz blues müzik yayını yapın. Yasal ve özgün playlistlerle karakterli ve duygulu bir ortam kurun.'),
(45, 'Radio Closing Time', 'radio-closing-time-barpub', 'SECTOR_KtZh06-wf200m-dfKKEb-dd2RAy-ghzNuk-HpU5DA.jpeg', '2025-05-28 18:37:09', 'Radio Closing Time | Telifsiz Gün Sonu ve Kapanış Müzikleri | Muzibu Radyo', 'kapanış müzik yayını, gün sonu playlist, telifsiz yavaş müzik, yasal müzik yayını, closing time müzikleri, Muzibu Radyo, end of day music, royalty-free closing playlist, slow cafe music, last hour ambience, mellow music stream, chill night playlist', 'Radio Closing Time ile gün sonuna özel yasal ve telifsiz müzik yayını yapın. Kapanış saatlerinde işletmenize dinginlik, huzur ve anlam katan playlistlerle fark yaratın.'),
(46, 'Radio Drip Soul', 'radio-drip-soul-coffee-shop', 'SECTOR_5DhRPs-drdgb5-1pYBwi-IbJ2BL-GH7mfK-xm2yLZ.jpeg', '2025-05-28 23:53:01', 'Radio Drip Soul | Telifsiz R&amp;B, Soul ve Groove Yayını | Muzibu Radyo', 'soul müzik yayını, telifsiz R&amp;B playlist, groove chill müzik, yasal müzik yayını, işletme müzik çözümleri, Muzibu Radyo, royalty-free soul music, drip soul stream, mellow groove radio, lo-fi R&amp;B playlist, smooth background music, cafe soul vibes', 'Radio Drip Soul ile işletmenizde yumuşak R&amp;B, soul ve groove ritimleriyle telifsiz müzik yayını yapın. Yasal playlistlerle stil, duygu ve akıcılık dolu bir atmosfer oluşturun.'),
(49, 'Radio Warm Strings', 'radio-warm-strings-coffeeshop', 'SECTOR_3e1UQH-bu6DRu-LXiw8I-0eYFt0-nwwg9J-KMJPWP.jpeg', '2025-05-29 03:14:01', 'Radio Warm Strings | Telifsiz Akustik Müzik Yayını | Telifsiz Radyo', 'telifsiz müzik, işletme için telifsiz müzik, akustik müzik yayını, yasal müzik yayını, restoran Radyo, royalty-free acoustic music, warm strings playlist, cafe müzik yayını, mağaza için müzik, lisanslı müzik hizmeti, relaxing background music, chill acoustic stream', 'Radio Warm Strings ile işletmenizde huzurlu ve telifsiz akustik müzik yayını yapın. Gitar, yaylılar ve yumuşak melodilerle yasal, samimi ve doğal bir atmosfer oluşturun.'),
(50, 'Radio Sundown', 'radio-sundown-coffee-shop', 'SECTOR_aT8UwH-cpWsG8-Gi1QcZ-M9qiCB-TO6XU1-vLK0xf.jpg', '2025-05-29 10:33:59', 'Radio Sundown | Telifsiz Chill ve Lounge Müzik Yayını | Telifsiz Radyo', 'telifsiz müzik, işletme için telifsiz müzik, chill müzik yayını, lounge playlist telifsiz, Muzibu Radyo, royalty-free chill music, sundown cafe music, sunset lounge vibes, yasal müzik yayını, beach club playlist, lisanslı müzik hizmeti, gün batımı müziği', 'Radio Sundown ile işletmenizde gün batımına eşlik eden telifsiz müzik yayını yapın. Chill, lounge ve soft house playlistlerle yasal, huzurlu ve akıcı bir atmosfer oluşturun.'),
(51, 'Radio Maison Menu', 'radio-maison-menu', 'SECTOR_hoo9Y9-tqMyCi-xgYbRN-qNl1cN-0WM04q-pVvrzR.jpeg', '2025-05-29 12:08:44', 'Radio Maison Menu | Telifsiz Fransız Lounge ve Akustik Müzik | Muzibu Radyo', 'fransız müzik yayını, fine dining müzikleri, telifsiz lounge playlist, akustik restoran müziği, Muzibu Radyo, maison menu radyo, royalty-free french lounge, elegant restaurant music, acoustic cafe playlist, french jazz stream, stylish dining ambience, soft background music', 'Radio Maison Menu ile restoranınızda zarif ve huzurlu bir atmosfer oluşturun. Telifsiz Fransız lounge, akustik ve jazz playlistlerle yasal ve şık müzik yayını yapın.'),
(52, 'Radio Shoping', 'radio-shoping', 'SECTOR_g50h0k-SgA4e7-hqDMMp-pcjUSW-IGve6E-P4P4q4.jpeg', '2025-05-29 14:08:14', 'Radio Shoping | Telifsiz Mağaza Müzik Yayını | Telifsiz Radyo', 'telifsiz müzik, mağaza müzik yayını, işletme için telifsiz müzik, telifsiz radyo, lisanslı müzik hizmeti, Muzibu Radyo, royalty-free retail music, shop playlist telifsiz, mağaza içi müzik, upbeat store music, market müzik yayını, yasal müzik yayını', 'Radio Shoping ile mağaza ve marketlerde telifsiz müzik yayını yapın. Enerjik, lisanslı ve yasal playlistlerle işletmenize özel alışveriş atmosferi oluşturun.'),
(53, 'Radio Electronics Store', 'radio-electrocore', 'SECTOR_E72p43-yjYZ4Z-rNVJGe-w5uncp-meAzAe-mSSJ9p.jpeg', '2025-05-29 18:25:14', 'Radio Electronics Store | Telifsiz Elektronik &amp; Synthwave Müzikler | Muzibu Kurumsal Yayın', 'elektronik mağaza müziği, synthwave radyo yayını, telifsiz elektronik müzik, teknoloji mağazası playlist, Muzibu kurumsal müzik, retro future vibes, royalty-free synth music, electronic store music, background retail music, upbeat electronic stream, modern ambient store playlist, techno ambient', 'Radio Electronics Store ile mağazanızda modern, elektronik ve synthwave tınılarıyla yasal müzik yayını yapın. Telifsiz içeriklerle teknoloji odaklı mekanlara enerjik bir atmosfer katın.'),
(54, 'Radio Homeware', 'radio-homeware', 'SECTOR_4Kc5Qv-K7pQv3-Qzqof6-l10gMS-R8Wmdt-q89eAO.jpeg', '2025-05-29 19:07:57', 'Radio Homeware | Telifsiz Mağaza Müzikleri ve Akustik Yayın | Muzibu Radyo', 'mağaza müzik yayını, homeware playlist, telifsiz akustik müzik, dekorasyon mağazası müziği, Muzibu Radyo, royalty-free store music, acoustic home stream, elegant retail music, relaxing shopping playlist, ambient home decor music, soft instrumental stream, yasal müzik yayını', 'Radio Homeware ile ev dekorasyonu, tasarım mağazaları ve showroomlarda telifsiz müzik yayını yapın. Yasal, akustik ve zarif playlistlerle alışveriş deneyimini zenginleştirin.'),
(55, 'Radio  Classic Store', 'radio-classic-clothing', 'SECTOR_P4UK2V-E6ghMF-9DFXBj-LuUYxt-0Y4N33-RyIZ3E.jpeg', '2025-05-30 00:25:00', 'Radio Classic Store | Telifsiz Radyo', 'mağaza müzik yayını, butik müzikleri telifsiz, alışveriş playlist, yasal müzik yayını, işletme müzik çözümleri, Muzibu Radyo, store background music, royalty-free retail music, boutique ambience music, acoustic store playlist, chill retail radio, classic fashion music', 'Radio Classic Store ile mağaza ve butiklerde huzurlu, şık ve telifsiz müzik yayını yapın. Yasal playlistlerle alışveriş ortamınıza zarafet ve akıcılık katın.'),
(56, 'Radio Vanity', 'radio-vanity', 'SECTOR_wgsZPr-kX8xwt-LY4lYW-4z5BbX-2Aajzf-vcPNcj.jpeg', '2025-05-30 02:44:32', 'Radio Vanity | Telifsiz Zarif Müzik Yayını | Telifsiz Radyo', 'telifsiz müzik, güzellik merkezi müziği, kuaför salonu müzik yayını, lisanslı müzik yayını, Muzibu Radyo, royalty-free beauty salon music, chill beauty playlist, işletme için telifsiz müzik, yasal arka plan müziği, spa için müzik, zarif müzik yayını, telifsiz radyo', 'Radio Vanity ile güzellik salonları, kuaförler ve bakım alanlarında telifsiz müzik yayını yapın. Yasal, zarif ve rahatlatıcı playlistlerle işletmenizde modern bir atmosfer oluşturun.'),
(57, 'Radio Sports store', 'radio-sports-store', 'SECTOR_xhjMMW-4E6zHh-tPmtJw-MZrpiy-xEatyN-fdAP6p.jpeg', '2025-05-30 12:26:27', 'Radio Sports Store | Telifsiz Enerjik Müzik Yayını | Telifsiz Radyo', 'telifsiz müzik, işletme için telifsiz müzik, spor mağazası müzik yayını, yasal müzik yayını, Muzibu Radyo, royalty-free workout music, sports store playlist, motive edici müzik telifsiz, upbeat retail music, lisanslı müzik hizmeti, fitness mağaza müziği, energetic background music', 'Radio Sports Store ile spor mağazası, spor salonu ve aktif yaşam alanlarında telifsiz müzik yayını yapın. Yasal, tempolu ve motive edici playlistlerle enerjik bir atmosfer oluşturun.'),
(58, 'Radio Breakfast', 'radio-breakfast', 'SECTOR_uLzUuE-Rur2d9-AQYO1R-7RZ22x-GqeQTr-Wcbv8W.jpg', '2025-05-31 00:39:31', 'Radio Breakfast | Telifsiz Sabah ve Kahvaltı Müzikleri | Muzibu Radyo', 'sabah müzik yayını, kahvaltı müzikleri, telifsiz breakfast playlist, cafe sabah müziği, huzurlu sabah müziği, Muzibu Radyo, morning acoustic stream, royalty-free breakfast music, coffee morning playlist, chill brunch music, telifsiz sabah yayını, breakfast ambience music', 'Radio Breakfast ile kahvaltı mekanları, cafeler ve otellerde güne telifsiz ve huzurlu müzikle başlayın. Sabah saatlerine özel yasal playlistlerle keyifli bir atmosfer oluşturun.'),
(59, 'Morning Coffee Radio', 'radio-morning-coffee', 'SECTOR_1NxBbp-GOscPf-pLJ8me-5nVAFn-lQZpc5-43h7Qi.jpg', '2025-06-01 12:25:50', 'Radio Morning Coffee | Telifsiz Sabah ve Kahve Dükkanı Müzikleri | Muzibu Radyo', 'sabah müzik yayını, kahve dükkanı playlist, telifsiz sabah müziği, yasal müzik yayını, Muzibu Radyo, royalty-free morning music, coffee shop background music, acoustic chill stream, lo-fi cafe vibes, brunch playlist, relaxing morning radio, cafe ambience music', 'Radio Morning Coffee ile kahve dükkanları ve brunch mekanlarında sabah saatlerine özel telifsiz müzik yayını yapın. Yasal akustik, lo-fi ve chill playlistlerle sıcak bir atmosfer oluşturun.'),
(63, 'Radio Workout House', 'radio-workout-house', 'SECTOR_txlDNU-N56Ilh-OgPRCS-sIjTko-aTD9u6-CzjuKY.jpeg', '2025-06-03 17:05:03', 'Radio Workout House | Telifsiz Spor ve House Müzik Yayını', 'telifsiz müzik, spor salonu müzik yayını, workout playlist telifsiz, işletme için müzik, Muzibu Radyo, royalty-free workout house music, fitness için müzik yayını, yasal müzik yayını, gym music stream, house müzik telifsiz, motive edici müzik, lisanslı enerji müziği', 'Radio Workout House ile spor salonunuzda telifsiz ve tempolu house müzik yayını yapın. Yasal, motive edici ve enerjik playlistlerle işletmenizde ritmi yükseltin.'),
(64, 'Radio Daily Quietude', 'radio-daily-quietude', 'SECTOR_fSojjo-QDOF2e-t4ra1e-gDGLr5-EcbMHq-aqrXLw.jpeg', '2025-06-03 17:12:59', 'Radio Daily Quietude | Telifsiz Sakin ve Huzurlu Müzik Yayını | Muzibu Radyo', 'sakin müzik yayını, telifsiz ambient playlist, lo-fi yayını işletme, yasal müzik yayını, Muzibu Radyo, chill background music, royalty-free calm music, quiet playlist stream, peaceful cafe music, relaxing ambience radio, soft instrumental music, daily calm vibes', 'Radio Daily Quietude ile işletmenize gün boyu huzur taşıyın. Telifsiz ve yasal chill, ambient ve lo-fi playlistlerle sakin, dinlendirici bir atmosfer oluşturun.'),
(65, 'Radio Underground', 'radio-underground', 'SECTOR_J2hAMk-2DFg1G-Lzz9R4-j4Dx3T-GNjKCd-wtFFmc.jpeg', '2025-06-03 21:11:36', 'Radio Underground | Telifsiz Alternatif Müzik Yayını | Telifsiz Radyo', 'telifsiz müzik, işletme için telifsiz müzik, alternatif müzik yayını, indie playlist telifsiz, Muzibu Radyo, royalty-free underground music, experimental chill playlist, bar için telifsiz müzik, yasal müzik yayını, cool işletme müziği, lisanslı alternatif müzik, gece mekanları için müzik', 'Radio Underground ile işletmenizde alternatif, deneysel ve telifsiz müzik yayını yapın. Indie, elektronik ve düşük ışıklı mekanlara uygun yasal playlistlerle özgün bir atmosfer kurun.'),
(66, 'Radio Trainer Mood', 'radio-trainer-mood', 'SECTOR_HSV4L9-XKBOu1-yzC9Qn-oE7k6Z-8Drig9-9UJQmF.jpeg', '2025-06-03 21:26:50', 'Radio Trainer Mood | Telifsiz Spor ve Enerji Müzik Yayını | Telifsiz Radyo', 'telifsiz müzik, işletme için telifsiz müzik, spor salonu müzik yayını, yasal enerji müziği, Muzibu Radyo, royalty-free workout music, gym playlist telifsiz, trainer mood playlist, lisanslı müzik hizmeti, upbeat fitness music, motive edici müzik yayını, spor için müzik', 'Radio Trainer Mood ile spor salonu, fitness stüdyosu ve antrenman alanlarında telifsiz müzik yayını yapın. Yasal ve motive edici playlistlerle enerjik bir atmosfer oluşturun.'),
(67, 'Radio Coffee Club', 'radio-coffee-club', 'SECTOR_ptegta-jQCboc-Na93s7-2b8cVa-SOswDZ-OrdNYD.jpg', '2025-06-04 14:32:57', 'Radio Coffee Club | Telifsiz Kahve Mekânı ve Chillout Yayını | Muzibu Radyo', 'kahve dükkanı müzikleri, coffee shop playlist, telifsiz cafe müziği, yasal müzik yayını, chill coffee music, Muzibu Radyo, royalty-free coffee music, lo-fi coffee stream, coffee club ambience, acoustic coffee playlist, kitap kafe müziği, sakin kahve müziği', 'Radio Coffee Club ile kahve dükkanlarında, kitap kafe ve ortak çalışma alanlarında telifsiz müzik yayını yapın. Yasal lo-fi, chill ve akustik playlistlerle gün boyu keyifli bir atmosfer yaratın.'),
(68, 'Radio Lobby', 'radio-lobby', 'SECTOR_BUbaeu-oI6DCw-SsGPDF-OsjER2-bTbVbl-VTSjtv.jpeg', '2025-06-07 17:51:08', 'Radio Lobby | Otel Radyo', 'otel lobi müziği, telifsiz bekleme müziği, kurumsal ortam playlist, Muzibu Radyo, yasal yayın müziği, royalty-free lobby music, hotel background playlist, ambient corporate music, elegant lounge stream, business waiting room music, smooth jazz lobby radio, instrumental hotel radio', 'Radio Lobby ile otel lobileri, iş merkezleri ve bekleme alanları için telifsiz müzik yayını yapın. Şık, yasal ve akışkan playlistlerle prestijli bir atmosfer oluşturun.'),
(69, 'Radio Market', 'radio-market', 'SECTOR_b35CVW-LxJiB7-bbTMQi-lA55FY-4LT5PC-006rtz.jpeg', '2025-06-07 22:43:48', 'Radio Market | Telifsiz Radyo', 'market müzik yayını, mağaza müziği telifsiz, Muzibu Radyo, alışveriş müziği, zincir market yayını, telifsiz mağaza müzikleri, royalty-free store music, upbeat retail playlist, market ambient music, energetic shopping music, store background radio, legal retail audio', 'Radio Market ile süpermarket, mağaza ve zincir satış noktalarında telifsiz müzik yayını yapın. Enerjik, dikkat çekici ve satış odaklı playlistlerle ortamınızı canlandırın.'),
(70, 'Radio Petrol', 'radio-petrol', 'SECTOR_s3nOYS-MPt5HH-4fnxEG-FioK01-ktT6Xh-0TeiDZ.jpeg', '2025-06-07 22:48:51', 'Radio Petrol | Telifsiz Rock, Blues ve Enerjik Playlist Yayını | Muzibu Radyo', 'benzin istasyonu müziği, oto yıkama playlist, telifsiz rock yayını, yol müzik yayını, Muzibu Radyo, royalty-free road music, blues rock radio, petrol station music, energetic stream, fuel stop ambience, upbeat rock playlist, yasal işletme müziği', 'Radio Petrol ile benzin istasyonu, oto yıkama ve yol üstü mekanlarda telifsiz müzik yayını yapın. Rock, blues ve ritmik playlistlerle güçlü ve yasal bir atmosfer oluşturun.'),
(71, 'Radio Zumba', 'radio-zumba', 'SECTOR_RDUTiS-61PdBo-szK9qJ-CuFRvE-vivTHt-Rmv4ds.jpeg', '2025-06-08 17:09:17', 'Radio Zumba | Telifsiz Dans ve Fitness Müzik Yayını | Telifsiz Radyo', 'telifsiz müzik, zumba müzik yayını, işletme için telifsiz müzik, yasal dans müziği, Muzibu Radyo, royalty-free zumba music, fitness dance playlist, latin müzik telifsiz, lisanslı müzik hizmeti, spor salonu müziği, energetic workout music, telifsiz radyo', 'Radio Zumba ile dans stüdyosu, spor salonu ve etkinlik alanlarında telifsiz müzik yayını yapın. Latin ritimler, hareketli pop ve yasal playlistlerle enerjik bir atmosfer oluşturun.'),
(72, 'Radio Summer Latino', 'radio-summer-latino', 'SECTOR_3qvOQL-lP22Q5-FFoy4d-zadL0G-JyIE0R-ZJykFt.jpeg', '2025-06-08 17:13:37', 'Radio Summer Latino | Telifsiz Latin Müzik Yayını | Telifsiz Radyo', 'telifsiz müzik, işletme için telifsiz müzik, latin müzik yayını, yazlık mekan müziği, Muzibu Radyo, royalty-free latin music, summer playlist telifsiz, latin cafe vibes, bar için telifsiz müzik, beach club playlist, yasal müzik yayını, lisanslı latin müzik', 'Radio Summer Latino ile işletmenizde yaz enerjisini yükseltin. Telifsiz ve lisanslı Latin müzik playlistleriyle kafe, bar ve mağazalarda sıcak, hareketli bir atmosfer oluşturun.'),
(73, 'Radio Cardio', 'radio-cardio', 'SECTOR_5t8BjD-yaznY3-BfEqWD-eW4DQ8-7lqdIZ-bccueE.jpg', '2025-06-09 01:55:13', 'Radio Cardio | Telifsiz Spor ve Kardiyo Müzik Yayını | Muzibu Radyo', 'kardiyo müzik yayını, spor salonu playlist, telifsiz workout müzikleri, yasal müzik yayını, işletme müzik yayını, Muzibu Radyo, cardio workout music, royalty-free fitness music, gym energy playlist, high tempo background music, telifsiz spor müziği, gym motivation radio', 'Radio Cardio ile spor salonlarında veya kardiyo alanlarında enerji yükselten telifsiz müzik yayını yapın. Yasal ve tempolu playlistlerle motivasyonu zirveye taşıyın.'),
(74, 'Radio Anadolu Esintisi', 'radio-anadolu-esintisi', 'SECTOR_Kfl02i-6A9PiY-ufRNg0-7CzXzo-7Gxkif-ypt9x5.jpg', '2025-06-11 23:44:04', 'Anadolu Esintisi Radyo | Telifsiz Türk Müziği Yayını | Muzibu', 'anadolu müzikleri, telifsiz türk müziği, radyo yayını işletme, geleneksel müzik yayını, işletme radyo yayını, anadolu playlist, yasal müzik yayını, türk ezgileri radyo, Muzibu Radyo, folk music radio, royalty-free turkish music, cultural ambience playlist', 'Anadolu Esintisi Radyo ile işletmenizde geleneksel ve modern Türk müziğini yasal ve telifsiz şekilde yayınlayın. Müziğin en doğal haliyle müşterilerinize huzurlu bir atmosfer sunun.'),
(75, 'Radio Rock &amp; Roll', 'rock-roll', 'SECTOR_tafURO-UgL8WZ-bUKRO1-cdZkqh-Etxlx8-pP6QCx.jpg', '2025-06-14 16:52:33', 'Radio Rock &amp; Roll | Telifsiz Rock\'n Roll Müzik | Muzibu Radyo', 'telifsiz rock\'n roll müzik, işletme için müzik yayını, lisanslı müzik hizmeti, yasal müzik yayını, Muzibu Radyo, royalty-free rock and roll, cafe için rock playlist, retro bar müziği, rock\'n roll playlist telifsiz, mağaza için müzik yayını, upbeat retro music, işletmelere özel müzik', 'Radio Rock &amp; Roll ile işletmenizde enerjik ve telifsiz müzik yayını yapın. Bar, kafe ve mağazalarda lisanslı rock\'n roll playlistlerle nostaljik ve ritmik bir atmosfer oluşturun.'),
(76, 'Radio Cocktail', 'radio-cocktail', 'SECTOR_8gp8Jl-e3sF5i-RYkBLL-6jL7bG-f1RYLX-AwnWmH.jpg', '2025-06-17 17:16:56', 'Radio Cocktail | Telifsiz Lounge ve Chill Bar Müzikleri | Muzibu Radyo', 'kokteyl bar müzikleri, telifsiz lounge playlist, bar müzik yayını, yasal müzik yayını, chill bar ambience, Muzibu Radyo, cocktail hour music, royalty-free bar music, elegant lounge music, chillout cocktail stream, evening bar playlist, soft house music', 'Radio Cocktail ile bar, lounge ve kokteyl mekanlarında telifsiz müzik yayını yapın. Yasal ve seçkin playlistlerle keyifli, akıcı ve sofistike bir atmosfer oluşturun.'),
(77, 'Beauty', 'radio-beauty', 'SECTOR_v7rwx9-lPTSlB-gNgsmK-gMuBi7-XIYII6-RPYsQc.jpg', '2025-06-18 18:59:06', 'Beauty Radyo | Telifsiz Güzellik Merkezi Müziği | Muzibu', 'beauty radyo, spa müzik yayını, güzellik merkezi playlist, telifsiz rahatlatıcı müzik, işletme müzik yayını, bakım salonu müzikleri, relaxing music radio, royalty-free spa music, wellness music stream, ambient beauty playlist, Muzibu Radyo, telifsiz güzellik müziği', 'Beauty Radyo ile güzellik merkezleri, spa ve bakım salonlarında huzurlu ve yasal müzik yayını yapın. Telifsiz playlistlerle müşterilerinize sakin ve rafine bir atmosfer sunun.'),
(78, 'Radio Natural Glow', 'radio-natural-glow', 'SECTOR_vKUqwA-NGsOju-X04nbS-fJktOQ-wnYOOQ-mJ1jL4.jpg', '2025-06-18 19:22:18', 'Radio Natural Glow | Telifsiz Akustik, Ambient ve Chill Müzik Yayını | Muzibu Radyo', 'doğal müzik yayını, telifsiz ambient playlist, akustik cafe müziği, yasal müzik yayını, Muzibu Radyo, royalty-free chill music, natural ambiance radio, acoustic background music, relaxing stream, wellness music playlist, soft instrumental vibes, spa and cafe music', 'Radio Natural Glow ile işletmenize dinginlik ve doğallık katın. Telifsiz akustik, ambient ve chill playlistlerle yasal, sade ve huzur veren bir müzik atmosferi oluşturun.'),
(79, 'Silk Touch House', 'silk-touch-house', 'SECTOR_Nml10c-ZRA7J3-53LgAw-Kzb1BH-qDXmyx-dESQa6.jpg', '2025-06-18 20:17:51', 'Silk Touch House | Telifsiz Lounge House Müzik Yayını | Telifsiz Radyo', 'telifsiz müzik, işletme için telifsiz müzik, house müzik yayını, lounge house playlist, yasal müzik yayını, Muzibu Radyo, royalty-free house music, silk touch playlist, cafe için house müzik, bar için telifsiz müzik, lisanslı müzik hizmeti, chill house vibes', 'Silk Touch House ile işletmenizde yumuşak, akıcı ve telifsiz house müzik yayını yapın. Lounge, chill ve deep house playlistlerle yasal, modern ve estetik bir atmosfer oluşturun.'),
(80, 'Radio FastFuel', 'radio-fastfuel', 'SECTOR_i2XKVJ-RunnoS-YjNFCE-zw2lMb-nJt05P-aQhBaO.jpg', '2025-06-18 20:24:05', 'Radio FastFuel | Telifsiz Dinamik Müzik Yayını | Benzin İstasyonları için Kurumsal Radyo', 'benzin istasyonu müzik yayını, telifsiz enerji müzikleri, hızlı tempo radyo yayını, Muzibu istasyon müziği, royalty-free fuel station music, energetic pop stream, road trip vibes, upbeat drive music, yasal müzik lisansı, oto yıkama müzik yayını, fast groove playlist, dynamic retail radio', 'Radio FastFuel ile benzin istasyonunuzda telifsiz ve enerjik müzik yayını yapın. Sürücüler için tempolu, yasal ve dikkat çekici müzik atmosferiyle hizmet kalitenizi artırın.'),
(81, 'Radio Home Table', 'radio-home-table', 'SECTOR_BOAvds-5vu0F1-ZcZ3js-bElR6r-sxWoq8-NffUJQ.jpg', '2025-06-18 21:42:38', 'Radio Home Table | Telifsiz Akustik, Chill ve Soft Müzik Yayını | Muzibu Radyo', 'akustik müzik yayını, telifsiz chill playlist, ev ortamı müziği, soft cafe müziği, Muzibu Radyo, royalty-free acoustic music, cozy background music, home table vibes, soft chill radio, relaxing playlist stream, calm ambient music, işletme müzik yayını', 'Radio Home Table ile ev konforunu işletmenize taşıyın. Telifsiz akustik, chill ve yumuşak playlistlerle huzurlu, samimi ve doğal bir müzik atmosferi oluşturun.'),
(82, 'Radio Soft House', 'radio-soft-house', 'SECTOR_NLOUCy-g2FBd3-srsv7j-sPowSA-ISS9kj-1XYBkX.jpeg', '2025-06-22 17:04:27', 'Radio Soft House | Telifsiz Chill House Müzik Yayını | Telifsiz Radyo', 'telifsiz müzik, işletme için telifsiz müzik, house müzik yayını, chill house playlist, yasal müzik yayını, Muzibu Radyo, royalty-free house music, soft lounge music, cafe için house müzik, bar playlist telifsiz, lisanslı müzik hizmeti, relaxing house stream', 'Radio Soft House ile işletmenizde telifsiz house müzik yayını yapın. Chill, lounge ve soft house playlistlerle yasal, modern ve akıcı bir atmosfer oluşturun.'),
(83, 'Radio Italiano', 'radio-italiano', 'SECTOR_qNNzaE-YHjHZ1-fIdIVf-i8q7ki-wnkpc1-ndaoZ8.jpeg', '2025-06-24 16:01:34', 'Radio Italiano | Telifsiz İtalyan Lounge, Jazz ve Akustik Yayın | Muzibu Radyo', 'italyan müzik yayını, telifsiz italyan playlist, italyan restoran müziği, yasal müzik yayını, Muzibu Radyo, italian lounge music, royalty-free italian jazz, acoustic italian vibes, trattoria playlist, cafe italiano music, mediterranean music stream, elegant italian ambience', 'Radio Italiano ile işletmenize İtalyan zarafetini taşıyın. Telifsiz lounge, jazz ve akustik playlistlerle samimi, sıcak ve yasal bir müzik atmosferi oluşturun.'),
(84, 'Radio Slow', 'radio-slow', 'SECTOR_8hHp04-PAIVNQ-CEc1Fb-voj9jr-icd8BG-kSAm1x.jpg', '2025-06-25 00:40:29', 'Radio Slow | Telifsiz Müzik Yayını | Telifsiz Radyo', 'telifsiz müzik, işletme için telifsiz müzik, slow pop müzik yayını, telifsiz radyo, Muzibu Radyo, lisanslı pop müzik, royalty-free pop music, soft pop playlist, cafe için müzik yayını, mağaza müzik yayını, yasal müzik hizmeti, relaxing pop stream', 'Radio Slow Pop ile işletmenizde yumuşak ve telifsiz pop müzik yayını yapın. Kafe, mağaza ve restoranlar için lisanslı, yasal ve dinlendirici playlistlerle özel bir atmosfer oluşturun.'),
(85, 'Radio Cool', 'radio-cool', 'SECTOR_lyvgta-HdX6pb-mNK9M0-RaWdJ8-9H6VS0-sPV78S.jpeg', '2025-06-26 02:04:09', 'Radio Cool | Telifsiz Groove, Funk ve Lo-Fi Yayını | Muzibu Radyo', 'groove müzik yayını, telifsiz funk playlist, lo-fi instrumental radyo, işletme müzik yayını, cafe chill müzik, Muzibu Radyo, royalty-free groove music, lo-fi funk stream, jazz bass playlist, cool cafe music, stylish background music, soul r&amp;b instrumental', 'Radio Cool ile cafeler, butik mağazalar ve modern işletmeler için groove, funk ve lo-fi tarzda telifsiz müzik yayını yapın. Yasal playlistlerle stil sahibi bir atmosfer oluşturun.'),
(86, 'Radio Spanish', 'radio-spanish', 'SECTOR_PJxGXQ-UnH1Um-UEFAhq-I5UpG2-8Z2jr8-lEETEF.jpeg', '2025-06-28 01:43:59', 'Radio Spanish | Telifsiz İspanyol Müzik Yayını | Telifsiz Radyo', 'telifsiz müzik, işletme için telifsiz müzik, İspanyol müzik yayını, yasal müzik yayını, Muzibu Radyo, royalty-free spanish music, latin playlist telifsiz, cafe için müzik yayını, bar için ispanyol müziği, acoustic latin stream, lisanslı müzik hizmeti, işletme radyo yayını', 'Radio Spanish ile işletmenizde telifsiz İspanyol müzik yayını yapın. Latin ritimler, akustik tınılar ve yasal playlistlerle sıcak, canlı ve özgün bir atmosfer oluşturun.'),
(87, 'Radio Mahser', 'radio-mahser', 'SECTOR_VwaEvC-sQtIbx-Fpa9Fy-eoBuLv-dDtfVw-wEKI5d.jpeg', '2025-06-29 01:23:52', 'Radio Mahşer | Derin Ruhlu Telifsiz Elektronik &amp; Sufi Etkili Yayın | Muzibu Radyo', 'mistik müzik yayını, sufi chill radyo, telifsiz spiritüel müzik, derin elektronik müzik, Muzibu Radyo, neyli atmosferik yayın, royalty-free mystic music, spiritual chill playlist, deep sufi vibes, ambient sufi beats, inner journey music, mahşer temalı radyo', 'Radio Mahşer ile işletmenizde derinlikli, mistik ve içsel bir atmosfer oluşturun. Telifsiz elektronik dokular, ney esintileri ve spiritüel chill öğeleriyle ruhu etkileyen bir yayın sunun.'),
(88, 'Radio Ege', 'radio-ege', 'SECTOR_q0jBU2-DP5obe-034OJd-cnycLA-Ry5VIj-kh4e7G.jpeg', '2025-06-29 01:45:45', 'Radio Ege | Telifsiz Ege ve Akdeniz Esintili Müzik Yayını | Muzibu Radyo', 'ege müzik yayını, telifsiz akdeniz playlist, yasal işletme yayını, sahil müziği telifsiz, Muzibu Radyo, ege esintili playlist, chill mediterranean music, royalty-free mediterranean music, beachside cafe music, summer vibes radio, soft acoustic stream, coastal background music', 'Radio Ege ile işletmenize deniz esintili, huzurlu ve telifsiz müzikler taşıyın. Yasal Ege, Akdeniz ve chill playlistlerle sıcak, samimi ve doğal bir atmosfer oluşturun.'),
(89, 'Radio Kırık Tabaklar', 'radio-kirik-tabaklar', 'SECTOR_j2HAib-HiPq29-rxH5Rd-Z30NPv-E6BRyY-QFPgyR.jpeg', '2025-06-29 01:48:54', 'Radio Kırık Tabaklar | Telifsiz Yunan Müzik Yayını | Opa! Ritimleri Muzibu\'da', 'yunan müzik yayını, telifsiz yunan playlist, opa müzikleri, işletme müzik yayını, Muzibu Radyo, greek tavern music, royalty-free greek music, upbeat greek stream, akdeniz eğlence müziği, greek celebration music, taverna playlist, enerji dolu radyo', 'Radio Kırık Tabaklar ile işletmenizde eğlenceli Yunan müzikleri telifsiz ve yasal şekilde çalsın. Opa ritimleri, hızlı tempo ve Akdeniz enerjisiyle mekanınıza hareket katın.'),
(90, 'Radio France', 'radio-france', 'SECTOR_XhYrTH-U0yY1n-91Qrrx-BywEme-geFKQJ-j2cSMX.jpeg', '2025-07-01 22:53:49', 'Radio France | Telifsiz Fransız Lounge, Jazz ve Akustik Yayını | Muzibu Radyo', 'fransız müzik yayını, telifsiz jazz ve swing, yasal müzik yayını, fransız cafe playlist, Muzibu Radyo, french lounge music, royalty-free french jazz, gypsy jazz stream, french acoustic vibes, cafe de paris music, swing and jazz playlist, elegant cafe music', 'Radio France ile işletmenizde Fransız tarzı telifsiz müzik yayını yapın. Yasal playlistlerle café kültürü, gypsy jazz, swing ve akustik tınılarla zarif bir atmosfer oluşturun.'),
(91, 'Radio Acoustic Guitar', 'radio-acoustic-guitar-', 'SECTOR_cg9qBH-faKlpv-boNSRN-fd1DIP-mXFqBX-Pte3YR.png', '2025-07-03 22:01:52', 'Radio Acoustic Guitar | Telifsiz Radyo', 'akustik gitar radyo, telifsiz akustik müzik, işletme müzik yayını, huzurlu müzik playlist, acoustic guitar radio, royalty-free acoustic music, relaxing guitar playlist, acoustic background music, cafe playlist telifsiz, Muzibu Radyo, acoustic ambience, guitar chill stream', 'Radio Acoustic Guitar ile işletmenizde doğal ve yasal müzik yayını yapın. Telifsiz akustik gitar tınılarıyla huzurlu, sıcak ve samimi bir atmosfer oluşturun.'),
(92, 'Radio World Pop', 'worldpop', 'SECTOR_42uJ5C-Qr99mt-jHcRAm-YtjBtK-1QCSzy-xU5YWl.jpeg', '2025-07-04 15:26:54', 'Radio World Pop | Telifsiz Radyo', 'telifsiz müzik, işletme için telifsiz müzik, global pop müzik yayını, yasal müzik yayını, Muzibu Radyo, royalty-free world pop music, multilingual playlist, cafe pop yayını, mağaza müziği telifsiz, lisanslı pop müzik, world music stream, işletmeler için müzik', 'Radio World Pop ile işletmenizde dünya çapında pop müziklerle telifsiz yayın yapın. Yasal, enerjik ve çok dilli playlistlerle mağaza, kafe ve restoranlarda modern bir atmosfer oluşturun.');
INSERT INTO `muzibu_radios` (`id`, `title_tr`, `slug`, `thumb`, `created`, `meta_title`, `meta_keywords`, `meta_description`) VALUES
(93, 'Radio Lounge Chill', 'radio-lounge-chillout-', 'SECTOR_m9JvZW-7pUQdW-2I3crd-rJQ8HV-PQkJfb-4KFAOs.jpeg', '2025-07-10 18:42:45', 'Radio Lounge Chillout | Telifsiz Lounge ve Chillout Müzikler', 'lounge chillout radyo, telifsiz lounge müzik, Muzibu Radyo, chill arka plan müziği, otel müzik yayını, restoranlar için müzik, chillout lounge stream, royalty-free chillout, background lounge music, hotel music playlist, relaxing radio, ambient chill', 'Radio Lounge Chillout, otel lobileri, restoranlar ve dinlenme alanları için özel seçilmiş telifsiz lounge ve chillout müzik yayınları sunar. Huzurlu bir atmosfer için ideal.'),
(94, 'Radio Lounge House', 'radio-lounge-house', 'SECTOR_U89wdD-BbX6B5-dFZK2F-LDfS4B-3DZGhc-LAbj71.jpeg', '2025-07-12 14:23:29', 'Radio Lounge House | Telifsiz Lounge ve Deep House Müzikleri | Muzibu Radyo', 'lounge house radyo, telifsiz house müzik, chill house playlist, Muzibu Radyo, deep house yayını, restoranlar için müzik, royalty-free lounge house, hotel deep house music, chillout club music, background house stream, ambient house playlist, lounge beats radio', 'Radio Lounge House, restoran, otel ve kafeler için telifsiz lounge house, chill house ve deep house yayınları sunar. Modern ve ritmik bir atmosfer için mükemmel bir seçim.'),
(95, 'Afro House Radio', 'radio-afro-house', 'SECTOR_l1ufpg-IByx4N-b7F8Zg-uiaxMi-qcOJYd-vtfSk7.jpg', '2025-07-13 16:57:07', 'Radio Afro House | Telifsiz Radyo', 'afro house radyo, telifsiz house müzik, işletme müzik yayını, afro playlist telifsiz, yasal müzik yayını, afro chill stream, Muzibu Radyo, african house music, royalty-free afro house, deep tribal beats, afro lounge playlist, energetic music radio', 'Radio Afro House ile işletmenize ritim ve enerji katın. Telifsiz ve yasal Afro House playlistleriyle dinamik, modern ve etkileyici bir atmosfer oluşturun.'),
(96, 'Radio Tasavvufi', 'radio-tasavvufi', 'SECTOR_OwvQJL-dN7gBy-IF0Gbe-Ilg4pd-4U49lD-qS5AcS.png', '2025-07-14 17:51:55', 'Radio Tasavvufi | Telifsiz Radyo', 'telifsiz müzik, işletme için telifsiz müzik, tasavvufi müzik yayını, sufi playlist telifsiz, ney müziği yayını, Muzibu Radyo, royalty-free sufi music, spiritual background music, yasal müzik yayını, huzur verici müzik, lisanslı tasavvuf müziği, işletmelere özel radyo', 'Radio Tasavvufi ile işletmenizde huzurlu ve telifsiz müzik yayını yapın. Ney, sufi ezgiler ve tasavvufi tınılarla yasal, dingin ve ruhani bir atmosfer oluşturun.'),
(99, 'Radio Metal', 'radiometal', 'SECTOR_1mHMvb-YJglE0-CjRELL-jvIotk-VOQmtU-BEOqdu.jpeg', '2025-07-31 19:19:35', 'Radio Metal | Telifsiz Metal ve Hard Rock Müzik Yayını | Muzibu Radyo', 'metal müzik yayını, telifsiz hard rock, bar için metal playlist, yasal müzik yayını, Muzibu Radyo, royalty-free metal music, heavy rock radio, metal bar ambience, energetic rock playlist, live rock music stream, metal pub music, hard sound background', 'Radio Metal ile bar, pub ve etkinlik alanlarında telifsiz metal müzik yayını yapın. Hard rock, heavy metal ve enerjik playlistlerle yasal, güçlü ve dikkat çekici bir atmosfer oluşturun.'),
(100, 'Radio Alaçatı', 'radio-alacati', 'SECTOR_U9RSxJ-SwtX4C-I60fv0-lUN6Vj-njws12-RIQ9f8.jpg', '2025-08-06 22:05:03', 'Radio Alaçatı | Telifsiz Müzikler', 'radio alaçatı, telifsiz radyo, chill playlist, telifsiz müzik, lisanslı müzik, işletme için telifsiz müzik, yazlık mekan müziği, lounge vibes, soft house, beach bar sound, relaxing music', 'Alaçatı&#039;nın rüzgarını taşıyan chill ve lounge müzikler. Telifsiz ve lisanslı içeriklerle işletmenize özel akış listeleri.'),
(101, 'Radio Japanese Lounge', 'radio-japanese-lounge', 'SECTOR_gDQmnf-C9SxhS-bKRpMz-ELpcaD-AVvX98-b9ioJg.jpeg', '2025-08-21 17:49:43', 'Radio Japanese Lounge', 'Japanese Lounge House, lounge house Japan, Japon restoran müziği, otel müziği, zarif fon müziği, restoran için müzik, modern Japon estetiği, ambient house, chill house playlist, işletme müziği, rooftop lounge müziği', 'Japanese Lounge House playlisti; yavaş akan, akıcı ritimlerle işletmelere zarif ve huzurlu bir atmosfer sunar. Özellikle sushi restoranlarında, çatı katı lounge alanlarında, otel lobilerinde ve spa bölümlerinde estetik bir fon müziği olarak idealdir. Japon kültüründen ilham alan bu seçki, mekânın ruhunu müzikle buluşturur.'),
(102, 'Radio Indie Rock', 'radio-indie-rock', 'SECTOR_0x1Enx-od96wf-rhk2gW-KWVNLZ-zdKkJf-6kD4zs.jpeg', '2025-08-26 14:55:25', 'Radio Indie Rock', 'telifsiz müzik, indie rock radyo, lisanslı müzik, işletme için müzik, kafe müziği, restoran playlist, alternatif rock, bağımsız müzik, chill rock yayını, Muzibu radyo, indie vokal, özgün sahne tınıları, modern işletme müziği', 'İşletmeler için %100 telifsiz ve lisanslı Radio Indie Rock yayını. Duygusal vokaller, özgün melodiler ve bağımsız ruhla mekanınıza modern bir hava katın.'),
(103, 'Artist Muzibu House', 'artist-muzibu-house', 'SECTOR_jBOQSu-Lbepns-XeinY3-KzkBiO-RXKUhy-knWZ06.jpg', '2025-09-01 16:33:14', 'Artist Muzibu House | İşletmeler için Telifsiz House Müzik', 'telifsiz müzik, işletme için telifsiz müzik, lisanslı müzik, house müzik playlist, lounge house, deep house, restoran müzik yayını, kafe için müzik, otel için müzik, Muzibu', 'Artist Muzibu House, restoran, kafe, otel ve mağazalar için seçilmiş house müzik playlistleri sunar. %100 lisanslı ve telifsiz müzik yayınlarıyla marka imajınızı güçlendirin.'),
(104, 'Radio Irish Pub', 'radio-irish-pub', 'SECTOR_ScwtPH-p8IWFl-bZkz4J-7pcRuJ-tlkSF8-8CWQMK.jpeg', '2025-09-16 14:53:10', 'Irish Pub Radio', 'irish pub, irlanda müziği, celtic folk, irish traditional, pub müzik, irlanda bar, irish drinking songs, folk müzik, radio irish pub, irish culture', 'İrlanda pub kültürünün ruhunu yansıtan canlı melodiler, folk ezgiler ve samimi atmosfer. Eğlenceli sohbetlere, dostluklara ve keyifli içkilere eşlik eden otantik İrlanda tınılarıyla dolu bir radyo deneyimi.'),
(105, 'Muzibu Mood On', 'muzibu-mood-on', 'SECTOR_24UF61-Borbnv-a8DBNl-BDJ8cG-XdSN8s-VIQ2Kh.jpg', '2025-09-17 22:40:16', 'Mood On – Enerjik Radio', 'mood on, playlist cover, energetic music, funk music, disco vibe, indie pop, electronic groove, bar music, cafe playlist, vibrant sound, stylish music, retro modern, music artwork, live performance, stage energy, neon vibe, music branding', 'işletmeler, kafeler ve yaratıcı ortamlar için hazırlanmış enerjik müzik listesi. Funk, disco, indie pop ve elektronik türlerini bir araya getiren Mood On playlist&#039;i ile modun hep açık kalsın.'),
(106, 'Radio Hard Rock', 'radio-hard-rock', 'SECTOR_vCl514-n3bIdu-lipS4u-0TDjzW-ECLY7Q-NIxqAY.jpg', '2025-10-05 01:09:43', 'Radio Hard Rock', 'hard rock playlist, bar müziği, işletmeler için rock müzik, progresif rock şarkılar, muzibu playlist önerisi, sert progresif rock, mekan müziği önerisi, alternatif mekan rock, atmosferik rock playlist', 'hard rock playlist, bar müziği, işletmeler için rock müzik, progresif rock şarkılar, muzibu playlist önerisi, sert progresif rock, mekan müziği önerisi, alternatif mekan rock, atmosferik rock playlist'),
(107, 'Radio Spa', 'radio-spa', 'SECTOR_AXLrE2-BMlAJm-tZa78H-fMPKGr-RYr4ak-U2Segs.jpg', '2025-10-11 23:02:07', 'Radio Spa', 'Radio Spa', 'Radio Spa'),
(108, 'Radio Piano', 'radio-piano', 'SECTOR_ZekKZn-tWMPKN-Arq322-IkQib6-wMAgtu-MHFMRk.jpg', '2025-10-12 22:44:32', 'Radio Piano', 'piano spa playlist,\r\nrahatlatıcı piyano müzikleri,\r\nspa müziği,\r\npiyano masaj müziği,\r\nterapi müziği,\r\nmeditasyon için piyano,\r\nişletmeler için spa müziği,\r\nfon müziği,\r\npiyano chill müzik,\r\nmuzibu playlist önerisi', 'Rahatlatıcı piyano tınılarıyla spa, masaj ve terapi ortamlarını tamamlayan huzur dolu bir playlist. İşletmeler için ideal arka plan müziği.'),
(109, 'Radio Jazz Dinner', 'radio-jazz-dinner', 'SECTOR_z9O5Ps-mIYbsp-7YUd9B-YUK8TB-fbOaGe-Mcy5Rv.jpg', '2025-10-20 20:28:26', 'Radio Jazz Dinner', 'jazzy dinner playlist,\r\nakşam yemeği caz müziği,\r\nrestoran müziği,\r\nsoft jazz playlist,\r\ndinner jazz tunes,\r\narka plan müziği,\r\notel restoran müziği,\r\nişletmeler için caz müzik,\r\nmuzibu playlist önerisi,\r\nelegant dinner music,\r\nevening jazz', 'Akşam yemeği saatlerine zarafet ve sıcaklık katan caz ezgileri. Restoranlar, oteller ve şık etkinlikler için ideal jazzy dinner playlist.'),
(110, 'Radio Pop Rock', 'radio-pop-rock', 'SECTOR_GhljWG-UXnIbh-tnJmVy-b0gFu0-dyh66g-ezCiRz.jpg', '2025-10-24 20:36:37', 'Radio Pop Rock', 'Radio Pop Rock', 'Radio Pop Rock'),
(111, 'Radio Café French', 'radio-french-cafe', 'SECTOR_8mOvXg-90Ivow-3yVt6D-QdvDWb-EU1xr6-DoToX7.jpg', '2025-10-25 01:01:13', 'Radio French Café', 'Radio French Café', 'Radio French Café'),
(112, 'Radio Italian Café', 'radio-italian-cafe-', 'SECTOR_mrBdU1-iiZDPe-f0kjd4-8EyKYT-pXlKuv-0uanVp.jpg', '2025-10-25 01:12:07', 'Radio Italian Café', 'Radio Italian Café', 'Radio Italian Café'),
(113, 'La Moda Italiana', 'la-moda-italiana', 'SECTOR_qiRbYm-rkjdD0-F8hclO-jDwkrb-F6JNdX-yV1vXX.jpg', '2025-10-25 01:22:25', 'La Moda Italiana', 'La Moda Italiana', 'La Moda Italiana'),
(114, 'Radio Paris Mode', 'radio-paris-mode', 'SECTOR_tgstPC-Lj5DvG-YwaPkM-qxxZ3x-0rRmKF-XicGXD.jpg', '2025-10-25 01:31:22', 'Radio Paris Mode', 'Radio Paris Mode', 'Radio Paris Mode'),
(115, 'Radio Happy Time', 'radio-happy-time', 'SECTOR_fMJIbM-Rz0oWy-v3zzzB-gG9fgR-JRlLSd-4oUjFW.jpg', '2025-10-26 13:58:45', 'Radio Happy Time', 'Radio Happy Time', 'Radio Happy Time'),
(116, 'Radio Spanish Cafe', 'radio-spanish-cafe', 'SECTOR_QVMYPn-b3L6kR-9pKDY8-hc2Wmt-qJ7siK-cqiSZR.jpg', '2025-10-26 15:01:56', 'Radio Spanish Cafe', 'Radio Spanish Cafe', 'Radio Spanish Cafe'),
(117, 'Radio Chill Cafe', 'radio-chill-cafe', 'SECTOR_4KYJH9-08IIJ0-S2Qm8o-r08noL-fgBF3p-f43QmR.jpg', '2025-10-27 03:10:12', 'Radio Chill Cafe', 'Radio Chill Cafe', 'Radio Chill Cafe'),
(118, 'Deep House Radio', 'deep-house', 'SECTOR_sgTVTp-6AjCtq-qIePwo-YkPPEI-OgSrON-pZWlSG.jpg', '2025-11-03 15:36:44', '', 'Deep House', 'Deep House'),
(119, 'Tech House Radio', 'tech-house-radio', 'SECTOR_tCvsX0-pHPQsu-ILwyn3-OEZl13-P9pzVB-NqaMDs.jpg', '2025-11-04 14:15:50', '', '', ''),
(120, 'Radio Stretch &amp; Relax', 'radio-stretch-relax', 'SECTOR_2YiOvq-TbLKIv-xBAH52-WZspyv-a4oixG-P9zv6i.jpg', '2025-11-05 02:29:19', 'Stretch &amp; Relax', 'Stretch &amp; Relax', 'Stretch &amp; Relax'),
(121, 'Pop Radio', 'pop-radio', 'SECTOR_naCb9e-5lkIBY-SlkePp-ETeUsq-EknzB4-VfHXNX.jpg', '2025-11-11 21:30:12', 'Pop Radio', '', ''),
(122, 'Bossa Nova Radio', 'radio-bossa-nova', 'SECTOR_4CrUgz-bRhuNb-VM0Dg6-74Os6H-kmKxHc-w94rSP.jpg', '2025-11-12 17:52:04', '', '', ''),
(123, 'Acoustic Radio', 'acoustic-radio', 'SECTOR_uUuG6s-tlkpcK-ruWgdt-RtX6Nh-WEbskG-f1W0BR.jpg', '2025-11-15 17:04:09', 'Acoustic Radio', 'Acoustic Radio', 'Acoustic Radio'),
(124, 'Happy Retro Cafe', 'happy-retro-cafe', 'SECTOR_Wb34fS-l9bxaX-L9xTrN-KpF5qo-JzO42a-ytf9f0.jpg', '2025-11-17 02:46:20', 'Happy Retro Cafe', 'Happy Retro Cafe', 'Happy Retro Cafe'),
(125, 'Coffee shop Radio', 'coffee-shop-radio', 'SECTOR_v9vZjd-PxD4nw-wDWZmr-8P17dU-NO6o3n-umUeku.jpg', '2025-11-19 19:22:28', '', '', ''),
(126, 'Beer Rock Radio', 'beer-rock-radio', 'SECTOR_1l5ITe-CSP6Ns-bMWaWg-DQUhlW-A1tOzf-jdVFfO.jpg', '2025-11-20 12:03:21', '', '', ''),
(127, 'Jazz Cafe Radio', 'jazz-cafe-radio', 'SECTOR_mHTYJ7-e5RYAS-AwV0CS-lasChb-NuCINB-os0TiN.jpg', '2025-11-23 13:57:43', '', '', ''),
(128, 'Coffee Shop Beats', 'coffee-shop-beats', 'SECTOR_dWPAEh-HHqa2R-3O9f0I-MlBUZ1-zb20q8-BpYphh.jpg', '2025-11-23 18:50:57', '', '', ''),
(129, 'Cozy Café Radio', 'cozy-cafe-radio', 'SECTOR_PuDUxf-hk5IJT-pwmkpQ-j2DGRv-yywu94-G7R5ZW.jpg', '2025-11-24 03:00:37', '', '', ''),
(130, 'Retro Pub Radio', 'retro-pub-radio', 'SECTOR_IYcf6R-VKJmhc-ROXY4f-2ptAnE-sLSLpS-xKiy17.jpg', '2025-11-24 18:50:34', '', '', ''),
(131, 'Christmas Radio', 'radio-christmas-8d-edition', 'SECTOR_vQmHy6-vTjxxn-mZWGAv-0JUQZL-Q0dfwg-bose35.jpg', '2025-11-28 02:39:11', '', '', ''),
(132, 'Coffee Shop Rock', 'coffee-shop-rock', 'SECTOR_ZjyrvU-iSBN5e-oXw5Zs-hpgpOJ-0vPsz2-nAybq5.jpg', '2025-11-28 19:36:21', '', '', ''),
(133, 'Chill House', 'chill-house', 'SECTOR_56qInM-TolewU-GYk2sc-VPuJEZ-G7vTWb-dtp4Fk.jpg', '2025-11-29 21:22:58', '', '', ''),
(134, 'Radio Techno Workout', 'radio-techno-workout', 'SECTOR_zTJSmr-D0YuKk-tvGOx9-EtLFdx-7YPCfq-z4xf0w.jpg', '2025-12-02 04:16:30', '', '', ''),
(135, 'Boutique Mix Radio', 'soft-luxe-radio', 'SECTOR_W2Ti79-X4LxNa-YGflDW-0f5Fdk-fQd2kH-gOd8Wd.jpg', '2025-12-05 12:57:09', '', '', ''),
(136, 'Radio Folk', 'radio-folk', 'SECTOR_DU5E0m-bpvd1J-YumOBq-nvzDw2-HRBTVL-4WlHAj.jpg', '2025-12-09 17:06:06', '', '', ''),
(137, 'Funky Disco House', 'funky-disco-house', 'SECTOR_xDBtjX-cV2sSZ-9IiKQG-Si6JN9-wYZwkQ-q7JkgI.jpg', '2025-12-24 21:03:18', '', '', ''),
(138, 'Jazz House Radio', 'jazz-house-radio', 'SECTOR_BFhdJb-6xi8hZ-YZloE4-loD3Af-BX9ut1-k7ZURv.jpg', '2025-12-29 22:13:10', '', '', '');

--
-- Dökümü yapılmış tablolar için indeksler
--

--
-- Tablo için indeksler `muzibu_radios`
--
ALTER TABLE `muzibu_radios`
  ADD PRIMARY KEY (`id`);

--
-- Dökümü yapılmış tablolar için AUTO_INCREMENT değeri
--

--
-- Tablo için AUTO_INCREMENT değeri `muzibu_radios`
--
ALTER TABLE `muzibu_radios`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=139;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
